### ISSUE TITLE
RTL Languages shown LTR in Preview

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-android#1005]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
RTL languages should always be shown RTL

### Observed
When tapping Preview in the app RLT languages show LTR

### Reproduced
1. Add a RTL Keyboard like Hebrew to your Android device
2. Switch input to that while in a note. You will see the cursor move from left to right as expected
3. Enter text
4. Tap Preview

![](https://d.pr/i/hviU9h+)
(Image link: https://d.pr/i/hviU9h )

![](https://d.pr/i/MyoUoI+)
(Image link: https://d.pr/i/MyoUoI )

Make|Model|Android Version|App Version
-|-|-|-
Pixel|3|Android 10|2.5.1
Unknown|Unknown|Unknown|2.5.1

**Comment by iskandergaba** [comment]
I believe I found a very simple fix that fixes the majority of RTL and mixed RTL/LTR text issues without breaking anything or introducing new problems.

PR soon. Teaser below :smiley:

![after1](https://user-images.githubusercontent.com/18679771/85229347-76329600-b3e9-11ea-942b-e59370af431d.png)
![after4](https://user-images.githubusercontent.com/18679771/85229348-76cb2c80-b3e9-11ea-908d-ecb7e4e0854d.png)
