### ISSUE TITLE
Markdown numbered list renders incorretly in Preview + Published notes went entered on first line

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-android#1008]
### Issue
When the number 1 is entered on the first line of a note in with markdown enabled the next number in the ordered list is shown as 1 as well. It's as if Simplenote doesn't "see" the first number as part of the ordered list

### Reproduced

Enter text like this:

![](https://d.pr/i/XGODwe+)
(Image link: https://d.pr/i/XGODwe )

It will preview and publish like this

![](https://d.pr/i/xClvmt+)

(Image link: https://d.pr/i/xClvmt )

The issue is resolved by entering a line between the title and the first number in the ordered list. 

Make|Model|Android Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|ANDROID_VERSION|APP_VERSION
Pixel |3|Android 10|2.5.1
Samsung Galaxy note| 4| Android 6.0.1| 2.5.1

Reported in #2868400-zen

**Comment by msilbers** [comment]
This is expected as the first line would be the "title" and as our markdown requires an extra line above lists. Not sure which of those apply to the issue as the screenshots 404, but I'm closing this.
