### ISSUE TITLE
Note pinning from note list doesn't sync until note editor is opened

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#1016]
### Expected

If I pin or unpin a note from the note list, it should sync immediately.

### Observed

If I pin or unpin a note from the note list, it doesn't sync to other devices until I open the note in the note editor.

### Reproduced

1. In the app, long tap on a note in the note list.
2. Tap the pin icon at the top of the screen to pin/unpin the note.
3. On another device, notice that the pinned status hasn't synced.
4. In the app, tap on the note to open it in the note editor.
5. On the other device, notice that now the pinned status is synced.

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.6-rc-1

**Comment by theck13** [comment]
The app doesn't sync until it is resumed from being in the background, which includes opening the note editor or note list.  It's expected behavior to not sync unless the note is edited while the app is in the foreground.

I'll add this to the **_Simplenote Groundskeeping_** project for now.

**Comment by ParaskP7** [comment]
👋 @rachelmcr !

I have just tested this with the below device/version and it seems to be working as expected, can you double check on your side that note pinning sync is still not working as expected? I tested it with one physical device (Pixel 4), one virtual device (Pixel 4) and a connected web client (`https://app.simplenote.com/`). They all sync instantly, there isn't even a slight delay involved.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 4|11|2.14-rc-1

**Comment by rachelmcr** [comment]
Thanks for the ping! Yep, I confirmed the note pinning sync is working as expected, as tested in 2.14-rc-1. I'll close this as resolved.

**Comment by ParaskP7** [comment]
> Thanks for the ping! Yep, I confirmed the note pinning sync is working as expected, as tested in 2.14-rc-1. I'll close this as resolved.

Thank you Rachel! 🌟
