### ISSUE TITLE
Select next note after trashing/restoring a note in tablet landscape

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#1021]
### What

Two suggested changes to the tablet landscape behavior:

* Select the note below a recently trashed note.
* Select the note below a recently restored note in trash view.

Currently, the Android app shows a split view (note list and note editor) in tablet landscape view. When a note is trashed, or a trashed note is restored, the note editor is blank until another note is manually selected:

![android-notes-loading](https://user-images.githubusercontent.com/8658164/81166497-9ae2c380-8f8b-11ea-8e64-4784dacaf2d2.gif)

(As observed on HTC Nexus 9, Android 7.1.1, Simplenote Android 2.6-rc-1.)

The current Electron behavior is to select the next note in the list when a note is trashed/restored, so the note editor is never blank:

![electron-notes-loading](https://user-images.githubusercontent.com/8658164/81166588-b221b100-8f8b-11ea-8866-8071a34f7829.gif)

(As observed on a Macbook Pro, macOS 10.15.4, Simplenote Electron 1.16.0 in Chrome.)

### Why

This enhancement would bring the Android tablet landscape behavior in line with Electron behavior.

**Comment by theck13** [comment]
This is expected behavior.  I'll add this to the ***Simplenote Android*** project under the ***Feature parity*** column for now.
