### ISSUE TITLE
Fix status bar display when opening drawer

### ISSUE THREAD

**Issue by stavares843** [Automattic/simplenote-android#1047]
- When user opens the drawer (lateral menu), the status bar doesn't display properly. 

I added a screenshot from Google Play store app vs Simplenote app. 

If you notice, on the Google Play store app, when opening the drawer, the status bar has a white background from the start to the end. 

On the Simplenote app, when opening the drawer, the status bar has a white background only on the drawer area.

### STR - Steps to reproduce
- Compile `develop` branch
- Open the Simplenote app
- Login
- Open drawer

### Expected
- Status bar should have a white background from start to end when opening the drawer.

Screenshot

<img width="1103" alt="Screenshot 2020-05-29 at 00 04 04" src="https://user-images.githubusercontent.com/29093946/83202782-453fa800-a140-11ea-8cef-0e275e017201.png">

Make|Model|Android Version|App Version
-|-|-|-
Google | Pixel 2 G011A | API 28, Android 9 |2.6-rc-1 debug (Build 103) develop branch

**Comment by theck13** [comment]
Simplenote is using expected behavior.

**Comment by stavares843** [comment]
I added this because seems the Google apps use it that way and they are usually a reference for material design so I thought it was more following the design guidelines on the Google Play Store app. Thanks for checking! 😄
