### ISSUE TITLE
Making Simplenote available on F-Droid?

### ISSUE THREAD

**Issue by LenzGr** [Automattic/simplenote-android#1066]
### What
It would be great if Simplenote would be available for download from not just only the Google Play Store, but pure open source software repositories like [F-Droid](https://f-droid.org/).

There is an [open request](https://gitlab.com/fdroid/rfp/-/issues/1317) on the F-Droid request tracker, it would be great if some engineers from Automattic could help out here in getting this accomplished.

### Why
This would help to extend the user base to Android users who do not want to set up a Google account for privacy reasons. Since Simplenote is an Open Source application, F-Droid would be a very suitable platform.

### How
Please get in touch with the F-Droid team to resolve any issues that might be preventing the inclusion.

**Comment by theck13** [comment]
Thanks for the request!  This was brought up a few years ago and has been discussed in https://github.com/Automattic/simplenote-android/issues/382.  Since nothing has changed, I'll mark this as a duplicate and close.
