### ISSUE TITLE
Remove duplicated tags

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1071]
### Expected
How to get rid of duplicated tags?

### Observed
- Some of my tags are duplicated.
- Some are not sorted alphabetically, 
although in Settings "sort tags alphabetically" is **active**

### Reproduced
- Press on Menu Button, 
- tags on the left side appear double and are not sorted.

### Make|Model|Android Version|App Version
Samsung Galaxy S9+ | Android 10 | Simplenote for Android 2.6

**Comment by theck13** [comment]
This appears to be a question.  Email us at support@simplenote.com for help.

**Comment by gubrist** [comment]
Sorry for not beeing precise: I consider the appereance of duplicated tags as a bug.

**Comment by gubrist** [comment]
Which solution is available, meanwhile?
