### ISSUE TITLE
Scrolling not working on Simplenote with Samsung Tab SE

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/simplenote-android#1073]
On long notes with or without Markdown, Simplenote will not fully scroll to the bottom of a note on Samsung Tab SE. This only happens in Landscape Orientation--the scrolling works fine on this device when it's in Portrait Orientation.

The user has done testing on his Samsung Galaxy Note 8 and there is no 

### Expected
Expect scrolling to work properly on all devices and in all orientations

### Observed
Note gets "stuck" when scrolling to the bottom of it on the Samsung Tab SE.

### To Reproduce:
> 1. Create long note in Simplenote with or without Markdown.
> 2. Open note in Samsung Tab SE and put tab into Landscape Mode.
> 3. Try scrolling to the bottom of the note. 

User shared a video:
https://drive.google.com/file/d/1SK9D2A_qnYHsYob83st6icVUn_Qn4bAE/view

Make|Model|OS Version|APP_VERSION
-|-|-|-
Samsung|Tab SE|Android 9.0|1.7

**Comment by theck13** [comment]
Is this still an issue?  It was reported a year ago and we've made changes to the note layout since then.  Unfortunately, I don't have a Samsung Galaxy Tab SE to test it.

**Comment by theck13** [comment]
Since this issue appears to be abandoned, I'm closing it.  Feel free to reopen it if the issue still exists.
