### ISSUE TITLE
Remove Travis CI

### ISSUE THREAD

**Issue by mokagio** [Automattic/simplenote-android#1085]
I noticed we have both CircleCI and Travis running here, with CircleCI being the only required one.

![image](https://user-images.githubusercontent.com/1218433/86123703-4d16b180-bb1d-11ea-8a2f-c42ec77395ae.png)

@theck13 is there a particular reason to keep the redundancy or shall I go ahead and remove Travis?

**Comment by theck13** [comment]
> @theck13 is there a particular reason to keep the redundancy...

Nope!

> ...shall I go ahead and remove Travis?

Yep!

I'm all for removing Travis CI.  It's always slower than CircleCI, and CircleCI has more coverage.
