### ISSUE TITLE
last release(s) lack changelog(s) in fastlane

### ISSUE THREAD

**Issue by IzzySoft** [Automattic/simplenote-android#1089]
The current release (versionCode 108) has no corresponding changelog (`108.txt`) in fastlane. You might want to add that (also with future releases). Thanks!

**Comment by mokagio** [comment]
Hi @IzzySoft, thank you so much for this report.

I think that happened because I didn't run the command that updates the localized changelogs as part of building version 2.7.1.

They will be there when we ship 2.8.0. 👍

**Comment by IzzySoft** [comment]
Great, thanks! I wasn't sure if something was missed or skipped intentionally. Good to know it will be back!

**Comment by theck13** [comment]
I'll close this issue for now.  Feel free to reopen it if the changlogs are not in future releases.

**Comment by IzzySoft** [comment]
Will do, thanks again!
