### ISSUE TITLE
Search only in selected tag

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1105]
### What
I want to show search results only in the selected tag.
(Simplenote Android App 2.7)

### Why
I loose the oversight. 
Currently search results are shown of all tages (regardless of the selected tag).

It is availble in Simplenote Electron (Windows 10 Desktop)

### How
As in Simplenote Electron (Windows 10 Desktop)

**Comment by theck13** [comment]
You can search notes with specific tags by using the "tag:" prefix.  To search for notes containing the text "email" with the "work" tag, enter the following in the search field.
> tag:work email

You can also search with multiple tags too.  To search for notes with the tags "work" and "to-do" with "email" text, enter this in search.
> tag:work tag:to-do email

**Comment by gubrist** [comment]
Thanks. This user experience looks like programming a search string.

- May I suggest to let it work as in Simplenote Electron (Windows 10 Desktop)?

**Comment by theck13** [comment]
I'll add your suggestion to our feature requests.

**Comment by gubrist** [comment]
We are on Simplenote Android Version 2.21 (144)
- Is there an update?

The electron version has evolved, meanwhile:

![search](https://user-images.githubusercontent.com/22197180/136036458-052b4518-d0b8-4a47-8a67-664610d259a1.JPG)

**Comment by gubrist** [comment]
We are on Simplenote Android Version 2.23 (148) now.

Is there an update?

**Comment by gubrist** [comment]
Any update on this?
