### ISSUE TITLE
Tab-Indented Checklist Items are Not Checkable/Uncheckable

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-android#1118]
### Expected
Checklist items are tappable to allow checking/unchecking when indented with spaces or tabs.

### Observed
Checklist items are tappable to allow checking/unchecking when indented with spaces, but not tabs.

### Reproduced
0. Create note with tab-indented checklist items on macOS or web.
1. Open note from Step 0 on Android.
2. Tap indented checklist items.
3. Notice checklist items do not check/uncheck.

Device Make: Google
Device Model: Pixel 3
Android Version: 10.0.0
Simplenote Version: 2.9.0-rc1

**Comment by reginabally** [comment]
Additional info for 3309347-zen:

Android version: 10
Simplenote version: 2.9
