### ISSUE TITLE
Note Widget doesn't stick

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-android#1119]
### Expected

I would expect that after trying to add a new note widget, it would stay in place on the home screen. 
### Observed

The note widget is immediately removed when added. The same isn't happening with the List Widget. 

### Reproduced

1. Add a new widget to the homescreen and select the note widget
2. The note is removed as soon as it's added
3. This happens for both new and old note widgets.
4. Add a note list widget and this one remains.

Device Make: Samsung
Device Model: S9
Android Version: 9.0
Simplenote Version: 2.8.0

User reported in 3190998-zen on a Xiaomi redmi note 7 with latest Simplenote version.

**Comment by theck13** [comment]
I can't reproduce that behavior with stock Android and the Pixel launcher.  Widgets depend on the launcher, which can vary by device.  What launcher app is being used?

**Comment by rezzap** [comment]
Microsoft launcher is used on the Samsung S9+. I'm not sure what the user is using, but I can ask if needed.

**Comment by theck13** [comment]
I can't reproduce it with the Microsoft Launcher either.  Here are the launchers I've tried without issue.
- Pixel v10
- Nova v6.2.12
- Microsoft v5.11.5.56362

I don't have a Samsung Galaxy S9+ to test, but it seems like it could be device-specific since it works on stock Android with those launchers.

**Comment by rezzap** [comment]
It looks like there was some confusion on my end about needing to select the note before the widget sticks. We were following these steps in testing:

1. Hold down on homescreen select add widgets.
2. Scroll to Simplenote, add the note (Dark) widget to the home screen. 
3. Drag on to the homescreen.
4. The Widget opens automatically.
5. Press Cancel
6. The widget is now removed. 

When a note is selected at step 4 as is required for it to stick, the widget is added. Will confirm this with the user and close this issue for now.
