### ISSUE TITLE
Ability to import/export as individual text files

### ISSUE THREAD

**Issue by draco-malfoy** [Automattic/simplenote-android#1142]
Would have been great if it was possible to import and export notes to/from the android app.

Currently, all the notes are exported as a single JSON file in simplenote's proprietary format.
This makes it difficult to import them elsewhere (mobile/desktop).

This would make reading the files anywhere as basic text reading is natively supported everywhere

This feature is already available on simplenote for Windows/MacOS.

**Comment by theck13** [comment]
I have added it to our feature requests.  In the future, use the template for creating issues or the issue with be closed without comment.
