### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by psmaheshwa** [Automattic/simplenote-android#1159]
I have signed up Simplenote using browser. I've used password having space character. And tried to login via Android App, form validation throws error alert. Kindly fix this bug.

**Comment by codebykat** [comment]
Thanks, moving this to the Android app repository. Spaces should be allowed in passwords.

**Comment by theck13** [comment]
@psmaheshwa, spaces are allowed in passwords.  See [the code snippet used for passwords](https://github.com/Simperium/simperium-android/blob/098bece0f6fe0f41bd13359b08f28482faf5a76d/Simperium/src/main/java/com/simperium/android/CredentialsActivity.java#L371-L377) shown below for details.

``` java
// Password is valid if:
// - Meets minimum length requirement based on login (PASSWORD_LENGTH_LOGIN) and signup (PASSWORD_LENGTH_MINIMUM)
// - Does not have new lines or tabs (PATTERN_NEWLINES_RETURNS_TABS)
// - Does not match email address
private boolean isValidPassword(String email, String password) {
    return isValidPasswordLength(mIsLogin) && !PATTERN_NEWLINES_RETURNS_TABS.matcher(password).find() && !email.contentEquals(password);
}
```

If you're having trouble logging in, email us at support@simplenote.com for help.
