### ISSUE TITLE
Checkbox is shown in markdown edit mode and  `- [ ]` is shown in preview mode

### ISSUE THREAD

**Issue by designsimply** [Automattic/simplenote-android#1186]
# Expected

In some user feedback, someone said they expected to see a checkbox in markdown preview mode and `- [ ]` in markdown edit mode.

### Observed

A checkbox is shown in markdown edit mode and  `- [ ]` is shown in markdown preview mode.

### Reproduced

1. Go to any note.
1. Tap on the overflow menu (three dots).
1. Select the Markdown option.
1. Add a checkbox.
1. Compare how the checkbox looks in edit versus preview mode.

<img src="https://user-images.githubusercontent.com/1119271/97364801-2f0e5300-186a-11eb-98a9-27859d6258f1.png" width="270" alt="Screenshot_20201027-145446"> <img src="https://user-images.githubusercontent.com/1119271/97364793-2cabf900-186a-11eb-9cdb-4c496557bac4.png" width="270" alt="Screenshot_20201027-145454">

Device Make: Google
Device Model: Pixel 3
Android Version: 11
Simplenote Version: 2.11.1

I'm not sure whether or not this is a bug honestly, though I agree with the user that it seems opposite from what I expected—especially if you compare it to how other markdown is displayed in edit versus preview modes. If it's not a bug then closing this issue with an explanation would be helpful! Here is the original question which prompted me to create this issue—it was sent in an App Review on Sep 24, 2020, 08:06: 

> What's the point in edit mode to see checkboxes but markdown - [ ] in preview mode?!

* Device: Xiaomi Redmi 5 Plus
* Device language: English
* App version code: 112
* App version name: 2.9
* Android version (SDK): Android 8.1 (SDK 27)
* play-store-reviewId=gp%3AAOqpTOH8Ax_P4JOuMYFCMJ_7KoujcMBU1dOYa8p9eHiTdbRT8Kst6KeDa9PUJdshW61kElNOYmMWL0l4sg1mPLI&corpus=PUBLIC_REVIEWS

**Comment by theck13** [comment]
This is a known issue.  That is a limitation of the markdown parser we're using.  Since Simplenote is very often used on multiple platforms by users, we want to have as much parity as possible between our apps.  In the case of our markdown parser, we chose the same base library for Android and iOS for consistency between those platforms before the checklist feature was added to the apps.  Unfortunately, that means we have to make compromises, which limits our options in the markdown preview.

**Comment by SystemObject** [comment]
Excuse me. So it will be fixed? So far, this is the only reason why I switched to another program. Please fix it. Perhaps you can parse the text for the first time through a third-party parser that you don't have access to, to fix it. And the second time to parse the text with a parser written by you only for ``[ x ]`` where this bug will be fixed. Sorry for the confusion in my text, this is the first thing that came to mind. And sorry for the bad English.

**Comment by chromer030** [comment]
same here , on android 7.1.2 i have exactly this issue , and it's annoying. please fix it.

**Comment by codebykat** [comment]
This has previously been reported in #872, so I'm closing this as a duplicate.
