### ISSUE TITLE
Markdown syntax highlighting

### ISSUE THREAD

**Issue by dmych** [Automattic/simplenote-android#1206]
### What

Markdown syntax highlighting (as it already done for desktop version)

### Why

It's more comfortable to work with texts when you see fonts and headings.

**Comment by theck13** [comment]
I have added it to our feature requests.

**Comment by aichi-t** [comment]
@theck13 I was just wondering if this has been implemented? I'd love this feature to be available in the android app.

**Comment by theck13** [comment]
I don't think so.  I don't work on Simplenote anymore.  I'm not sure when or if the feature will be implemented.  The app hasn't been actively developed for ten months.
