### ISSUE TITLE
Cursor can be hidden below results bar

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-android#1219]
### Expected
The cursor should always be visible while editing a note.

### Observed
The cursor is sometimes below the search results bar.

### Reproduced
1. Search for a term with a match in a note
2. Tap to open the note
3. Tap on the bottom line of the note
4. Observe that the cursor is now underneath the "1 of 3" search results bar

<img width="324" alt="Screen Shot 2020-12-01 at 6 08 23 PM" src="https://user-images.githubusercontent.com/52152/100819119-62f80d80-3400-11eb-836b-9cb663a94700.png">

<img width="334" alt="Screen Shot 2020-12-01 at 6 08 28 PM" src="https://user-images.githubusercontent.com/52152/100819132-69868500-3400-11eb-80e9-56560dd4a554.png">

<img width="327" alt="Screen Shot 2020-12-01 at 6 06 32 PM" src="https://user-images.githubusercontent.com/52152/100819156-71dec000-3400-11eb-877e-e5be8d161052.png">

Device: Pixel 2, Android 10.0.0 (emulated via Android Studio)
Simplenote version: current `develop`

**Comment by theck13** [comment]
This is a consequence of the software keyboard being shown.  The bottom of the note where the cursor is located can still be scrolled into view while the search match bar is visible.  Once the text is changed, the search match bar is dismissed and the cursor is visible.
