### ISSUE TITLE
Have a similar view as Google Keep

### ISSUE THREAD

**Issue by Joe23232** [Automattic/simplenote-android#1245]
I find that Google Keep has a very intuative sticky notes. It allows different coloured notes, it looks like sticky notes etc.

![image](https://user-images.githubusercontent.com/34926497/102709174-02bc0380-42fc-11eb-992a-836f01c6a581.png)

It would be great if simplenote can offer a similar layout through settings. The only reason why I am not using Google Keep is due to privacy concerns.

**Comment by theck13** [comment]
I've added your suggestion to our feature requests.

In the future, use the template for creating issues or the issue will be closed without comment.
