### ISSUE TITLE
Does this support and use end-to-end encryption?

### ISSUE THREAD

**Issue by Joe23232** [Automattic/simplenote-android#1246]
Does this support and use end-to-end encryption?

**Comment by theck13** [comment]
You can find information on encryption during [storage](https://simplenote.com/help/#encryption) and [sync](https://simplenote.com/help/#sync-encryption) on the [SImplenote Help page](https://simplenote.com/help).

GitHub issues are for requesting features or reporting bugs.  If you have questions, contact us at support@simplenote.com for help.

In the future, use the template for creating issues or the issue will be closed without comment.
