### ISSUE TITLE
Allow Simplenote syncing with Nextcloud 

### ISSUE THREAD

**Issue by ralxxx** [Automattic/simplenote-android#1251]
### What
Allow the users to select from other options where his/her notes a stored/synced with. Ideally this could be Nextcloud - other alternatives could be Dropbox and similar services.  

### Why
Allowing to chose an alternative storage location, increases the users' self-determination in terms of his/her data.     

### How
see > Joplin

![Joplin](https://user-images.githubusercontent.com/36100882/103082582-b82bd700-45da-11eb-8ebe-f4a90cfd6a67.png)

**Comment by theck13** [comment]
I've added your suggestion to our feature requests.
