### ISSUE TITLE
[Question]  SimpleNote as paid service ?

### ISSUE THREAD

**Issue by chromer030** [Automattic/simplenote-android#1272]
In latest 2.15-rc-1 release , we see limitation on theme selecting and premium membership option , SimpleNote is not free anymore ?

**Comment by theck13** [comment]
Simplenote is completely free.  We are planning to add non-essential features like styles to the apps, which will be available with a monthly subscription.  That hasn't been enabled yet.  We have to finish adding the features and subscription flow on all platforms before it will be enabled.

As for Simplenote Android 2.15-rc1, I'm not sure what do mean by "limitation on theme selecting" in your comment.  The app themes (i.e. **_Light_**, **_Dark_**, **_Dark at night only_**, and **_System default_**) are a free feature and they will still be free once styles are enabled.  As you can see in the screenshot below, **_Theme_** and **_Style_** are two different options that will appear under the **_Appearance_** section in **_Settings_**.

<kbd><a href="https://user-images.githubusercontent.com/3827611/104230082-51941f00-540a-11eb-8587-7c2fd97ec04c.png"><img src="https://user-images.githubusercontent.com/3827611/104230082-51941f00-540a-11eb-8587-7c2fd97ec04c.png" width="300"></a></kbd>

**Comment by chromer030** [comment]
@theck13
Thank you very much for answering.
