### ISSUE TITLE
Sort order option not being saved

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-android#1293]
It was reported in 3684270-zen that the Sort order option on the Android app doesn't sort the notes according to their chosen setting (Alphabetically).

### Expected

I would expect the notes in the app will be sorted according to the settings I've chosen at the "Sort order" option.

### Observed

The notes weren't sorted according to my chosen setting at the "Sort order" option. When I go back to the Settings screen, the "Sort order" option reset to "Newest modified date".

### Reproduced

1. Tap the Navigation Drawer
2. Tap Settings
3. Tap Sort order
4. Tap any options
5. See that the chosen setting appear at the "Sort order" option
6. Tap the back arrow
7. See that the notes aren't sorted based on the chosen setting in Step 5
8. Go back to the Settings screen and see that the "Sort order" option is reset to "Newest modified date"

Video recording: https://d.pr/v/3rlSVM/U5Oo82GhWq

**Reported on**

Device Make: Sony  
Device Model: Xperia XZ Premium
Android Version: 9
Simplenote Version: 2.15 (130)

**Reproduced on**

Device Make: OPPO
Device Model: Reno 4
Android Version: 10.0.0
Simplenote Version: 2.16-rc-2(132)

**Comment by theck13** [comment]
This was fixed in https://github.com/Automattic/simplenote-android/pull/1284, which will be included in the Simplenote Android 2.17.0 release.
