### ISSUE TITLE
Change of note sort order not stored

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1294]
Thanks for release 2.15

### Expected
see below

### Observed
- Change of note sort order is not stored

### Reproduced
1. I have a tag list opened

2. I change the note sort order from "last changed" to "A-Z"

3. I get back and find an empty screen 
(for several seconds, this is not nice but not the main problem of this report)

4. I am not in the tag list but in the "All Notes" screen 
(this is not nice and rather the second problem of this report)

5.  the note sort order has not changed

__________________
Screenshots

2.a
![Screenshot_20210130-112139_Simplenote](https://user-images.githubusercontent.com/22197180/106355109-4be97500-62f6-11eb-946f-015178ee532b.jpg)

2.b
![Screenshot_20210130-112109_Simplenote](https://user-images.githubusercontent.com/22197180/106354975-a0d8bb80-62f5-11eb-8334-7eee43e1b61a.jpg)

3.
![Screenshot_20210130-112210_Simplenote](https://user-images.githubusercontent.com/22197180/106355027-edbc9200-62f5-11eb-98c1-ed5b31a3c164.jpg)

(4. no Image)

5.a
![Screenshot_20210130-112131_Simplenote](https://user-images.githubusercontent.com/22197180/106354984-ac2be700-62f5-11eb-8112-61af4d75039b.jpg)

5.b
![Screenshot_20210130-112139_Simplenote](https://user-images.githubusercontent.com/22197180/106355109-4be97500-62f6-11eb-946f-015178ee532b.jpg)

### Devices

Device: Samsung Galaxy XCover 4 (SM-G390F)  **and** Samsung Galaxy Tab A (9.7, LTE) SM-T555
Android Version:  9 and 7
Simplenote Version:  2.15

**Comment by theck13** [comment]
Thanks for reporting the issue! This was fixed in https://github.com/Automattic/simplenote-android/pull/1284, which will be included in the Simplenote Android 2.17.0 release.
