### ISSUE TITLE
Doesn`t dial and call telephone numer from note

### ISSUE THREAD

**Issue by LiwiuszPleandro** [Automattic/simplenote-android#1307]
In the note: it does not dial a number and does not call a telephone number in the format, for example: +48791874533 or 791874533. It highlights the number in blue, displays a blue telephone receiver at the top, but after pressing it, nothing happens. Does not redirect to the dialer. Back in the days on older versions of simplenote (several months) this feature worked great. In the last few versions, this doesn't work. It is very flustering. Please repair :).

Simplenote -> Settings -> Detect links [yes]
Device: Xiaomi note 5 Pro, MIUI 11 eu
System: Android 9
App version: Simplenote 2.15 (130) google play

**Comment by theck13** [comment]
Thanks for reporting the bug!  I created https://github.com/Automattic/simplenote-android/pull/1308 to fix the issue.

In the future, please use the template for creating issues or the issue will be closed without comment.

**Comment by LiwiuszPleandro** [comment]
OK, 
Thanks.  Now, detect telephone link and dial a number in version Simplenote-pr-1308-build-4851.apk works great!

**Comment by pachlava** [comment]
[testing] fix/feature verified on Samsung A31 | Android 10 | Simplenote 2.17-rc-1
