### ISSUE TITLE
Sync issue? 

### ISSUE THREAD

**Issue by erikdemarco** [Automattic/simplenote-android#1324]
Currently I use simple note on 1 Linux desktop, 1 android device. Everything works correctly. Never have any problem since use Simplennote. 

Today I buy a new android device (let's name this android2) and install Simplennote. But its weird. 

If I add/update notes from android1 or desktop1. Every notes synced correctly on all devices including on android2.

The problem is when I add/update note in android 2. The note is not getting pushed to other devices. I wait for a week. All notes added in android 2 will never be pushed to other devices. Why? 

### Expected
If note updated from any device, it will be pushed to all devices 

### Observed
No error notification at all. 

### Reproduced
-) Install Simplennote on Linux desktop, android (miui 11), android (miui12) 
-) try add/update note on each devices and see whether it getting pushed to other devices. 

Linux desktop 1:
Linuxmint

Android 1:
Device Make: Mi
Device Model: Mix 2s
Android Version: 10 QKQ1.190828.002 (Miui 11)
Simplenote Version: 2.15 (130)

Android 2:
Device Make: Mi
Device Model: Mix 3
Android Version: 10 QKQ1.190828.002 (Miui 12)
Simplenote Version: 2.15 (130)

Update:
I try uninstall Simplennote on both android 1 and android2. And do fresh install on both of them. Guess what? The android 1 and android 2 now can't add/update to any device. Now only Linux can push note update to all device. So weird. Now I lost ability of multidevice on Simplennote

**Comment by pachlava** [comment]
@erikdemarco Thank you for this report. Before we go deeper into analysing what happens, could you please try these things:

1. Install the latest beta APK from here: https://github.com/Automattic/simplenote-android/releases/tag/2.17-rc-1. There was a number of fixes in the area which might affect what you experience.

2. If this does not help, could you please use the [Web-version](https://app.simplenote.com/) on both of your Android devices, and check if the sync issues are present there too. This will help us to narrow down and exclude the case of connectivity issue.

Please let us know if this help.

**Comment by dmsnell** [comment]
@erikdemarco I'm closing this ticket so we can help you on a 1:1 basis - please contact support@simplenote.com where we can diagnose the specifics with your devices and issues. there is an app log you can collect with extra diagnosis information that may be useful in understanding why changes aren't syncing.

**Comment by erikdemarco** [comment]
@pachlava I have tried it. It still can't update whatever I add in android app. Now I can only use web version on all my Android device . Because it works perfectly. 
The only complain is. Web version can't bulk delete, Can't select text, whn i enter text and press space, the word become double
