### ISSUE TITLE
[Search] Scroll position of a note with matching keyword in not persistent

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-android#1338]
This comes from Google Play [review](https://link.reviewbot.io/review/hWBC6R_QD):

> The SEARCH function was the main advantage of this app.When we searched for a word, the result was positioned on the 1st occurrence of the word and proposed the other occurrences. No other competing note app offers this. This was decisive in my choice of app. Since the last update (Feb 2021), if there is only 1 occurrence, the cursor is placed at the end of the note.

After some testing it definitely looks like there is an inconsistency in this place. However, the scroll position can be both correct and 'bottom of the note' for both cases of multiple or single match.

### Expected
If a note contains a search match, tapping a note should show the match. Or, at least, be opened with a consistent scroll position.

### Observed
The scroll position can be both correct and 'bottom of the note' for both cases of multiple or single match.

### Reproduced
1. Have a note that contains some unique keyword (only once, only in one note)
2. Start search against this keyword
3. Tap the note ~> you might firstly see the keyword shown on screen
4. Go back to note list and tap the note again ~> you might see the note scrolled to bottom.

https://user-images.githubusercontent.com/73365754/110334627-a67b9c80-802b-11eb-9ee6-c25d524e220f.mp4

Device Make: Samsung
Device Model: A31
Android Version: 10
Simplenote Version: 2.17-rc-1

**Comment by pachlava** [comment]
Similar report in closed #1375:

> Phrase search does not work properly. It worked fine in previous versions.
> 
> Expected:
> After searching for a phrase, it should show a list of notes in which it was found and then go to the specific field found
> 
> Observed:
> It does not go to a specific searched field in the note
> 
> Reproduced:
> 
> 1. Go to: magnifier, type ex. (number phone) +4887345643 and click search
> 2. Correctly finds a notes in which the phrase appears +4887345643
> 3. Error: Shows a random note in which the searched phrase is missing at all. Does not go to the searched field
>
> - System Make: Phone Xiaomi
> - System Model: Note 5
> - OS: Android 9 . Snapdragon 636
> - OS version: MIUI 11.2 eu
> - Simplenote app version (google play): 2.18 (138)
> 
> In previous versions simplenoteapp worked fine. There has not been a newer android version on my phone for two years. I am updating every version of simplenoteapp.
> **The error occurs if the notes are large, one note is approx. 40-60,000 characters. Searches correctly in short notes.**

**Comment by LiwiuszPleandro** [comment]
Where can I download earlier versions where the search works properly, ex: Simplenote-pr-1308-build-4851.apk ?

**Comment by pachlava** [comment]
Generally, you can download the official released versions from [here](https://github.com/Automattic/simplenote-android/releases).

If you need an in-between version, like the one you mention: it depends on the time when the apk was automatically built by CI for a pull request. For the case of #1308, my assumption why it's not downloadable anymore is because it was quite a while ago, and it got automatically removed from the server.

I would suggest you to try using the beta which came right after Feb 3 which is [2.16](https://github.com/Automattic/simplenote-android/releases/tag/2.16), released on Feb 8. Let us know if this helps.

**Comment by reginabally** [comment]
Another report in 4003115-zd-woothemes:

> When there is only one 'hit' within a note, the part of the note that gets displayed on the screen does not contain the hit. So I must hunt around the note to find the hit.
If I had to make a bet (because this is a common source of such bugs), I would guess that the bug doesn't appear when minimum font size is used as is typical of young developers.

**Comment by rezzap** [comment]
Another report of this in 4205301-zd-woothemes

They also mention this:

> But additionally I'm seeing that instead of remembering where I was in a
note, going back in gives me an apparently random jump to a different
location in the note.

Moto g7 Power, Android 10 (always latest update), and always keep Simplenote updated to current version
