### ISSUE TITLE
Email verification screen appears for some verified accounts

### ISSUE THREAD

**Issue by hichamboushaba** [Automattic/simplenote-android#1343]
While working on the new signup flow, we noticed that the email verification screen appears in some cases where the account should be already verified:
1. Accounts using the new signup flow.
2. WordPress.com login.
3. Login after install.

<img width=400 src="https://user-images.githubusercontent.com/9729923/110639585-8e855380-81b8-11eb-9c2a-815be115de1b.png" />

Steps to reproduce:
1. Click on signup.
2. Enter an email.
3. Check the email inbox to continue signup.
4. Complete the account creation.
5. Notice the email verification screen.
The issue occurs randomly, so you may need to repeat the above steps multiple times.

**Comment by pachlava** [comment]
Reproduced with consistency (three times for three new users). In all cases the email was displayed correctly in the `Review your account` dialog. The dialog was never shown again after dismissal.

Device Make: Samsung
Device Model: A31
Android Version: 10
Simplenote Version: 2.18-rc-1
