### ISSUE TITLE
Sorting Notes on Android not working

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/simplenote-android#1351]
A user brought to our attention the sorting option on Android is not working. I have tested on my Pixel 2 and was able to replicate the issue. 

### Expected

Click on the hamburger menu
Click on Settings
Click on Sort order
Choose the sorting option. In my case I selected alphabetically from A to Z

![photo_2021-03-23 14 59 25](https://user-images.githubusercontent.com/30724184/112203220-ae6d3c00-8be8-11eb-823a-5c21bed9ac09.jpeg)

I would expect the notes to be sorted based on my selection from the Sort Order menu

### Observed

Nothing happens, the notes are kept sorted by date, plus when I go back to the settings menu it did not save my selection

![photo_2021-03-23 14 59 22](https://user-images.githubusercontent.com/30724184/112204188-c5605e00-8be9-11eb-8aa6-fa7a5cc9bbb2.jpeg)

![photo_2021-03-23 14 59 18](https://user-images.githubusercontent.com/30724184/112204261-d6a96a80-8be9-11eb-8ee7-7766f6f29a10.jpeg)

### Reproduced

Click on the hamburger menu
Click on Settings
Click on Sort order
Choose the sorting option. In my case I selected alphabetically from A to Z

Device Make: Google
Device Model: Pixel 2 (mine) and the user has a OnePlus ONEPLUS A5000 (OnePlus5)
Android Version: 11.00 (mine) and user's is 10.0.0
Simplenote Version: 2.15.0 for both
3841481-zen

**Comment by pachlava** [comment]
Thank you for the report @rossanafmenezes ! Sorting was not working in Android for some time, but was fixed since version 2.16. The latest version is [2.18-rc-1](https://github.com/Automattic/simplenote-android/releases/tag/2.18-rc-1). The update should help the user.

I'm closing the issue, since it's reported for version 2.15.
