### ISSUE TITLE
Email verification: Address showing up as null, account may not exist?

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-android#1353]
A user reported (3868456-zen) that they are prompted to verify their email when opening the app, but their email is shown as the word "Null".

They also say they don't recall signing up for the app / setting a password, and I don't see an account for the email address they contacted us from. They say they've been using the app for many years and have never had to sign in.

I've asked them for more information in the ticket but I wonder if it's possible we still have some folks using the account without having created an account - I found https://github.com/Automattic/simplenote-android/pull/432 in the history but can't tell if we still allow account-less usage for those very old accounts.

**Comment by pachlava** [comment]
@codebykat please also see #1353 - `null` email address is mentioned there as well

**Comment by codebykat** [comment]
@pachlava This is 1353 - what did you intend to link? I searched other issues for "null" and I'm not seeing anything.

**Comment by pachlava** [comment]
@codebykat whoops 🤦 , I meant #1343, sorry

**Comment by codebykat** [comment]
The user got back to us to confirm that they do not have an account at all. 😱

**Comment by rossanafmenezes** [comment]
Got another case here 3938469-zen just FYI

User mentioned it's an old account that did not require login. So probably from back when you could use SN on Android without an account.
