### ISSUE TITLE
Poor alignment of text on sort bar for Russian language

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-android#1358]
It was reported in 3887370-zd-woothemes that the Russian text on the sort bar looks off. 

![photo_2021-04-09_22-08-25](https://user-images.githubusercontent.com/40906847/114349016-ec330400-9b99-11eb-900e-12d439599339.jpg)

Also a +1 to [this request](https://github.com/Automattic/simplenote-android/issues/1342) since the user mentioned having the sort order in the Settings screen is good enough.

Reported on Honor 20 Pro, Magic UI 4.0.0, app version 2.18.

**Comment by reginabally** [comment]
Another report here: 4056102-zd-woothemes

Samsung tab s7 Android 10

**Comment by danilo04** [comment]
Fixed in #1438.
