### ISSUE TITLE
Request of Finding Duplicate lines

### ISSUE THREAD

**Issue by 0x00Finch** [Automattic/simplenote-android#1407]
### What
I would like a feature that checks duplicate lines in a note page

### Why
let's say that I use simple note as a clipboard syncing app, when there is tons of content that I can't keep track of duplication in a note page, especially dealing with urls in clipboard

### How
there may be a button or switch that can turn this function on and off.
I would like a function that checks for duplicate urls in a single note page.

There could be multiple ways to deal with the duplications found
- we could highlight them and it is up to the user to decide which to stay
- or we could auto delete duplicated urls

**Comment by danilo04** [comment]
Hi there 👋 ,

I've added your idea to our list of feature requests, so you may see it in a future release. Features are considered for every release so we appreciate you taking the same to share some feedback.
