### ISSUE TITLE
App Switches to Light Mode When Editing in Landscape Orientation

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-android#1410]
### Expected
When dark mode is enabled, rotating to landscape orientation while editing should retain dark mode.

### Observed
Instead, the editor switches to light mode.

### Reproduced
1. Enable dark mode in Simplenote's app settings.
2. Open a note and start editing.
3. Rotate to landscape orientation.

https://user-images.githubusercontent.com/42454301/124658653-05cea980-de72-11eb-8f8b-0a9fec888ba7.mp4

Device Make: Google
Device Model: Pixel 3
Android Version: 11
Simplenote Version: 2.18

**Comment by danilo04** [comment]
Hi @mdrockwell. 

I think that is the full-screen mode of the keyboard takes over our text field. I see this same behavior in apps such as `Whatsapp`. However, in `Samsung Notes` they do handle the full-screen mode themselves (see image below):

| `Whatsapp`      | `Samsung Notes` |
| ----------- | ----------- |
|   ![Screenshot_20210818-125201_WhatsApp](https://user-images.githubusercontent.com/195721/129948701-80d400f2-2001-4774-b140-429b15063871.jpg)     | ![Screenshot_20210818-125248_Samsung Notes](https://user-images.githubusercontent.com/195721/129948657-2880f7dc-6547-49b1-990b-98493b1a9dee.jpg)  |

So we need to modify the default full-screen mode of the keyboard to handle this case.

**Comment by danilo04** [comment]
One simple solution is to disable full-screen mode of the keyboard. It would look like this:

![Screenshot_20210818-151707_Simplenote](https://user-images.githubusercontent.com/195721/129966340-c4220389-0467-4887-8644-30ec85847720.jpg)

This solve the issue but reduces the space to type. What do you about this change in design @SylvesterWilmott?
