### ISSUE TITLE
Possibility to select notes in Trash

### ISSUE THREAD

**Issue by Marco-Sulla** [Automattic/simplenote-android#1421]
In the normal notes, you can select them and you can select multiple of them. In trash, you can't. Can you add this possibility also for the trash, so one can restore or permanently delete multiple notes?

**Comment by danilo04** [comment]
Hi there 👋 ,

I've added your idea to our list of feature requests, so you may see it in a future release. Features are considered for every release so we appreciate you taking the same to share some feedback.
