### ISSUE TITLE
Checkboxes not being interactable in preview mode when markdown is enabled

### ISSUE THREAD

**Issue by exinr** [Automattic/simplenote-android#1422]
### Expected
Expected Behavior: Markdown preview mode renders a tappable checkbox similar to the one in the Edit view.

### Observed
Observed Behavior: Markdown preview mode shows "[ ]" in place of unchecked checkboxes and "[x]" in place of checked checkboxes. These bracket things aren't interactable so I can't change between them by tapping.

### Reproduced
To Reproduce:
1. Create New Note (or open existing note)
2. Tap on the Checklist Icon in the top right of the edit menu to create a new checkbox
3. Tap on Preview to enter preview mode
4. The observed behavior is shown

![image](https://user-images.githubusercontent.com/62219187/126727628-b6d641bd-4544-4e2b-b1c7-e9e6160cbe95.png)
![image](https://user-images.githubusercontent.com/62219187/126727635-bc35b1f9-7a8a-4d13-8229-5eaeb5de9e36.png)

I don't know if this is only on my device (I only have one android device at my disposal), but:
Device Make: Samsung
Device Model: S21 Ultra
Android Version: OneUI 3.1 (Android 11)
Simplenote Version: 2.18

If this doesn't count as a bug because its more of an aesthetic + functional oddity then sorry for marking this incorrectly.

**Comment by danilo04** [comment]
This has previously been reported in #872, so I'm closing this as a duplicate. 

Thanks for the report!
