### ISSUE TITLE
Improvement to error msg shown when trying to delete an account with no network

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-android#1464]
### What
When there's no network, and the user tries to delete the account, this will be shown:

<img width="334" alt="Screenshot 2021-08-31 at 18 48 19" src="https://user-images.githubusercontent.com/73365754/131534616-d3fa11cb-00ff-4e12-b99f-8124ea34b267.png">

There's a much more descriptive message that is shown during login, which can be reused for account deletion:

<img width="341" alt="Screenshot 2021-08-31 at 18 48 08" src="https://user-images.githubusercontent.com/73365754/131534772-297cb0c0-5757-4e9a-9e76-1705d8b3388a.png">

### Why
Users will instantly know the reason why account can't be deleted.

**Comment by danilo04** [comment]
Tagging @SylvesterWilmott to see whether we can use this message or something else.

**Comment by SylvesterWilmott** [comment]
This message looks good to me! Thanks, both.
