### ISSUE TITLE
Internal link does not open the corresponding note

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1528]
### Expected
I create an internal Link.
I open another note and paste it.
I leave the note and open it again (later).
I press on the Link.
The original note opens.

### Observed
I press on the Link.
Nothing happens.

### Reproduced
see above
Device Model: Samsung Galaxy A51
Android Version: 11
Simplenote Version: 2.23.

**Comment by gubrist** [comment]
How can I add the type label [Type] Enhancement o this issue?

How can I add a feature label to this issue. e.g. 'Stats'?

**Comment by gubrist** [comment]
How can I add the type label [Type] Enhancement o this issue?

How can I add a feature label to this issue. e.g. 'Stats'?

**Comment by gubrist** [comment]
The electron version has evolved, meanwhile:

Entering a second word, Simplenote-elelctron suggests to search in tags beginning with that expression

**Comment by dougaitken** [comment]
Hi @gubrist 

For the main Issue here about the internal notes not working, can you confirm that you are changing the note to Markdown Preview mode and tapping on the hyperlinked text? The plan unformatted Markdown format won't work. 

This won't work `[Welcome to Simplenote for iOS!](simplenote://note/welcomeNote-iOS)` - you need to view the note in Preview mode.

For your last comment, can you elaborate a bit more about that, please?

**Comment by gubrist** [comment]
Thanks, Doug

I can confirm that changing the note to Markdown Preview mode and tapping on the hyperlinked text works.
