### ISSUE TITLE
Cannot open links in notes

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-android#1551]
After the update to v2.24, it's no longer possible to open links appearing in notes in the mobile browser. Instead, only an error appears.

### Expected
For the URL to open in my mobile browser/see the prompt asking which browser to use

### Observed
The app shows a `No Browser Detected` error, and doesn't open the link.

![Cursor_and_Jose_Negron_on_Twitter____simplenoteapp_I_updated_to_the_latest_2_24_update_for_the_Android_login_fix_but_now_clicking_on_a_click_in_any_notes_won_t_open_the_browser__This_a_Markdown_formatted_note_and_using_Brave_browser__Worked](https://user-images.githubusercontent.com/11873759/179153861-45509b0d-2abe-49bd-8623-3af3f69a8ad7.png)

### Reproduced
* Open a note containing a link. It can be markdown-formatted or a naked URL
* Tap the link, and tap the icon to open in a browser

I was able to replicate on the following:
Device Make: Xiaomi
Device Model: Redmi Note 11 Pro
Android Version: 11
Simplenote Version: 2.24

Reported [via Twitter](https://twitter.com/josenjt/status/1547804370934214661)

**Comment by maxime-pasquier** [comment]
On a mail reply of the support :

> ...
> 
> Please be aware we’ve identified another issue of not being able to open/click links in notes.
> If you’re seeing this issue as well, rest assured that it’s already on our radar.
> 
> ...
> 
> E. Gerard
> Happiness Engineer

**Comment by erricgunawan** [comment]
Adding report from 5381518-zen (translated):

> I always use it.
After today's update, the Android Evening App now displays an error message saying that the browser was not detected when trying to jump to the link destination.
The browser application (Chrome) can be used without any problem.
I would appreciate it if you could investigate once.

**Comment by KokkieH** [comment]
Looks like the merge didn't auto-close this. 

Confirmed links are opening normally again in v2.24.1, so closing this issue.
