### ISSUE TITLE
Synchronization upload halted 

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1575]
**Observed**

New or changed notes on my Android Galaxy Phone are not synched with the Simplenote Online Database.

**Reproduced**

Samsung Galaxy A32:

I have changed a note yesterday (25.11.2022),
it is not synchonrized are not synched with the Simplenote Online Database.

I created a note today (26.11.2022),
it is not synchonrized are not synched with the Simplenote Online Database.

I have tried various WLAN connections
I have tried mobile conncecation only.
I have tried new start of Simplenote.
I have tried new start of Samsung Galaxy A32.

**Software**

Android Version: 12
Simplenote Version: 2.24.1 (150)

**Comment by gubrist** [comment]
It happens again (for days).

**Comment by gubrist** [comment]
Anybody out there?

**Comment by roundhill** [comment]
[Support thread](https://forums.simplenote.com/forums/topic/synchronization-upload-halted-1575/#post-2182)
