### ISSUE TITLE
Checkboxes disappearing in notes for Samsung Galaxy users on upgrade to OneUI 5/ Android 13

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-android#1582]
### Expected
Checkboxes should remain as they are unless a user deletes them

### Observed
Checkboxes disappear almost immediately after being added in a note, or after opening a existing note that contains them.

### Reproduced

We haven't reproduced this, but the users who experience it, experience it every time. 

https://user-images.githubusercontent.com/7907292/210369822-09f8bcdf-092d-4c85-a10d-978c20da2f51.mp4

### Info

Every user report is for those on Samsung with the most recent OS update, Android version: Android 13 (SDK 33 or OneUI 5

Device Make: Samsung
Device Model: Samsung Galaxy S20 5G
Android Version: Android version: Android 13 (SDK 33
Simplenote Version: 2.25

5778885-zen
5794049-zen
5805437-zen
5812363-zen

Google Play App Review ID 7c2f5114-242c-480b-a660-582de08987bc

**Comment by planarvoid** [comment]
There seems to be a lot of issues with the new OneUI 5 and Android 13 updates on Samsung devices. One thing that might help are the following steps: 

1. Hold down the Volume Up and Power button at the same time > release when you see the Samsung logo appear. This will load a special screen with options. Be very careful in this screen!
2. Use the “Volume Down” button to move down the list of options until the “Wipe cache partition” is highlighted. Tap the power button to select it.
3. Use the “Volume Down” button again to highlight “Yes” in the confirmation screen – tap power button to select it. When the process is finished, you’ll be returned to the main screen listing all the advanced options from step 2.
4. Use the “Volume Down” button again to scroll to highlight the last option in the list: “Repair Apps”. Tap the power button to select it. A new screen will show the progress of repairing apps on the device. Once completed, the device will reboot.
5. Test to see if you can add the checkboxes.

**Comment by azollafox** [comment]
Another report https://woothemes.zendesk.com/agent/tickets/5843624
Samsung Android phone
Samsung software: G990USQS4DVL1
Simplenote 2.25

**Comment by reginabally** [comment]
The user in 5896526-zd-woothemes said [these steps](https://github.com/Automattic/simplenote-android/issues/1582#issuecomment-1369904306) didn't help:

> This has not worked for my Samsung S21 it's frustrating cause the check boxes are the main way I use. Now I cannot even add new boxes

**Comment by adamjohndaly** [comment]
> When I access my notes on the phone app, it deletes my check boxes. It then syncs with all device and the check boxes are gone. Any Ideas of what I can do to make this stop?
> 
> Thank you in advance for any help that you can provide!
> What device you use Simplenote on Galaxy S22
> What operating systems and versions One UI Version 5.0 Android Version 13
> The Simplenote versions on each 1.15.0

5941310

**Comment by danilo04** [comment]
This issue and #1580 are related to updates in `One UI Version 5.0 Android Version 13` for Samsung devices. We are implementing some changes to prevent the Samsung keyboard from making these updates on its own.
