### ISSUE TITLE
Text duplicating after updating the app to 2.26

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-android#1590]
There is more than one report of text duplicating after updating the app to version 2.26 in this forum post: https://forums.simplenote.com/forums/topic/app-repeats-numbers-when-typing-letters-or-numbers-in-certain-order/

### Expected

Text entered into the app shouldn't be duplicated.

### Observed

Text duplicated.

Example: typing 12 on keyboard gives 112, typing 1234kr gives 12341234kr

### Video recording

Check this YouTube video: https://www.youtube.com/shorts/CB9l-cynpPs

Device Make: Samsung
Device Model: Galaxy A72
Android Version: 13
Simplenote Version: 2.26

**Comment by danilo04** [comment]
I was able to reproduce the issue and found a partial solution. I am testing it to verify whether it works for all edge cases in Simplenote.

**Comment by danilo04** [comment]
The fix will be released in `2.27` cc @reginabally.

**Comment by reginabally** [comment]
Thank you so much for the quick fix, @danilo04!

**Comment by forteller** [comment]
I have this issue now. Random single letters gets duplicated in the Linux version of the app. Not on Android. 

Simplenote 2.21.0
Nobara Linux 41
Gnome 47
