### ISSUE TITLE
Note list: no divider between notes

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-android#1602]
On other platforms, we show a dividing line between notes on the note list. Android doesn't seem to do that. We've had [a request to have alternating colors](https://forums.simplenote.com/forums/topic/note-opening-mode-and-more/?view=all) for notes in the list, but I'd say likely better to follow what other platforms are doing. 

### Expected

Some way to quickly see where the next note begins

### Observed

No dividing option between notes in the note list

**Comment by roundhill** [comment]
I don't think list dividers really match with the Android design guidelines, so I think it was a conscious choice. Other "list" Android apps like Gmail do not have dividers.

Closing but we can reopen if we want to match the design up across platforms strictly.
