### ISSUE TITLE
SSL Cert Error on Older Android Devices

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#1684]
It appears Android 6 and 7 devices are no longer able to connect, due to an issue with how it handles certificate chains. 

See how Pocket Casts resolved this here: https://github.com/Automattic/pocket-casts-android/pull/2717

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by notandyvee** [comment]
https://github.com/Simperium/simperium-android/pull/250

https://github.com/Automattic/simplenote-android/pull/1685
