### ISSUE TITLE
Identify published and shared notes

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#174]
While we don't support publishing notes in the UI, we can still indicate that a note is published similar to the web.

![screen shot 2014-03-12 at 9 36 13 am](https://f.cloud.github.com/assets/19795/2399948/79c75bb6-aa04-11e3-8f29-57b529c17e52.png)

**Comment by bummytime** [comment]
Ref: https://github.com/Automattic/simplenote-electron/issues/227
Ref: https://github.com/Automattic/simplenote-macos/issues/4
Ref: https://github.com/Automattic/simplenote-ios/issues/312

**Comment by theck13** [comment]
This was added in https://github.com/Automattic/simplenote-android/pull/791.
