### ISSUE TITLE
"New Note..." note item shown in Notes List after pinning a note

### ISSUE THREAD

**Issue by mjangda** [Automattic/simplenote-android#181]
- Edit an existing (unpinned) note
- Pin it from the Edit Note view
- Back button to go back to Notes List
- The note will disappear from the list and will see a "New Note..." entry at the bottom of the list for a few seconds, which then disappears and note reappears with the Pinned icon.

**Comment by theck13** [comment]
I can't reproduce this.  Feel free to reopen it if you can.
