### ISSUE TITLE
Support partial match in any part of string for search

### ISSUE THREAD

**Issue by fredrocious** [Automattic/simplenote-android#227]
Current search matches words that start with search term e.g. "sear" finds "search" but, "earch" does not.

**Comment by cecoates** [comment]
https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3173237

Another report from a user. Can confirm on my Android 7.1.1 Nexus 5x Simplenote version 1.5.5. Web app and iOS app seem to handle those searches well, however.

**Comment by rachelsquirrel** [comment]
Also reported in 671724-zen.

**Comment by roundhill** [comment]
Due to the nature of FullTextSearch, we won't be fixing this for a while. Closing!
