### ISSUE TITLE
Home screen widget

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#232]
A widget that lists notes on the home screen. Should have a button to create a new note.

**Comment by d73** [comment]
Just dropped in to say, hey I would love this too cos that would be 💣

**Comment by ericbrandwein** [comment]
Google keep already has exactly this, I really would love to have my to-do list as a widget

**Comment by potahto** [comment]
+1 to having a fast way on the homescreen to view specific notes or open the app on a specific note -- either as an App Widget or a Pinned Shortcut.

**Comment by gbdc** [comment]
+1 I can really benefit from this

**Comment by robertoissc** [comment]
I'm thinking about 2 widgets: a `PinnedNoteWidget` which will be a shortcut to a specific note and a `NoteListWidget` that shows the list of notes with create new option. What do you think?

I would like to start working on the PinnedNoteWidget implementation. :)

**Comment by gbdc** [comment]
Pinned note would be perfect for use case of managing todos

**Comment by robertoissc** [comment]
Currently working on PinnedNoteWidget :).
I'll post updates with my progress to get feedback.

**Comment by MCherrey** [comment]
@robertoissc I am interested in helping with this feature. Just curious if you started working on the `NoteListWidget`. If not, I can take a shot at it.

**Comment by robertoissc** [comment]
Hey @MCherrey! Please feel free to start with the list widget. :)

**Comment by livejamie** [comment]
Is there any update to this?

**Comment by potahto** [comment]
v2.0 on Android has a pinned note widget that opens SN to a specific note. Looks nice!

**Comment by livejamie** [comment]
Yes the Pinned Note Widget is working, I was looking for an update on NoteListWidget that @MCherrey and @robertoissc mentioned. :)

**Comment by livejamie** [comment]
I just wanted to give this a friendly bump as not having the NoteListWidget is the only thing keeping me from adopting Simplenote fulltime. I'd even be willing to donate to one of @MCherrey or @robertoissc 's favorite charities or donate directly to them if it would help.

This feature request has been open for 6 years now. :)

Thanks so much!

**Comment by MCherrey** [comment]
Hello,

I am sorry for offering to help and then not getting around to it (I had a busy school semester). I'll start working on it.
