### ISSUE TITLE
Ask if user wants to keep notes locally if they sign out

### ISSUE THREAD

**Issue by fredrocious** [Automattic/simplenote-android#234]
Since Simplenote for Android allows users to use the app with no account, if they sign up for an account, and then decide they don't want an acount any more, there isn't a way to get those same notes back into the offline only state.
Suggestion: when signing out on android, prompt user if they want to keep those notes locally

**Comment by theck13** [comment]
Since Simplenote for Android no longer allows users to use the app without an account, I'm closing this issue.
