### ISSUE TITLE
Allow duplicating notes

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#236]
From a review in the Play Store

> Dissapointed Got this app as it was compatible with my older 4.0.3 tablet that won't support OneNote, and because it offers offline note access - which Evernote no longer supports for free. So this app has a nice niche market in that it has better compatibility than OneNote and supports a critical feature for free which Evernote does not. However, Simplenote does not support note templates, or COPYING a note, and therefore is useless to me. I can understand not supporting templates, but copying... that is so basic I can't comprehend why that don't have that feature yet. Very disappointing.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
