### ISSUE TITLE
Pin code feature not working correctly

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#237]
From the play store:

> There is a security issue. When I leave the app to do something else, then click back onto the app the pin number screen doesnt come up. Which it should, please fix this. Other than that the app is great.

**Comment by daniloercoli** [comment]
This should be fixed with the version 1.5.1  of PasscodeLock.
See https://github.com/wordpress-mobile/PasscodeLock-Android/pull/51

cc @roundhill

**Comment by jessestu** [comment]
Just to check, is there a reason that this ticket remains open? @beaucollins

**Comment by theck13** [comment]
I cannot reproduce that behavior.  It appears to be fixed in https://github.com/Automattic/simplenote-android/pull/408.  Feel free to reopen this issue if you can. still reproduce this
