### ISSUE TITLE
Note count in tag editor incorrect

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#239]
From the play store

> bug in tag editor in the screen where you edit all your tags, many tags which have actual notes linked to them are mistakenly diaplayed as "0 notes". i nearly deleted some useful tags because of this bug. this is important please fix.

**Comment by gracie** [comment]
Also reported in #3241529-t

>  tags in the EDIT TAG screen: 
> When I go to edit tags, tags that start with certain symbols like "@", "^", and "~" don't show a note count. An example here would be @StreamsDesert (which I recently started to record quotes from a book called "Streams in the Desert"). If you look at the attachment that ends with 12-21-07, you'll see that SimpleNote doesn't show that I have any notes with those tags. But this isn't true.

**Comment by gubrist** [comment]
Simplenote Version 1.7.0 on Android 8.1.0

![20190531_172219](https://user-images.githubusercontent.com/22197180/58725545-b2124c00-83df-11e9-902e-2bc8d9c6364d.jpg)
![20190531_180452](https://user-images.githubusercontent.com/22197180/58725599-d4a46500-83df-11e9-81f2-9a0b31db437d.jpg)
