### ISSUE TITLE
Syncing issues with simultaneous edits

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-android#243]
[Google Play Store review](https://play.google.com/store/apps/details?id=com.automattic.simplenote&reviewId=Z3A6QU9xcFRPRnY4NkRpUWY1VjR6clF6YmNHMm9qaHF5NW9wbUMta3c0NkpPTXpiaVlXOWVEcERHdjhkaDI2Y0wtVkpubUJmUnYwVko1SG5qaGtJdWhuczd3):

> Great app, but sync issues. When I edit the same note on Android and web, sometimes the sync is not up to date and I wind up editing an old version. When sync later occurs, I appear to lose text, and I need to go to the web and select an older note version to get my text back. To avoid having to do this, I try to make sure I am editing the latest version when I switch between platforms - based on content alone, as there is no sync timestamp or force sync button.

**Comment by roundhill** [comment]
Fixed via #554 

props @whhone
