### ISSUE TITLE
Can't sign in with '!' in password

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#275]
A user claimed that having a `!` character in her password prevented her from signing in to the app.

**Comment by Robertght** [comment]
@roundhill I've managed to replicate this on this ticket 1328058-zen.

I used a long password (41 characters) + ! at the end of it. and I couldn't log into the app anymore. Worked with the 40 characters without ! though.

**Comment by roundhill** [comment]
Thanks @Robertght we'll take a look.

**Comment by theck13** [comment]
I tested multiple password combinations with `!` up to 64 characters, but I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
