### ISSUE TITLE
Alphabetise tag list

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#283]
It would be great to be able to sort the list of tags alphabetically

**Comment by valsor** [comment]
It's unbelievable this basic feature is yet open. Simplenote becomes unusable with tag count more then several dozens

**Comment by MorgothSauron** [comment]
+1

Sorting tags would improve usability.

**Comment by roundhill** [comment]
Refs: https://github.com/Automattic/Simplenote-United/issues/13

**Comment by theck13** [comment]
This was added in https://github.com/Automattic/simplenote-android/pull/599.
