### ISSUE TITLE
Wrap title in list of notes

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#294]
When viewing the list of notes in iOS the note title wraps to the next line so you can see the entire title when you scan through the list. It doesn't do this on Android and only the first line is visible.

https://simplenote.desk.com/agent/case/63393

**Comment by theck13** [comment]
Only the macOS and iOS apps wrap the title to a second line.  Android, [web (old)](https://app.simplenote.com), and [web (new)](https://app.simplenote.com/new) use one line for the title with an ellipsis if the title is longer than one line.
