### ISSUE TITLE
Android app works on Blackberry ... almost

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#295]
A user says the Android app works perfectly on the Blackberry except for one flaw which they describe as follows:

"The BB problems happen when editing a text. When I use the enter key to create a few empty lines, the screen will show one empty line, and doesn't then show the others. If I exit the text and re-edit, the empty lines, that I created, are there, and I can work normally.Other than this flaw, the application works extremely well on the BB10 platform."

I haven't made any promises and have already explained that we don't support the Blackberry but thought I'd pass this on anyway.

**Comment by CorentinLemaitre** [comment]
+1 
I use this application in blackberry and i have the same problems. 
Some new line (usualy when you create only a line it works) can not be seen. When you write inside it write over the text in the bottom line. 
I have to go out of the note to get good note.
I have seen also that when the bottom lines don't go down when i push enter i can note select them correctly, i have to select the logical position of the line and not on the visible position. When i delete one leter on a logical line (invisble) the line get done and appear in the correct position.
I hope it will help to solve the problem...
