### ISSUE TITLE
Use close icon instead of back arrow

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-android#315]
In these 2 scenarios, an X icon would be more appropriate than a back arrow.

![screen shot 2015-10-02 at 2 27 48 pm](https://cloud.githubusercontent.com/assets/618551/10255871/d5de809a-6912-11e5-9aa8-004c7d18d597.png)

**Comment by theck13** [comment]
Using the back arrow for search and action mode (i.e. selecting multiple characters of text or multiple items in a list) is standard across apps I tested.  Let me know if you have examples when `x` is used instead and feel free to reopen this issue in that case.  One thing to note is that the `x` is used to clear the search field once text has been entered.  Two `x` icons in the app bar may be odd in that situation.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/58066394-6c839280-7b46-11e9-8632-ed5175b62385.gif" width="360">
