### ISSUE TITLE
Share menu ordering

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-android#316]
Can we alter the ordering of the share menu? It's strange that the first item is Simplenote.

We could prioritize WordPress, then maybe email clients?

![screenshot_2015-10-02-14-37-57](https://cloud.githubusercontent.com/assets/618551/10257301/20a3807c-691c-11e5-8c3b-0e13651e4cc2.png)

**Comment by theck13** [comment]
I don't see this "Share Note" interface in the app. I think the share feature has been updated since this issue was created. If this behavior still exists as described, feel free to reopen this issue and let me know how I can reproduce the "Share Note" usage.
