### ISSUE TITLE
Add more info to pop over

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-android#317]
Redesigning the info pop over to be more like this would allow us to add more features like history.

![screenshot_2015-10-02-15-01-35](https://cloud.githubusercontent.com/assets/618551/10259057/a2f030ea-6929-11e5-884d-b6f85b3675f6.png)

**Comment by theck13** [comment]
Since it appears the info and history features have been updated since this issue was created, I'll close this issue.  See the screenshots below for illustration.

![bottom_sheets](https://user-images.githubusercontent.com/3827611/58066616-4dd1cb80-7b47-11e9-8778-2e070e427460.png)
