### ISSUE TITLE
Lag on long notes with Japanese characters Android v.4.2

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#319]
I'm running version 4.4 of Android and unable to reproduce this. The user has both versions 4.2 and 4.4 and only has problems with version 4.2 so not sure if this is something we'll fix but thought I should submit an issue anyway.

The problem occurs in very long notes in Japanese (> 4000 words). When they try to input more text there's a long lag.

ticketid=2371777

**Comment by theck13** [comment]
Since we haven't received reports of this in years, I'll close this issue.
