### ISSUE TITLE
Long notes clipped when opened in Android app

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#321]
I have a user who reports that when they open a 1000+ line note in the Android app, the note is cropped and some of the lines missing from the bottom. They have to open the web app and restore a previous version to get the full note back. They've created a video of the issue - https://goo.gl/DeqaWy. I can't reproduce and have tried with the exact same note as them. It seems to be specific to their device. They're running Android version 5.0.2 on an LG-D337.

ticketid=2380908

**Comment by kevmarsden** [comment]
Another report of truncated notes in 2994287-t

User is using an LG G2 running Android 4.4.2

**Comment by theck13** [comment]
Since we haven't received reports of this in years, I'll close this issue.
