### ISSUE TITLE
Add application opened and closed events

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#329]
We should track when the app opens and closes in Tracks/Analytics

**Comment by theck13** [comment]
[`APPLICATION_OPENED`](https://github.com/Automattic/simplenote-android/blob/1b3c750bd939ce65fad0d3827e4bfa877c7468af/Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java#L139) and [`APPLICATION_CLOSED`](https://github.com/Automattic/simplenote-android/blob/1b3c750bd939ce65fad0d3827e4bfa877c7468af/Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java#L140) events were added in https://github.com/Automattic/simplenote-android/pull/336.
