### ISSUE TITLE
Blank note disappears in Android app

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#330]
1. Create a new note in the Android app.
2. Write a line in the note and then delete the line completely so the note is blank.
3. Then return to the note list by tapping the arrow at the top left.
4. The newly created blank note is not there.
5. Sign into the web app. The blank note is visible in the web app but not the Android app.

Possibly related to this issue, if you delete the blank note in the Android app before returning to the note list and then empty the Trash, the blank note disappears from the Trash but is still visible in the Trash on the web app. In other words, emptying the Trash in Android does not delete blank notes from the web app. 

ticketid=2458309

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
