### ISSUE TITLE
Links ending with a dash don't work

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#331]
This is a user report which I'm not able to reproduce but @supernovia can with Android 5.1 (It works with 5.0). Links don't work for me at all on Android 4.2.2. Links ending with a dash don't work because the app ignores the dash. 

Eg:
www.bloomberg.com/news/articles/2015-12-12/landmark-climate-change-agreement-hailed-as-leap-for-mankind-

This opens as a 404 on Android devices running 5.1, 6.0, and 6.0.1. 

Ticket 2456819

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
