### ISSUE TITLE
Improve contrast for dark theme option

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-android#339]
Request submitted via [Twitter](https://twitter.com/physicynicism/status/689455266161524736):

> Would really appreciate a higher contrast dark mode from @simplenoteapp on Android. Blue on grey is a bit of a pain. White text perhaps?

I've noticed myself that the dark theme, while it looks very nice, is very hard to read most of the time.

**Comment by roundhill** [comment]
The latest update added white text on a nearly black background.
