### ISSUE TITLE
Sign Up link hidden behind keyboard

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#345]
If you go to the Sign In screen on the Android app the keyboard pops up and obscures the "Sign Up" link.

![screenshot_2016-03-10-10-24-59](https://cloud.githubusercontent.com/assets/7946521/13666729/f8485ab4-e6aa-11e5-8ba9-a0a5ee14e433.png)

Ticket 1089303

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
