### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#346]
I've got a user who has to root their phone in order to sign into the Android app but they were able to sign into the web app. They're using Gionee dream d1 with 4.1.2. They've got special characters in their password and periods in their email address. I tested both things on my own Android and was able to sign in.

1093294

UPDATE*\* This user did not manage to sign in after all but is using the app without signing in. They still can't sign in.

**Comment by rachelsquirrel** [comment]
A similar issue has been reported by a user with an Android ONE mobile BQ Aquaris A4.5 running Android 6.0.

They can sign in using a web browser on their device but they can't sign into the app. It works on other Android devices. They've tried reinstalling the app on this device already but it didn't help.

#2893479-t

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
