### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#347]
I've had a few reports of this. They say the battery drains really quickly when the app is running in the background. When they force quit the app it's fine.

This [user](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2593256&highlight=--+Mixed+--&ticketsearchid=1101082) is Android Marshmallow on Nexus 6P

**Comment by catkit** [comment]
I got another user report of this issue.

They are using a Motorola Moto x force on android 6.0.1.

They sent screenshots to help:

![](https://cloudup.com/cu-A-VoBvOQ)

**Comment by roundhill** [comment]
#414 fixed this.
