### ISSUE TITLE
Allow enable/disable of "smart links"

### ISSUE THREAD

**Issue by travisw** [Automattic/simplenote-android#357]
I have a user request to allow the disabling of automatic linking for phone numbers and URLs.
Similar to what's available in the Mac app when you toggle Substitutions > Smart Links.

Ticket no.: 1165528

**Comment by KokkieH** [comment]
Another via [Twitter](https://twitter.com/user/status/841534921411710976)

**Comment by katinthehatsite** [comment]
Another report in #10761860-zen

User mentioned:

> The app started "guessing" what constitutes a "link" and just puts them everywhere, so I have half my notes in blue and the other half in black. 
> Being able to select an area and id it as a link would be nice

**Comment by Robertght** [comment]
Hi there,

We've experienced this behavior on a user's Android phone, but not on the Mac app or on the web app.

Here's how it looks for them:
![image](https://user-images.githubusercontent.com/6737345/38777437-a8b8ddea-40b0-11e8-8c8b-40d18c8c929e.png)

I was able to replicate the one with the mark between the numbers(900.21343), but that's it.

#1042498-zen

**Comment by katinthehatsite** [comment]
The user in #1076186-zen noticed an interesting patter:

When they create notes in French, somehow the auto-detections happens on street addresses and stops in French before preposition "de":

```
And: 
'''95 rue beaubourg 75010 Paris. De

Vers Opéra : 
Rue Saint Anne, plein de restaurants'''

also stops at ''' plein de '''
```
And finally: 
```
'''95 rue beaubourg 75010 Paris. De
Vers Opéra 
Rue Saint Anne, plein de restaurants'''

stops at '''Paris. De''' (I removed the ':')
```

**Comment by dorimoli** [comment]
A user comments that Simplenote is adding irrelevant hyperlinks to text. According to the user, sometimes it's part of a sentence or a string of numbers.  When he retypes to have the text without the hyperlinks, Simplenote re-applies them. He is using an Android device. Ticket no. 1179539

**Comment by rantoncuadrado** [comment]
#1179539-zen gives us a rich explanation with a use case, detailed steps to reproduce the issue and also a screenshot.

**Comment by adamjohndaly** [comment]
I have a report of this happening in the latest version of Simplenote on Android. It is not happening on iOS or Web. I am able to reproduce the behavior. 

> Google Pixel 3a running Android 11
> Simplenote v2.24.1
> This behavior does NOT happen when I use Simplenote on my PC in Firefox
> 
> Anytime I type a 4 digit number followed by the division symbol / then a 3 digit number, the expression converts into a blue link. Any suggestions?
> 
> 
> 2000 / 100
> 2000 / 400

![Screenshot_20220909-114723](https://user-images.githubusercontent.com/18173779/189955967-5f4de9bb-4769-44b3-8598-e1c25b4e00c7.jpg)

https://woothemes.zendesk.com/agent/tickets/5539418
