### ISSUE TITLE
Date translation "quoted" on the Note info bottom sheet

### ISSUE THREAD

**Issue by maxme** [Automattic/simplenote-android#360]
`24 mai 'à' 10:55` should be `24 mai à 10:55`

![screenshot_20160524-105744](https://cloud.githubusercontent.com/assets/40213/15498103/5b651352-219e-11e6-946f-e4111c390f93.png)

**Comment by theck13** [comment]
Closed by https://github.com/Automattic/simplenote-android/pull/932.  See the screenshot below for illustration.

![360](https://user-images.githubusercontent.com/3827611/75552354-5a972000-59f3-11ea-8f7c-ccddcd0952c0.png)
