### ISSUE TITLE
Radio button appears to right of Trash icon when bulk-selecting notes

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-android#363]
Reported via [Twitter](https://twitter.com/user/status/743422689205960704)

A user with the 1.5.0 beta-version requested that the Trash icon should appear on the right when bulk-selecting notes, to be consistent with the icon's positioning in the rest of the app.

At the moment the app shows a radio button to the right of the Trash icon when bulk-selecting.
![cleq_kaugaazcpf jpg_small](https://cloud.githubusercontent.com/assets/11873759/16146673/a4894500-347f-11e6-97f6-e6a714bf28b3.jpg)

That button does not show in the production version of the app, so I'm wondering if its inclusion in the beta is intentional, or if it might be a bug. If it's intentional, can the position be changed to be consistent with the rest of the app?

**Comment by theck13** [comment]
The _*Move to Trash*_ action appears to the right of the _*Pin to Top*_ action on Simplenote 1.7.0.  See the screenshot below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/58144171-97cfb580-7c0a-11e9-954e-879f0165d667.png"><img src="https://user-images.githubusercontent.com/3827611/58144171-97cfb580-7c0a-11e9-954e-879f0165d667.png" width="360"></a>

I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
