### ISSUE TITLE
A tag side; where you can sort tags and put a note in a subtag

### ISSUE THREAD

**Issue by eleijonmarck** [Automattic/simplenote-android#370]

**Comment by MorgothSauron** [comment]
Like notes, there should be an option to sort the tags or not.

As for sure tag I got inspired by Google:
- tag1
- tag1_subtag1
- tag1_subtag2
- tag1_subtag1_subsubtag1

I could not use '/' as a separator. Selecting a tag shows notes correctly, but when editing tags the tags using '/' do the display the notes count.
