### ISSUE TITLE
Swiftkey covers up tag predictions

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-android#373]
User-reported: 

Tag predictions drop below Swiftkey keyboard.

Samsung Galaxy S4 GT-I9506,
Running on Android v.5.0.1,
With a SwiftKey v.6.3.8.82.

Seems to be somehow connected to user multitasking within other applications.

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
