### ISSUE TITLE
Add possibility to set reminders for notes

### ISSUE THREAD

**Issue by smonsays** [Automattic/simplenote-android#376]
It would be a nice feature to be able to set time controled reminders to notes, which then pop up in the notification area at the defined time.

**Comment by philgood** [comment]
I would like to see this feature incorporated into the app.

**Comment by marwendoukh** [comment]
Hi @roundhill , I'm currently developing this new feature and I have some questions . How can I contact the Simplenote team ?

**Comment by roundhill** [comment]
@marwendoukh Since we've gone open source, perhaps we should create a Slack group to use for Simplenote dev? You can ask questions here, too.

**Comment by marwendoukh** [comment]
Well , how can I get the "id" of a given Note ? because every Reminder should have its "NoteID"

**Comment by roundhill** [comment]
> Well , how can I get the "id" of a given Note ? because every Reminder should have its "NoteID"

Every note is a Simperium object with its own key, so use `note.getSimperiumKey()`.

**Comment by Jonatino** [comment]
Yes please!! This is a feature I think a lot of people want. In Google Keep I have a note to send a reminder every day at 6:45PM for stuff I think of during the work day but will forget by the time I get home.

**Comment by BrixV2** [comment]
Please!

**Comment by unai-ndz** [comment]
Please!

**Comment by Wizardling** [comment]
I would also love this feature to be added, along with the ability to set a reoccurring notification. Then Simplenote could totally replace Google Keep on my Android devices.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
