### ISSUE TITLE
Font Size Setting Does Not Affect Markdown Preview

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-android#377]
### Expected

The font size setting in the app affects text within the All Notes list, the Trash list, the Edit tab, and the Preview tab.
### Observed

The font size setting in the app affects text within the All Notes list, the Trash list, and the Edit tab.
### Reproduced
1. Open a note with Markdown enabled.
2. Note text size in _Edit_ tab.
3. Note text size in _Preview_ tab.
4. Go to _Settings_.
5. Tap _Font size_ option.
6. Choose different option than what is selected.
7. Note text size in _All Notes_ list.
8. Open same note as in Step 1.
9. Note text size in _Edit_ tab.
10. Note text size in _Preview_ tab.
##### Tested

LG G4 (LG-H815) on Android 6.0.1 with Simplenote 1.5.1

**Comment by eduardozulian** [comment]
Reopening this as it seems that it's not working anymore. The font sizes on both Edit and Preview are completely different.

Reported by a user on 3750787-zen
