### ISSUE TITLE
Adjust the location of the add tag button

### ISSUE THREAD

**Issue by rwaynick** [Automattic/simplenote-android#378]
In #2794112-t,

> It sits at the bottom of the screen, right above the keyboard and predictive bar (Swiftkey). On most notes, I accidentally touch "Add tag" at least once and begin typing there instead of within the note.

**Comment by marwendoukh** [comment]
@rwaynick Should we relocate it like this ?

![photo361377715518024004](https://cloud.githubusercontent.com/assets/10298519/18022131/4853bcf6-6be4-11e6-86ec-82b5d074f487.jpg)

**Comment by roundhill** [comment]
It used to be at the top, actually. Having at the bottom hasn't been a problem for me, and it matches the design of the other apps...

**Comment by marwendoukh** [comment]
So , @roundhill  should we keep it in the bottom ? what about the issue reported by @rwaynick ?

**Comment by rwaynick** [comment]
Maybe a little extra space at the bottom between the top of the keyboard and horizontal line?

**Comment by marwendoukh** [comment]
Does this fix the problem ?
![photo361377715518024005](https://cloud.githubusercontent.com/assets/10298519/18022830/2bcf3438-6bea-11e6-89fb-77b9373c64f6.jpg)

**Comment by BitcoinBelieverxxx** [comment]
Where do i write that down....in a script

**Comment by marwendoukh** [comment]
@roundhill look at this issue  [#373](https://github.com/Automattic/simplenote-android/issues/373) , it have the same problem . I would like to suggest that we let the user to choose the location of the tag bar in the preferences. What do you think ?

**Comment by roundhill** [comment]
Let's hold off on this for now. I'll check on Google Play to see how common the issue is.

**Comment by Donkey-Doug** [comment]
Why not relocate it to the 3-dots menu? It is typically only used once and should not have to be visible all the time.
