### ISSUE TITLE
Folders for notes

### ISSUE THREAD

**Issue by bastadur** [Automattic/simplenote-android#379]
A little suggestion from me - It would be extremely useful if you added the option to put notes into folders. I like it how MobisleNotes is doing it, so something similar would be great.

**Comment by danielms215** [comment]
I think Simplenote has sided with tags over folders to conserve simplicity and minimalism. I emulate folders by using tags, and after getting used to them I find that I like them even more than I like folders.

Have you tried using tags as folders? You should give it a shot! :)

**Comment by geekpete** [comment]
We need multi-select tagging to be able to batch sort notes or batch add tags to multiple notes.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
