### ISSUE TITLE
i18n Changelog/description suggestions

### ISSUE THREAD

**Issue by kristarella** [Automattic/simplenote-android#384]
Suggestion to improve changelog notes as seen in Google Play store in Japanese, especially for Markdown. They say:

> Let me say translating "Markdown" to "値下げ" is definitely incorrect. "値下げ"
> means price down in Japanese.
## Original English
- Fixed the ActionSheet on iPad Devices
- New Markdown Support!
- Updated Sync'ing Core
- Added Printing Capabilities to the Share Sheet
- Multiple bugfixes here and there!
## Your translation
- iPadのデバイス上のアクションシートを修正しました
- 新値下げサポート！
- 更新の同期コア
- 共有シートに追加された印刷機能
- ここにある複数のバグ修正！
## My suggestion
- iPadのアクションシートにおける不具合を解決しました
- Markdownプリビュー機能を新たにサポート！
- 同期エンジンのアップデート
- 共有シートの印刷機能を追加
- いくつかのバグを修正しました！

Kayako ticket: #2818968-t

**Comment by theck13** [comment]
Those release notes are from an out-dated version of the Simplenote iOS app, 4.4.1.  We'll keep an eye on translations for future releases.
