### ISSUE TITLE
Simplenote android app generates 700MB of traffic on my mobile network in a couple of hours

### ISSUE THREAD

**Issue by elpraga** [Automattic/simplenote-android#385]
Something is horribly wrong..

I guess it comes down to using images in a markdown formatted note, but still!! More then 700MB of mobile data!!! Most of it must have been in the background though, because all the images I have used don't have even 34MB together. And I am sure I did not open the note 28 times...

I have used following syntax:

```
![alt text](https://tomaskaluza.ocloud.de/index.php/s/WrDAZRqKJSVQiKz/download "Preliminary English Test - Extra - with answers - Front Page")
```

to insert some page covers of books I was working on..

I have never had any problems with data consumption with the android app, so I am pretty sure this incident is related to the images.

Please look at it as soon as you can. 

I will provide more information if needed.

Best regards.

Tomas

**Comment by dmsnell** [comment]
Thanks for the report @elpraga.

I did some initial investigation here and noticed the following headers coming from the server supplying that image…

```
Date: Mon, 12 Sep 2016 18:38:56 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
X-Powered-By: PHP/5.5.9-1ubuntu4.9
Set-Cookie: cookie-id; path=/; HttpOnly
Expires: 0

Cache-Control: must-revalidate, post-check=0, pre-check=0

Pragma: public
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
Content-Disposition: attachment; filename*=UTF-8''Preliminary%20English%20Test%20-%20Extra%20-%20with%20answers%20-%2001%20front.jpg; filename="Preliminary%20English%20Test%20-%20Extra%20-%20with%20answers%20-%2001%20front.jpg"
Content-Transfer-Encoding: binary
Content-Length: 4778611
Content-Type: image/jpeg
```

Notice the cache control. I believe that what is happening is that the image server is explicitly telling Android _not_ to serve a cached image (if it's out-of-sync with the server). With `must-revalidate` having no partner, such as an `ETag` or `last-modified`, I believe that this requires that Android verify that the contents of the image in its cache match what is currently served from the server, meaning that it has to re-download the entire thing.

If this is the case, there's not much we can do without violating the HTTP protocol I'm afraid.

**Comment by elpraga** [comment]
Ok. 
Thank you for a quick reply. But I still think that the images should not have been downloaded in the background. There is no need for it if they are not being displayed at all, especially if they don't get cached.

I was basically trying to play around with inserting images, but truly, 700MB is too much and very dangerous.

What do you think?

**Comment by elpraga** [comment]
I am sorry, I forgot to mention you @dmsnell :smile: 

Obviously, I have no clue how the MarkDown rendering works, but does it make sense to render notes that are no displayed?
