### ISSUE TITLE
Material Design on pre-Lollipop devices

### ISSUE THREAD

**Issue by Tunous** [Automattic/simplenote-android#391]
There are few user interface elements such as switches which aren't in Material Design style when running application on pre-Lollipop devices.

- [x] Switches in note info bottom sheet
- [x] Tag renaming dialog
- [x] Tags input field
- [x] Switches in settings
- [x] Dialogs in settings
- [x] Settings section headers 

# Question

I can try and create pull request(s) solving these issues but I have a question whether I should make these changes in one pull request or few separate focused on specific UI elements?

# Images

![Switches](http://i.imgur.com/q11tuVt.png)
![Rename dialog](http://i.imgur.com/oPTvnKj.png)
![Settings headers](http://i.imgur.com/1GkJP19.png)
![Settings dialogs](http://i.imgur.com/KqUobyl.png)

**Comment by roundhill** [comment]
You can do one PR, as long as it isn't too large. Thanks for contributing!

**Comment by Tunous** [comment]
Ok, I'll see how it turns out in a few days.
