### ISSUE TITLE
Enhancement:  add support for rendering pipe tables in Markdown

### ISSUE THREAD

**Issue by elpraga** [Automattic/simplenote-android#392]
Would it be possible to add the support for Markdown pipe tables?

**Comment by MaiLunJiye** [comment]
code blocks rendering error 

android version: 1.5.3
rom : CM13

the code of markdown:
![picture](https://i.upc.edu.cn/dcp/uploadfiles/twitter/2016/12/3/bc914f78a37b48969a2d06fa62c5e96b.png)

but in the preview, the code block look like this
![picture2](https://i.upc.edu.cn/dcp/uploadfiles/twitter/2016/12/3/f55c3cbaa6644b56a38002fee6284552.png)

and the same code in the linux:
![linux](https://i.upc.edu.cn/dcp/uploadfiles/twitter/2016/12/3/ecfb3f36a2c44820b2b96ddef0ecb44a.png)

**Comment by quocvu** [comment]
+1

**Comment by richardtkemp** [comment]
+1

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
