### ISSUE TITLE
Disappearing BottomSheetDialog

### ISSUE THREAD

**Issue by Tunous** [Automattic/simplenote-android#394]
When closing any of the note bottom sheet dialogs via swipe down gesture they no longer appear but only show dimmed screen.

This appears to be support library bug and I didn't find a solution for that other than recreating bottom sheets every time.

Relevant android bugs issue: https://code.google.com/p/android/issues/detail?id=220706

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
