### ISSUE TITLE
Preformatted code blocks designated with ``` or ~~~ are not rendered correctly

### ISSUE THREAD

**Issue by mobusby** [Automattic/simplenote-android#411]
Code blocks in a note render fine if every line is preceded by two indentation levels. However, code blocks designated by the Markdown standard syntax of three [`] characters or three [~] characters on their own line before and after the code block are not rendered as preformatted blocks in the app.

**Comment by thisispiers** [comment]
+1

**Comment by rachelsquirrel** [comment]
Another report in #3129506-t

Related issue: https://github.com/Simperium/simplenote-gae/issues/140

**Comment by carlba** [comment]
+1 would be awesome if this was fixed

**Comment by msilbers** [comment]
This seems to work just fine if you have at least one full enter/space before the code markdown (```) starts.

**Comment by theck13** [comment]
I confirmed the behavior works as @msilbers described with both <code>```</code> and <code>~~~</code>.  See the screenshots below for illustration.

![markdown](https://user-images.githubusercontent.com/3827611/58189583-04cd6480-7c78-11e9-9dfc-0a0e852596ab.png)
