### ISSUE TITLE
Setting to allow markdown format by default for new notes

### ISSUE THREAD

**Issue by geekpete** [Automattic/simplenote-android#412]
Would be great to be able to have a setting that defaulted all new notes to markdown rather than having to switch the note to markdown every time.

**Comment by theck13** [comment]
When you say "switch the note to markdown every time," do you mean using the **Enable markdown** switch in the **Info** sheet or swiping from the **Edit** tab to the **Preview** tab?  If you're referring to the former, I have good news; that feature already exists!  After enabling Markdown for the first time, all new notes will have Markdown enabled by default.  If you're not seeing that behavior, please include which device, Android version, and Simplenote version you are using so we can better troubleshoot the issue.

**Comment by geekpete** [comment]
Sounds awesome! I'll test again and see if I'm getting Markdown by default.

**Comment by geekpete** [comment]
Works as expected! Thanks!

I guess I just didn't notice this before.
