### ISSUE TITLE
Untagged notes

### ISSUE THREAD

**Issue by lassiewoof** [Automattic/simplenote-android#417]
In my opinion it would be great to have an option to change the main screen. I would like to see all the untagged notes as the main screen, instead of all the notes, which is chaotic. It would be amazing because all the other notes are already organized in folders thanks to tags, but we cannot see only untagged ones. This could be useful also to avoid to display, at application startup, some notes that I prefer to stay "hidden" in their folders.

**Comment by beaucollins** [comment]
What if there were an "Untagged" list item below "All Notes"?

**Comment by theck13** [comment]
> What if there were an "Untagged" list item below "All Notes"?

That's one solution.  We would also need to remember the last selected list item in the navigation drawer (i.e All Notes, Untagged, Trash) since it currently defaults to All Notes at startup.

Another option that wouldn't require any code changes would be to tag all untagged notes with "untagged" or "none" or something similar.  Unfortunately, that workaround would still show All Notes at startup due to the point I mentioned above.

**Comment by beaucollins** [comment]
I think remembering last state on start up is worth its own issue.

**Comment by roundhill** [comment]
We get occasional requests for this, but it is not enough IMO to add another menu item. Maybe we could do something a little more hidden like a special search term or something?

If we added it here we would also want to consider adding it to all of the apps. cc @drw158 for his thoughts.

**Comment by theck13** [comment]
> I think remembering last state on start up is worth its own issue.

Adding that separately would enable the workaround I mentioned and avoid any additional interface.

**Comment by lassiewoof** [comment]
In my opinion adding an "untagged" list item is awesome. But there should be the opportunity to choose what to see at startup. Possible solutions are:
- See only untagged notes at startup
- Add a toggle in the settings to choose between all notes and untagged notes

To avoid taking too much vertical space I would move the trash down, leaving in the bottom part of the list two icons: one for the settings, one for the trash.

**Comment by lassiewoof** [comment]
Any news?

**Comment by lassiewoof** [comment]
Any news about it?

**Comment by drw158** [comment]
I think we can at least tap into the hidden `tag:` search feature. `tag: untagged` could list all untagged notes, as long as no one has actually tagged a note as `untagged` :). 

That doesn't solve the original issue of seeing untagged notes on startup though.

I think it's a matter of taste, similar to managing email. Some like an empty clean mailbox, all sorted in folders. Others don't worry about it and keep a permanent ever growing list of emails in their inbox.

Personally I don't think the original intent of the app was to create a habit of sorting the notes into folders and maintaining an empty notes list.  Tags are more of a filter option for the main All Notes list.

**Comment by lassiewoof** [comment]
I personally don't agree with that, I have a lot of notes and they are organized thanks to tags. When I open the application I see only a long list of various notes and I *always* end up in searching them using the tags directory. Imho having this long list of all notes is almost useless. I forget to tag notes only if I'm in a hurry and I don't have time to do it. So this means that they are important to me because I took them in particular moments and I like to have them always visible without being distracted by other useless information. I know untagged notes resolve my problem, I hope it could be useful for you too.

**Comment by drw158** [comment]
So, you'd like to have untagged notes in the main list visible, but the notes you have tagged are still present and therefore distracting?

Is your goal to tag these notes eventually, or are they forever untagged?

**Comment by lassiewoof** [comment]
Yes, I'd like to have only untagged notes in the main visible list and the other notes (tagged ones) are still there distracting me.
About your second question the answer is: it depends. Most of the time I tag the notes but sometimes I don't. As a very stupid example I use simplenote also for shopping lists, or to remember names of people, places, codes and I never tag this kind of notes. Many times a note doesn't fit in any existing tag and I don't create a new tag only for single cases...

**Comment by lassiewoof** [comment]
Any news about this thread?

**Comment by roundhill** [comment]
We added the `Untagged notes` filter to the sidebar a few releases back 👍
