### ISSUE TITLE
Transform the apk for blackberry and share it

### ISSUE THREAD

**Issue by CorentinLemaitre** [Automattic/simplenote-android#419]
Hello,

I am blackberry 10 user and i love it. I love also simplenote.

Currently the simplenote apk is supported in the blackberry but there is some bug (see the issue dedicated to it).

I want to rebuild a blacberry app from the apk ( the how to explained here : http://developer.blackberry.com/android/documentation/rpkg_with_bb_plugin_for_android_stdio.html )
I 'm not a developper but it seems to be not so hard.

There is the possibility to share the new application in the blackberry world (play store for blackberry).
I prefer to ask : can i do that? do i have to fork the project? 

Also, If somebody want to do it with me i am really interested.

**Comment by theck13** [comment]
Unfortunately, we don't support BlackBerry devices.  You can build and run the source code as is, but it doesn't support production Simplenote accounts with the example Simperium app ID and key.  That means users won't be able to log in with their production Simplenote account.  Also, things like publishing and sharing won't work.
