### ISSUE TITLE
Android tablet: App crashes in landscape mode

### ISSUE THREAD

**Issue by fditrapani** [Automattic/simplenote-android#423]
Related to to issue #3034317-t. A customer wrote in with the following issue:

> Happened on a Lenovo tablet wich Android Kitkat 4.4. When I opened a note in Portrait view and then turned the tablet in landscape mode, it automatically crashed.

**Comment by theck13** [comment]
I wasn't able to reproduce the crash on two devices (Samsung Galaxy S III on Android 4.4.4 and Samsung Galaxy Tab 3 on Android 4.4.2) or an emulator (Nexus 5 on Android 4.4.2) running Simplenote 1.5.5.  I tested opening a note in portrait orientation then rotating into landscape orientation without Markdown enabled, with Markdown enabled while viewing the Edit tab, and with Markdown enabled while viewing the Preview tab.

We might need to find out exactly which device model, what flavor of Android (i.e. stock, AOSP, AOKP, CyanogenMod, etc.), and what version of Simplenote is being used.  A stack trace would be extremely helpful too.

**Comment by fditrapani** [comment]
Thanks for the reply @theck13. I'll follow up with the customer to see if they can provide us with more info.

**Comment by nthcircle** [comment]
I just noticed this bug. It's related to stack trace logged here:
https://github.com/Automattic/simplenote-android/issues/444

I've submitted a PR with a fix, along with step to reproduce, here:
https://github.com/Automattic/simplenote-android/pull/453
