### ISSUE TITLE
Organizing notes

### ISSUE THREAD

**Issue by dokker** [Automattic/simplenote-android#424]
Would you consider to implement **one level folder support** for better organization of notes?
If the folders implementation beyond the barriers of simplicity, at least **nested tags** support?

**Comment by pihentagy** [comment]
Maybe duplicate of #379

**Comment by ericbrandwein** [comment]
You *could* emulate nested tags by just using a tag only if other is present, but that isn't the best approach I believe.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
