### ISSUE TITLE
Tag list order

### ISSUE THREAD

**Issue by memeplex** [Automattic/simplenote-android#428]
There are some open issuses for nested tags and folders, but there are many workarounds for that using a well designed naming convention to sort tags in a hierarchical or another fashion.

The 80/20 would suggest you sort the tags in the sidebar in alphabetical order! Currently they're displayed in creation time order, which is mostly random and useless.

**Comment by gracie** [comment]
Another request in #3241529-t, asking to be able to reorder tags within the Android app, according to individual preference.

**Comment by GeoJunkie** [comment]
Another request in #696030-zen for user to be able to reorder tags in Android.

**Comment by roundhill** [comment]
Dupe of #283
