### ISSUE TITLE
Make easier to change tags

### ISSUE THREAD

**Issue by memeplex** [Automattic/simplenote-android#429]
I use the app for task management for which I'm constantly changing tags, say, for todo to done. Currently you have to:

1. Open the note
2. Scroll to the bottom
3. Open the keyboard
4. Delete the current tag
5. Start typing the new tag and complete it from the suggestions

This is way too cumbersome.

**Comment by rachelsquirrel** [comment]
I've also had a report about tags being hard to find as you have to scroll all the way to the bottom.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
