### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by memeplex** [Automattic/simplenote-android#430]
If this is already possible I'm not able to figure out how to do it. Neither tag:<tag> nor plain <tag> match anything.

**Comment by ericbrandwein** [comment]
For the same reason, there is no way of finding notes by multple tags, at least not one that I'm aware of.

**Comment by robertoissc** [comment]
I believe this should be closed. :)

**Comment by theck13** [comment]
Yep, this can be closed.  That feature was added in https://github.com/Automattic/simplenote-android/pull/479.
