### ISSUE TITLE
Settings page cut off in Android Page using Simplenote in a browser.

### ISSUE THREAD

**Issue by NujabesSoul** [Automattic/simplenote-android#435]
Steps:

1. Open Browser on Android phone
2. Go to simplenote.com
3. Login to simplenote
4. Click email at top-right
5. Click 'Account Settings'
6. See that part of the settings is cut off

This is probably due to the CSS found here:
`#accountsettings {
    margin: 0 auto;
    float: none;
    width: 420px;
}`

The width doesn't accommodate for the browser. I have tested this on several Android phones and had the same result. I understand most people will use the app but I noticed this testing on the browser for on Android phones for once.

Here's an image of what it looks like: [https://cloudup.com/i_6hUtDE1rr](https://cloudup.com/i_6hUtDE1rr)

**Comment by roundhill** [comment]
Thanks for the report, I made a copy of the issue at the private repo for our web app.
