### ISSUE TITLE
Weird search behaviour in notes with Chinese characters

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#437]
Searching for English strings in notes with Chinese characters returns strings different to the search string.

**Steps to repro:**

1. Copy/paste this example note as a new note in Simplenote - https://app.simplenote.com/publish/Dx8cj2
2. Search for the string "get" in the app.
3. The note with Chinese characters will appear in the search results with highlighted strings that are not "get".

**Comment by rachelsquirrel** [comment]
Reported in #3100531-t

**Comment by iamgabrielma** [comment]
Reported in #3113041-t

**Comment by KokkieH** [comment]
We've had a report [via Twitter](https://twitter.com/yking_khan/status/995884391623790592) of a similar issue in a note using the Urdu alphabet. In that case even searching Urdu causes text not matching the search string to also be highlighted. Confirmed by @ehti

**Comment by roundhill** [comment]
I think #562 is related.

**Comment by roundhill** [comment]
Should be fixed now, we can reopen if we get any more reports.
