### ISSUE TITLE
Set of numbers automatically becomes phone link

### ISSUE THREAD

**Issue by vparkhere** [Automattic/simplenote-android#440]
If you enter a set of numbers, they'll automatically become a phone number link you can select to start a call.

It requires a minimum 7 numbers, no dashes, to create the link.

Tested and confirmed on a Galaxy S7 Edge.  User reported on a Samsung Galaxy Note 4 running Android 5.0.1

![samsung galaxy note 4](https://cloud.githubusercontent.com/assets/11635760/24227797/dc5eb5a8-0faa-11e7-9315-4b608dc22a83.png)

#3117877-t

**Comment by gracie** [comment]
#701205-zd reported numbers like the following also became links:

2015
10/05

Oddly, the following number did not, even though it's the same structure as one listed above:
08/09

**Comment by Mojahidmd** [comment]
+8801927598932reported numbers like the following also became links:

**Comment by sdixon194** [comment]
Another report in 1179539-zen

**Comment by katinthehatsite** [comment]
Also reported by the user in 1179539-zen; the screenshot: 

https://cloudup.com/c4gTu_qf3gQ

**Comment by kriskarkoski** [comment]
Here's the example note text this user provided ^

> Doctor–patient communication is a multidimensional process, which on the doctor's part includes delivering clear and complete information about the disease, its symptoms, possible treatments, their side‐effects and the prognosis.7, 36, 37, 38 In addition, doctor's assessment of the patient's understanding of the information is recommended,27, 39 as well as discussing patient's willingness to be involved in the decision‐making process,26, 40 and support the patient emotionally.41, 42, 43 Similarly, the patient is expected to provide complete information regarding his/her symptoms,40, 44, 45, 46, 47 ask questions regarding unclear information45, 46, 47 and/or lacking information such as medical treatments and procedures, side‐effects and prognosis.40, 45, 48 In addition, expressing fears and worries by the patient is advisable.18, 41, 49 In this model of interaction, the physician's knowledge of the patients' preferences and willingness to take part in the medical decision‐making process are of special importance.26, 46, 50
> 
> ICD-11 BETA
> X EXTENSION CODES
> These categories should never be used in primary coding. They are provided for use as supplementary or additional codes when it is desired to identify more detail in diseases classified elsewhere.
> 
> partial recovery
> residual sxI
> ICD-11 BETA X Extension codes
> TEMPORALITY
> Course of the Condition: 
> 1. Pattern, Activity, or Clinical Status
> XT3B Asymptomatic

**Comment by jeremypaavola** [comment]
Reported as well in 1211755-zen

**Comment by theck13** [comment]
This is working as expected.  The code in Simplenote uses a standard Android utility to detect links in notes.  A setting to disable detecting links if the user prefers notes without those links as added in https://github.com/Automattic/simplenote-android/pull/533.  Open the navigation drawer, tap the ***Settings*** option, scroll to the ***Editor*** section, and tap the ***Detect links*** item.
