### ISSUE TITLE
Tag field not visible when opening note

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-android#442]
When creating a new note the tags field is not visible, but is hidden behind the keyboard. Need to drag the screen upwards to reveal it.

When opening an existing note the tags field is also not visible at the bottom and requires dragging the screen up. If you tap on the note to open the keyboard the tags field is still hidden behind the keyboard as well. This happens regardless of the length of the note - the note can only be one line long, but the tags field would be too far down the screen to see.

Reported by a user via Twitter, but I was able to confirm on two different devices as well.

Confirmed in version 1.5.5, Android 6.0.1 and 7.1.2, on a Pixel, Nexus 5X, and Sony Xperia M4 respectively.

**New note:**
![screenshot_20170408-084119](https://cloud.githubusercontent.com/assets/11873759/24826475/4fe60e70-1c37-11e7-815f-e620dff6ae6d.png)

**Existing note:**
![screenshot_20170408-084303](https://cloud.githubusercontent.com/assets/11873759/24826495/9ebe9076-1c37-11e7-9614-c63409f771db.png)

**Drag note up to reveal tags:**
![screenshot_20170408-084308](https://cloud.githubusercontent.com/assets/11873759/24826496/a07662d6-1c37-11e7-8a70-3e19f1faf036.png)

**Comment by theck13** [comment]
That UI should be improved.  If you have a long note, you have to scroll for days to see the tags.  What about adding the tags field to the bottom sheet triggered by the info action?
  That would allow you to access the tags regardless of keyboard or note length.  @drw158, what do you think?

![info](https://cloud.githubusercontent.com/assets/3827611/24834174/0b7e41a8-1c9b-11e7-88b9-75b3106162f0.png)

**Comment by drw158** [comment]
I think that it's probably ok to put tags in the info panel. I personally never have to scroll a few swipes to get to the bottom of a note. I'm also more partial to the Bear approach of just being able to add a tag anywhere in the note.

We should fix the hidden tag field first if it's possible. On iOS, once you tap on the note text, the keyboard pops up, and the tag field is visible right above the keyboard.

**Comment by delta-emil** [comment]
If the tags field needs to be moved, I'd suggest putting it somewhere in the top strip where the EDIT/PREVIEW buttons are for markdown-enabled notes.

Putting it in the info panel would make it a pain to reach when creating a new note. Oddly, that would be a usability problem comparable to the current bug in that you'd still need to an extra action to get to the tags field.

**Comment by kriskarkoski** [comment]
1809447-zen
