### ISSUE TITLE
Any option to show md files in preview mode first

### ISSUE THREAD

**Issue by dxnacho** [Automattic/simplenote-android#446]
I found out that note always open first in Edit mode. As most of the times I just wanna check notes and not write on them, I was wondering if a new option to "Show md notes in Preview first" could be added.

Many thanks!

**Comment by theck13** [comment]
Thanks for the feedback!  It looks like the same feature was requested in https://github.com/Automattic/simplenote-android/issues/434.  I'll close this issue since it's a duplicate.

**Comment by dxnacho** [comment]
Thanks!!
