### ISSUE TITLE
Markdown "code fences" not supported on android app

### ISSUE THREAD

**Issue by frabert** [Automattic/simplenote-android#447]
While I can successfully enter and preview github-style codefences from the windows app, they do not preview correctly on android, they basically get ignored.

**Comment by alexjgustafson** [comment]
3262159-t

**Comment by theck13** [comment]
This is a duplicate of https://github.com/Automattic/simplenote-android/issues/411.

I confirmed the behavior works by preceding and succeeding the code block with either <code>```</code> or <code>~~~</code> on a separate line.  See the screenshots below for illustration.

![markdown](https://user-images.githubusercontent.com/3827611/58189583-04cd6480-7c78-11e9-9dfc-0a0e852596ab.png)
