### ISSUE TITLE
Problem when using a Logitech k480 bluetooth keyboard

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#448]
I've got a report where the Logitech k480 bluetooth keyboard is crashing the app.

**Steps to reproduce:**
1. Open a note on an Android tablet with the Logitech keyboard.
2. Use the directional keys on the keyboard to move to the end of the note then press the right key once more.

Focus changes to a new blank page and there's no way to exit from the blank page without closing the note and opening again. The new blank page looks like a new note except that it's not possible to write in it.

#3238144-t

**Comment by theck13** [comment]
The blank page reference above _may_ be the ***Preview*** tab, but it will need to be investigated further.

**Comment by theck13** [comment]
This appears to be the same issue as https://github.com/Automattic/simplenote-android/issues/472.  Even though this was created first, I'll close it as a duplicate since https://github.com/Automattic/simplenote-android/issues/472 has more information and isn't specific to a certain configuration.
