### ISSUE TITLE
Swipe on text to markdown formating

### ISSUE THREAD

**Issue by CorentinLemaitre** [Automattic/simplenote-android#449]
Hello,
I love simplenote and because it is simple i use it for complicated things : task or check list. Something is really missing for me : the capability to swipe to edit text rapidly from mobile. 
I have seen a function on other app that can be usefull for simplenote:
you put your finger on a row, you swipe left to mark as todo '[ ]' , then right to check as done or left to mark as important '!!!'. 
The app that use that is : upword notes, here is a gif of there function. 

![swipe-list-2](https://user-images.githubusercontent.com/20289907/27070984-760dfbf4-501b-11e7-812d-f41fda7d2547.gif)

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
