### ISSUE TITLE
Line Spacing Changes When Editing Note

### ISSUE THREAD

**Issue by kriskorn** [Automattic/simplenote-android#450]
On the latest Android version (7.1.2) with the latest Simplenote app, it's okay when I open a note without altering it. But as soon as I change anything (add something, delete something), the spacing around that particular line contracts, so that it's uneven across the note, and so that the edited lines are harder to read and edit. The more edits I make, the more scrambled the note becomes.

Screenshot:
![screenshot_20170616-161538](https://user-images.githubusercontent.com/12064241/27228202-4b4e9716-52af-11e7-87b5-be34813cf50c.png)

3258766-t

**Comment by cecoates** [comment]
I was able to replicate this as well. Android 8.0, Nexus 5x, Simplenote version 1.5.6.

![screenshot_20171010-163228](https://user-images.githubusercontent.com/10121835/31412138-91851ab8-add9-11e7-87d1-3e80950b2d9c.png)

![screenshot_20171010-163133](https://user-images.githubusercontent.com/10121835/31412140-947e3736-add9-11e7-89e8-fb285d7254fc.png)

![screenshot_20171010-163243](https://user-images.githubusercontent.com/10121835/31412144-97d2a5b6-add9-11e7-9dfc-9ecc091cf432.png)

#724060-zen

**Comment by Cor-13** [comment]
I have the same issue. My setup is Android 7.1.2 (LineageOS 14.1), Samsung Galaxy S2 (GT-I9100), Simplenote version 1.5.6.

Will someone from Automattic look into this? I love Simplenote, but this bug is very annoying…

**Comment by roundhill** [comment]
I was able to reproduce. Working on the fix!
