### ISSUE TITLE
Search: View note from matching text of search result, instead of top of note

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/simplenote-android#454]
In iOS if you use search box, and click on a note that matches the search, it automatically scrolls down to the point in the note with the matching search result. 

On Android, it highlights the matching result during search. But when you click on a note, it starts off the note view at the top of the note instead of at the matching text from the search result.

**Comment by alexjgustafson** [comment]
3275386-t

**Comment by pauljacobson** [comment]
951319 too

**Comment by sdixon194** [comment]
954694-t

**Comment by sophiegyo** [comment]
Update (previously 951319-t) with screenshots at 1022718-t

**Comment by serabi** [comment]
1085670-t
