### ISSUE TITLE
Back arrow returns to a different view

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#458]
I'm unable to reproduce this but wanted to submit an issue in case others are running into this problem as well. 

Steps to reproduce:

1. Select a tag from the list of tags. 
2. Select and view one of the notes for that tag.
3. Tap the back arrow at the top left to return to the previous view. 

The user expected to see the notes from his tag selection but instead he was returned to the full note list.

Simplenote v.1.5.6, on an LG-H540 running Android 6.0.

621865-zen

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
