### ISSUE TITLE
Search doesn't support special characters

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#463]
Steps to reproduce:

1. Create a note with $.
2. Try searching for $.

The Android app doesn't find it but the web app does.

**Comment by roundhill** [comment]
We clearly need to fix a few things with search in the app, quite a few issues piling up.

**Comment by jamiepalatnik** [comment]
A user reported this as well in 1089651-zen.

**Comment by roundhill** [comment]
The app uses `SQLite` full text search, which doesn't support searching for a single special character. It is a word-based search and we won't be able to fix it easily.
