### ISSUE TITLE
Show notes without tag - find "orphans"

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#464]
**Steps to reproduce/understand**
I write a lot of notes and any one is supposed to have one single tag in order to assign it to a specific topic. I organize my notes by these topics.

**What I expected**
Show notes without tag in order to find "orphans"

**What happened instead**
This functionality is not yet available.

**OS version**
Android 6

**Comment by MorgothSauron** [comment]
+1. Showing orphans would be helpful to find notes for which I forgot to add a tag when I created it.

**Comment by bummytime** [comment]
Looks like this was addressed in #527 — closing.
