### ISSUE TITLE
Checking word count 

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/simplenote-android#466]
Ref ticket: 718667-zen

If user goes to check word count, app hangs and all edits are lost.

**Comment by maheshgaya** [comment]
How can we reproduce this issue?

**Comment by GeoJunkie** [comment]
I'm unable to reproduce the error myself, but have asked the user to try to narrow down the error by creating a short note and long note and try to cause the error to happen.

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
