### ISSUE TITLE
Need an Icon for Shortcut

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#467]
#459 added a handy way to create a new note from the app icon. It is currently using a black icon that we use for the new note icon in the app, and it doesn't look so good:

<img width="208" alt="screen shot 2017-10-09 at 9 54 19 am" src="https://user-images.githubusercontent.com/789137/31349590-b3ae7244-acd8-11e7-92c2-1d1f7f7e3913.png">

We can't dynamically tint the icon so we'll want to create one with a blue tint, and probably with a circular background?

**Comment by maheshgaya** [comment]
In Android 8:

![screenshot_20171011-184043](https://user-images.githubusercontent.com/11140545/31477387-634baa42-aed1-11e7-84d2-1d57608df79e.png)

**Comment by neelkadia** [comment]
As per my design sense current New Note shortcut icon is not that clean and elegant as other interfaces of Simplenote is. @roundhill @maheshgaya I want to work on this over this weekend for design and static/dynamic shortcuts also.

**Comment by roundhill** [comment]
Thanks @neelkadia, it really needs a better icon 👍
