### ISSUE TITLE
Alphabetic index on the right edge of the screen

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/simplenote-android#471]
Copying here a -happy- user suggestion 

`"I did wonder whether it might be worth adding an alphabetic index on the right edge of the screen in the mobile apps (similar to that in e.g. the native iOS contacts app - to allow quick access to contacts/notes starting with a particular letter)."`

#741594-zen

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
