### ISSUE TITLE
Duplicate Tags

### ISSUE THREAD

**Issue by JALusk** [Automattic/simplenote-android#474]
When applying tags to notes on simplenote-android, existing tags end up duplicated in the tags list.
Interestingly, they are still the same tag - clicking on either of the tags in the tags list narrows the notes list to the same set of notes. In fact, clicking on one of the tags in the tags list on Linux highlights both tag names in blue.

This happens whether I type in the tag name fully, or I use the autocomplete in the app.

**Comment by rachelsquirrel** [comment]
Also reported for the Mac and Electron apps: 

https://github.com/Automattic/simplenote-macos/issues/70
https://github.com/Automattic/simplenote-electron/issues/519

**Comment by lizkarkoski** [comment]
There's another report coming from Twitter: https://twitter.com/ktulu_0/status/931168389837488131

**Comment by SiobhyB** [comment]
This was also reported in 830155-z

**Comment by roundhill** [comment]
This is actually a bug in the electron app, we'll get a fix out in the next update.

**Comment by roundhill** [comment]
Fixed in the electron app, unfortunately any tags created before the fix in the app will need to be deleted/recreated in order to prevent the duplication.
