### ISSUE TITLE
Markdown rendering changed?

### ISSUE THREAD

**Issue by cocobelgica** [Automattic/simplenote-android#483]
I'm using the following note: https://daringfireball.net/projects/markdown/syntax.text as reference for Markdown syntax and I noticed in the last released(I'm on the beta channel) that some stuff like inline HTML are no longer rendered properly. Screenshot below for reference.

![screenshot](https://i.imgur.com/pGYD64R.png)

**Comment by roundhill** [comment]
Yup, HTML tags are no longer supported for security reasons. You'll need to use markdown syntax only. This also matches up with how the other Simplenote apps work.
