### ISSUE TITLE
Latest release (1.5.7) has missing apk asset

### ISSUE THREAD

**Issue by ravikg** [Automattic/simplenote-android#486]
In the latest release[ v1.5.7](https://github.com/Automattic/simplenote-android/releases/tag/v1.5.7) : build apk file is missing from the assets list.

FYI: @roundhill

**Comment by roundhill** [comment]
@maxme can you please add the APK to the latest release? 👍

**Comment by thenanobel** [comment]
@maxme I also need the APK file. Can you please add it?

**Comment by maxme** [comment]
Sorry I missed the first ping, v1.5.7 APK has been uploaded on https://github.com/Automattic/simplenote-android/releases/tag/v1.5.7

**Comment by thenanobel** [comment]
@maxme Thanks. Would you please tell me why is this not available on F-Droid?
