### ISSUE TITLE
Character count for Chinese/Japanese/Korean characters is incorrect

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/simplenote-android#495]
Currently Simplenote does not count words correctly for Chinese, Japanese, and Korean when I tested on my Android mobile device. This was originally a user reported issue.
Ideally, for these languages a character count would suffice as it's not commonplace to do word counts like we do in English.

Android(ver 1.5.7):
![screenshot_20180208-151216](https://user-images.githubusercontent.com/17694715/36003383-a8bccf7e-0ce2-11e8-9e0e-d71f95df8589.png)
It says 5 words, when there are actually 7 words. 

Total characters(without spaces): 18

**Comment by hichamboushaba** [comment]
I think we can close this ticket now, as the info panel shows the character count, and I confirmed it's correct for a Japanese text 
<img width="473" alt="Screen Shot 2021-01-07 at 11 08 50" src="https://user-images.githubusercontent.com/1657201/103880011-db757c80-50d8-11eb-8356-9df289d1e609.png">
