### ISSUE TITLE
Keep screen on while editing

### ISSUE THREAD

**Issue by gregmac** [Automattic/simplenote-android#500]
I use my phone for meeting notes, and as such, often sit it on the table in front of me during a meeting. It would be nice in this situation if the screen would stay on so I didn't have to wake/unlock the device to quickly add something.

Specifically, while the editor is open, it should prevent the screen from sleeping ([Android reference:  FLAG_KEEP_SCREEN_ON](https://developer.android.com/training/scheduling/wakelock.html)). This maybe needs to be a setting as well (I don't really think so, but others might).

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
