### ISSUE TITLE
Bug: Fingerprint not available on certain devices

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-android#501]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

1. Get a Redmi 3S Prime which has fingerprint reader on the back / Android Marshmallow device with Android 6.0.1 (not very sure which one is affecting this case)
2. Enable PIN lock in the settings

**What's expected**: Fingerprint reader mode is available and can be used to unlock.

**What happens instead**: No fingerprint reader mode when launching the app. Shows PIN reader instead. No fingerprint reader icon below the PIN input box either.

**Comment by arunsathiya** [comment]
#975103-zen

**Comment by arunsathiya** [comment]
The fingerprint reader mode is available on my OnePlus 5 with Android Oreo. Same Simplenote account logged in.

**Comment by roundhill** [comment]
Does the Redmi 3S Prime use the native android fingerprint api? I'm guessing not, otherwise it'd show up in the lock screen.

**Comment by arunsathiya** [comment]
Turns out you are right, @roundhill. Xiaomi is indeed not using native fingerprint API. There is a [similar post about it on the 1Password Community](https://discussions.agilebits.com/discussion/comment/364002/#Comment_364002).

**Comment by roundhill** [comment]
I don't think we'll integrate with any fingerprint APIs besides the native Android one, so closing this one.
