### ISSUE TITLE
Move simplenote-android and simplenote-ios to react native

### ISSUE THREAD

**Issue by natanielcz** [Automattic/simplenote-android#502]
I see that simplenote-android and simplenote-ios doesn't have a common base with simplenote-electron.
Maybe It's worth to consider moving those 2 apps to react native so We would be able to have the entire business logic common across all platforms. 

Currently when we fix some issue or create something new on one platform we have to migrate it to other platforms what isn't really convenient.

**Comment by roundhill** [comment]
While the idea sounds cool, one of the reasons for the separate Simplenote clients to exist is to showcase how Simperium can work across platforms natively with clear examples of how the libraries work.

So I think this is a _wontfix_ for now, unless something changes with how Simplenote utilizes Simperium.
