### ISSUE TITLE
Off-line created notes are not synchronized automatcially

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#511]
**Steps to reproduce/understand**
Create a new note while off-line (or with poor internet connection)

**What I expected**

- Re-establishing a (good) internet connection should synch (upload) this note automatically to be available on other devices.

- When closing the Simplenote App (1.5.8) without successful synch a warning message should appear: "Not all notes have been synchronized " 

**What happened instead**
The note is not synched / updated automatically.
Whereas "newer" notes (created on other devices) are downloaded automatically.
Work-around: I have to change the note, then it is synched / updated.

**OS version**
Simplenote 1.5.8 / Android 7.0

**Comment by gubrist** [comment]
**What happened instead**
The above-mentiond Work-around does **not** work: 
I change the note, then it is **still not** synched / updated.

**OS version** (many updates later)
Simplenote 1.7.0 / Android 9.0

**Comment by gubrist** [comment]
![round](https://user-images.githubusercontent.com/22197180/55712587-4c14d400-59ef-11e9-9fc4-c3b1f3603010.JPG)

I observe that the "time wheel" turns for many minutes
- even when attached to a fast WiFi .

**How can I monitor what the phone is exactly doing?
Is there a protocol or synchronization status of eacht message (e.g. "synched on")**

**Comment by gubrist** [comment]
- The download (form notes created on PC / other devices) works.
- It is the **upload** that (still) does not work.

**Comment by theck13** [comment]
I cannot reproduce that behavior with Simplenote 1.7.0.  Feel free to reopen this issue if you can.  See the animation linked below for illustration.

https://drive.google.com/open?id=1xF7xAMs2eqsi80I6UG9I9tfQEAEO2dkz

**Comment by gubrist** [comment]
Thanks. I could not reproduce the behaviour neither, currently.

How can I re-open this issue?

Because the following questions are stillopen:

**- 
-     How can I monitor what the phone is exactly doing?
-     Is there a protocol or synchronization status of each message or the synched message (e.g. "synched on")
-     How can I push the synchronization (e.g. by a button)?**

**Comment by theck13** [comment]
> How can I monitor what the phone is exactly doing?

The easiest way to verify notes are synchronized is to see the notes in two different apps (e.g. Android and web).

> Is there a protocol or synchronization status of each message or the synched message (e.g. "synched on")

No, there isn't any synchronization status.

> How can I push the synchronization (e.g. by a button)?

There is no synchronization button.  The apps will automatically sync when online.

**Comment by gubrist** [comment]
> The apps will automatically sync when online.

I assume the problem is that something is inhibting this synch.
