### ISSUE TITLE
Feature Request: Todo/checkbox bullet mode with: "o" -> TOUCH -> "x"

### ISSUE THREAD

**Issue by CryptoStar2000** [Automattic/simplenote-android#528]
Feature Request:
A simple mode for Android touch devices that changes a "o" bullet point at the beginning of a line to a simple "x" by touching on the "o". At best change "o"s to standard bigger checkboxes by activating a "touch checkbox mode".

This would enhance SimpleNote A LOT on touch devices. And as it's simple "o" and "x" there is no difference on desktop devices.

**Comment by GTD4life** [comment]
Very good and simple idea to implement checklist feature.
