### ISSUE TITLE
Split screen Android O build bug

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-android#531]
Howdy! We got some feedback from a developer friend:

> We've discovered a bug specific to your application running on the Android O build (https://developers.google.com/android/images) on Pixel C. Please see the following details:
> 
> Application name: "Simplenote (com.automattic.simplenote)"
> 
> Steps to reproduce the issue:
> 
> 1. Install app from the Google Play Store.
> 2. Launch the app in landscape mode and sign in.
> 3. Click on a note.
> 4. Click the information icon in the upper right.
> 5. Rotate the device or put the device into split screen mode.
> 
> Observed Results:
> a. The note is closed. 
> b. Clicking the "Note not published" option does nothing.
> 
> Expected Results:
> a. The note remains open. 
> b. Clicking "Note not published" allows the user to share the note.

On my Samsung S8 (Android 8.0.0) I was able to split the screen but I couldn’t see the information bar at the bottom so I believe that’s a bit different.

**Comment by hichamboushaba** [comment]
Same issue as  #1239, closing this one.
