### ISSUE TITLE
Nav Bar color for notes

### ISSUE THREAD

**Issue by abhijithvijayan** [Automattic/simplenote-android#542]
Color feature for notes could provide easiness in finding the similar notes.

Similar to ColorNote
![](https://i.imgur.com/4CK3Zte.png)

Switching from ColorNote wasn't easy for me

It's got Calendar, color feature, and Grid View and Pure Black mode.

If all these could be somehow injected to Simplenote.
It would be super awesome

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.

**Comment by RickyM7** [comment]
@theck13 Will this still be added at some point? I think that this would be a very good function and that it would help a lot in the organization, especially if it was like in the color note that you can classify the notes according to the color.

**Comment by theck13** [comment]
We don't have any plans to add a color to notes at the moment.

**Comment by RickyM7** [comment]
Understand. Thanks for the answer.
