### ISSUE TITLE
User logged out after setting the pin code for the very first time

### ISSUE THREAD

**Issue by zyousafi** [Automattic/simplenote-android#543]
**What Happened:**

The user installed the Simplenote app, used it for a few days without any issues, and then went into Settings to set the pin code for the very first time.

After they set the pin code, even though they were using the app without any issues before, they were logged out of the app.  The user did not explicitly press the **Logout** option.  The user then had to enter their password again, and since then the app and the pin code are working as expected.

**What Should Have Happened:**

The user should have been asked for a password when accessing the **Set Pin Code** option, but should not have been logged out after setting the pin code unless they explicitly clicked on the **Logout** option.

**Testing:**

I had to find an Android device first but when I did I was able to recreate this issue on a Samsung Galaxy device.

**User Interactions:**

[1187448-zen](https://woothemes.zendesk.com/agent/tickets/1187448)

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
