### ISSUE TITLE
The cursor goes massive when hovering on the edit panel

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/simplenote-android#545]
Hi there,

We got this from a user report. To reproduce this you would need to use a **Google Pixelbook (Chrome OS)**. Here's a screenshot that was sent by the user:

> When hovering over the edit panel of the app, the cursor becomes massive, 2-3 times larger than the height of the text.

![cursor](https://user-images.githubusercontent.com/3696121/42398887-4bb088c0-8131-11e8-998c-c23e3ac8cc80.jpg)

I tried to reproduce that using BlueStacks but I don't get a cursor there. 

Reported here #1254713-zen

**Comment by roundhill** [comment]
I also see a giant cursor on my Samsung Chromebook.
