### ISSUE TITLE
Searching notes brings up random results

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-android#546]
User is on a Huawei P10 Lite mobile device using 1.6.1.

In the search bar, they search for a term, but it highlights seemingly irrelevant results. 

Reported in 1266338-zen with screenshots. 

I've tried to reproduce but was not able to.

**Comment by lizswafford** [comment]
User reported that search does work on the desktop app, but still not on the mobile app.

1331012-zen.

**Comment by roundhill** [comment]
If we could get the actual search terms, that would be helpful!
