### ISSUE TITLE
Markdown <del> tag is not working

### ISSUE THREAD

**Issue by digiwizkid** [Automattic/simplenote-android#547]
Markdown `<del>` tag for strikethrough is not working on Android but is working on Ubuntu.

- Android 6.0, Simplenote 1.6.1

![screenshot_20180711-203842](https://user-images.githubusercontent.com/16302424/42582029-bee39468-854b-11e8-938f-30bf0c87bd00.png)

- Ubuntu 16.04 LTS, Simplenote 1.1.6

![del tag](https://user-images.githubusercontent.com/16302424/42581739-1450b6d4-854b-11e8-82be-98079742027f.png)

**Comment by roundhill** [comment]
Instead of using HTML tags, use `~striked~`.
