### ISSUE TITLE
Feature request: Pure black theme for AMOLED displays

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-android#549]
We received a feature request for a "pure black" theme for AMOLED displays. The user we spoke to would prefer this to the current dark theme. The user is using a Samsung Galaxy S8.

Source: 1284760-zen

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.

**Comment by chromer030** [comment]
Please add this theme , it's stylish and power saver.
Thank you.

**Comment by Donkey-Doug** [comment]
+1
