### ISSUE TITLE
Markdown Table Shows In Preview in Portrait but not Landscape

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-android#555]
User is reporting that markdown tables added to a note will show fine in a preview in portrait mode but not landscape. 

Device used: Android 10 inch tablet as well as Chromebook tablet

Screenshots: 
Portrait:
![portrait_thumb](https://user-images.githubusercontent.com/19782997/44805651-71ed1700-ab8a-11e8-9b19-cf96450914d8.png)

Landscape:
![landscape_thumb](https://user-images.githubusercontent.com/19782997/44805654-76193480-ab8a-11e8-9c5c-90494c6d4f46.png)

Reported in #1373173-zen

**Comment by PhiLhoSoft** [comment]
He is lucky because most users, including me and #392 and #499, don't see the tables at all.
BTW, the screenshots are unreadable here...
