### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Automattic/simplenote-android#556]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by roundhill** [comment]
I don't think we're interested in changing the logo for Simplenote at this time. But did you have an idea for using the current logo in a different way for the icon?

**Comment by roundhill** [comment]
cc @drw158 for any thoughts.

**Comment by mansya** [comment]
I'm happy to wait for opinions from @drw158
