### ISSUE TITLE
Loss of note changes on android app after sync /!\

### ISSUE THREAD

**Issue by pakal** [Automattic/simplenote-android#560]
I'm frightened after losing text with Simplenote, not only apps show nothing about the sync status of notes, but visibly servers *override* data on terminals instead of merging pending changes before.... 

#### Steps to reproduce
1. Exit a note in windows 10 Simplenote Client, eg. deleting a big chunk of text
2. Edit the same note on mobile Android app without letting it sync first (eg. Plane Mode), eg. add text after the chunk which is in pending deletion
3. Remove Plane Mode on mobile
4. Instead of merging the changes, the data is overwritten on mobile, losing the "pending insertion" chunk of text which was entered on mobile
5. The History of the note only deals with the data which was once stored on server, no trace of the added text

#### What I expected

Have an automatic merge of deletion+append, or a "merge conflict" at worst, not a brutal override of the mobile data with the server's one

#### What happened instead

Loss of text (= worst bug possible)

#### OS version

Windows 10 on PC, Android Oxygenos 5.0.5 on oneplus 3T

**Comment by roundhill** [comment]
Thanks for the report! I tried to reproduce it without much luck. Could you provide an example with the exact content and edits you've done? That'll help us fix it!

**Comment by pakal** [comment]
Sure, I've reproduced it numerous times just now (v1.1.6 on windows10 pc, v1.6.4 on oneplus3t smartphone).

Write this on a new note on PC, and let it sync with the phone.

```
test

Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.

On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum leur faux texte par défaut, et une recherche pour 'Lorem Ipsum' vous conduira vers de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter de petits clins d'oeil, voire des phrases embarassantes).
```

Then put the phone in "plane mode".

Delete the last paragraph on PC, put a short sentence INSTEAD at its place, and let the note sync with servers

Add sentences BEFORE and AFTER that last paragraph on the phone (no sync is possible due to airplane mode) ; also remove a word from said last paragraph (I dunno if it changes anything).

Then remove airplane mode from phone. Sync occurs.

The big last paragraph (although edited on phone) disappears from phone, replaced by the sentences BEFORE and INSTEAD above. **The AFTER sentence has disappeared.**

As a side note, I've never seen "merge conflicts" or the likes on simplenote, whereas like Git it should encounter such unsolvable situations, and let users deal with them.

**Comment by roundhill** [comment]
Thank you! I've tried this on multiple Simplenote clients, and pinned it down to something with the Android application.

**Comment by jessestu** [comment]
Thank you for working on this bug! A user is reporting it and kindly offering their own steps to reproduce in 1458648-zen:

```
I was wandering if it would be possible to have a merge error show up in case of desynchronising updates. Say i update a note when i have a spotty connection on mobile, and i make an edit in a Windows browser, when the mobile connects and sends, it often updates over the last update. Same, if i update the note Windows and it didn't get to be updated by the phone Android client, it stays like that and ignores the other update.

It's a bit hard to explain but i've had it a few times where i ended up with missed bits of text in my notes due to this.
```

**Comment by desnum** [comment]
A possibly related case: A customer lost revisions to his note (rather than losing the whole note itself) and we've ruled out syncing issues as he just uses the app on his Android device.

We checked version history and trash, but couldn't find the missing revision. 

Ticket: https://woothemes.zendesk.com/agent/tickets/1509244

I've asked the customer to follow up if he has any contributing details.

**Comment by Cosmitz** [comment]
Hey there, i'm the user from here:

> > I was wandering if it would be possible to have a merge error show up in case of desynchronising updates. Say i update a note when i have a spotty connection on mobile, and i make an edit in a Windows browser, when the mobile connects and sends, it often updates over the last update. Same, if i update the note Windows and it didn't get to be updated by the phone Android client, it stays like that and ignores the other update.
> 
> > It's a bit hard to explain but i've had it a few times where i ended up with missed bits of text in my notes due to this.

I had an instance yesterday which i think was tied to the app forcing me to sign back in/timing out the sessions. I use simplenote on my phone, on my home PC and on my work PC to keep some of my stuff in order. 

![image](https://user-images.githubusercontent.com/7086599/47956323-4f70e300-dfab-11e8-9d99-c5f2bffa4d8f.png)

I had updated my work simplenote, then my phone simple note, and upon returning home, i saw no changes in my home simplenote. The work simplenote had "No versions" listed, the home simplenote had "3 weeks" as the last one, and the phone/android one had some more recent. Either way, upon a page reload, it forced me to relog.

To note, both my home and work PC stay on 24/7 as do the browser instances and the simplenote instances.

**Comment by Cosmitz** [comment]
Sorry to bump this again but had it happen again today, the android app was showing no updates/revisions within the last day or so, even if had been was constantly scribbling them on the home desktop yesterday. When i checked the desktop,  it showed the correct up to date variant, and even after a window reload it kept the same data. However, it was not until i copied and pasted the text again and modified something that it started resynchronizing again. No 'sign in' screen this time.

**Comment by roundhill** [comment]
Thanks for the info everyone! We've discovered the source of the bug and are implementing a fix.

**Comment by Cosmitz** [comment]
That sounds great. I'll be waiting for a roll-out with bated breath.

**Comment by Cosmitz** [comment]
Just updating that right now, refreshing two simplenote tabs on two different computers. They're not syncing. Cleared cookies, new tabs. "changes you made may not be saved" warning on refresh even a few minutes after changing.

**Comment by theck13** [comment]
This was fixed in https://github.com/Simperium/simperium-android/pull/203 and released so I'll close this issue.  Feel free to reopen this issue if you still have problems.
