### ISSUE TITLE
Feature request: Custom URL for published notes

### ISSUE THREAD

**Issue by forteller** [Automattic/simplenote-android#574]
Publishing notes trough Simplenote is pretty sweet at the moment. But one thing is lacking: The URL is always very cryptic. It would be nice if you could set a username which would be used instead of the "app" part of the URL.

So today the published notes have the form of
https://app.simplenote.com/p/0JhQKl

My idea is just to change that to
https://username.simplenote.com/p/0JhQKl

for those who choose to set a username.

This would also make it possible, in the future, to add the function of listing all public notes from the same user on username.simplenote.com, if you like. But that's another story.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
