### ISSUE TITLE
 sharing notes via tag field in app fails

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-android#576]
#### Steps to reproduce
1. Open note in Andoid app 
2. Add email address as a tag (bottom) 
3. Wait for anything to happen 

#### What I expected
This used to be an easy and quick possibility to share a note with another person (see [#915](https://github.com/Automattic/simplenote-electron/issues/915) with simplenote-electron). I expected an email to be sent to the email address with a link to the note. 

#### What happened instead
Nothing ever happened. Has this functionality been discontinued? 

Suggestion if so: provide feedback to the user upon insertion of an email address as a tag to a note (“Sharing notes via tag has been discontinued. Press the Share icon in the toolbar to collaborate with another Simplenote user or publish a note.”) 

#### Simplenote version
1.6.5 

#### OS version
Android 8.0 (Oreo) 

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6254428/46992638-5a062e00-d10b-11e8-8b5a-59f081803825.png)

**Comment by roundhill** [comment]
Should work as long as the email belongs to an existing Simplenote user.

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.

**Comment by marianoju** [comment]
Apparently sharing notes via tag field in simplenote-android is *not* an issue anymore. This sharing function does *not* require the recipient to be an existing Simplenote user.

Email addresses inserted as a tag in simplenote-android still do not show up in simplenote-electron (tested with v1.4.0 for Ubuntu) while the content of the note *is* synchronized.

**Comment by theck13** [comment]
Since I can't reproduce it on Android, iOS, or macOS, I'll move this to the Electron repository.
