### ISSUE TITLE
Pin code: Pin code dots are too small

### ISSUE THREAD

**Issue by robertoissc** [Automattic/simplenote-android#578]
The pin code dots in the pin code view are too small.
Increase their size accordingly to the text field.
#### Steps to reproduce
1. Open pin code screen

#### What I expected
![g906](https://user-images.githubusercontent.com/5239138/47247666-b6e33c00-d3ca-11e8-94a6-496a91da8974.png)

#### What happened instead
![screenshot_20181019-180534](https://user-images.githubusercontent.com/5239138/47247682-c5c9ee80-d3ca-11e8-8ad7-8cbc60814ed7.png)

#### Simplenote version
1.6.5

**Comment by roundhill** [comment]
We would need to fix this in https://github.com/wordpress-mobile/PasscodeLock-Android I think, which is not longer being maintained...
