### ISSUE TITLE
Feature Proposal: Add an 'Auto' option to the theme selection options

### ISSUE THREAD

**Issue by iskandergaba** [Automattic/simplenote-android#581]
I use Simplenote at different times of the day. While I prefer the Light theme during the daylight, I also like the dark theme during the night. A very common use case is the user, i.e. me, writing some notes while on the bed just before sleeping. In this case, the light theme kind of hurts the eyes and the dark one is much more eye friendly.

I propose adding a third option, `Auto`, to the theme selection menu. If the user selects this option, the application will decide, upon start, on what theme to use depending on the time of day. Just like Twitter's application auto setting of night mode. I believe this is better than me switching back and forth between the themes.

I have already started exploring the code and I am planning to implement this myself as it seems to be fairly straightforward. However, I wanted to post this so that I can have an idea about what others think about this feature and whether it is worth it or not.

**Comment by robertoissc** [comment]
I think it's a good idea, I actually use that feature on Twitter...
I wonder how it decides to switch modes...
Twitter states that:
> night mode can be set to commence at sunset and turn off at sunrise

**Comment by iskandergaba** [comment]
> I think it's a good idea, I actually use that feature on Twitter...
> I wonder how it decides to switch modes...
> Twitter states that:
> 
> > night mode can be set to commence at sunset and turn off at sunrise

That is the idea @robertoissc. I want dark theme to commence at sunset and turn off at sunrise if `Auto` option is selected.

The way I want to do this is by using Android's `DayNight` Theme that was added to `AppCompat` with the realease of Support Library v23.2.0. I want to refactor the existing `Light` and `Dark` themes into a single `DayNight` theme and use built-in functionality to let it decide if it has to display `Dark` or `Light` theme when `Auto` is selected. Of course, all colour and theme values will be preserved and will remain the same. This is just a refactor, not a visual theme change.

## Benefits:
- No longer need to maintain two separate themes and therefore better development experience.
- The Day/Night detection is taken care of by the framework.

## Resources:
- https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94
- https://blog.iamsuleiman.com/daynight-theme-android-tutorial-example
- http://www.androidtutorialshub.com/android-daynight-theme-example-using-appcompat-support-library

**Comment by iskandergaba** [comment]
Implemented and merged. Please close this issue.
