### ISSUE TITLE
Unintentionally Swiping Screen Corrupts Note Content

### ISSUE THREAD

**Issue by billrobbins** [Automattic/simplenote-android#587]
This is a user reported bug that I have been unable to reproduce myself.  They did provide copies of the notes to show what they encountered.

#### Steps to reproduce
1.  User is editing a note.
2.  Unintentionally swipes the screen.
3.  Upon returning to the note, the text had been modified both in layout and content.
4.  User was able to restore the note via history, but is concerned about losing notes in the future accidentally.

#### What I expected
Swiping the screen would not affect the content of the note.

#### What happened instead
Both the layout and content of the note were altered.

#### Screenshot / Video
1502919-zd has the original and the corrupted versions of the note.

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.
