### ISSUE TITLE
Search does not work for Japanese text

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-android#594]
#### Steps to reproduce
1. Add a note in Japanese
2. Search for some of the existing text in the Android app's search bar

#### What I expected
To see the search results showing the Japanese note

#### What happened instead
Zero results
(note, this works on the Mac app and in the web app, but not Android)

#### Simplenote version
Android 1.6.5

#### OS version
Android 8.0.0

**Comment by msilbers** [comment]
The user said this just _started_ with 1.6.5 and that uninstalling and reinstalling did not help

**Comment by marcuswisecaesar** [comment]
User stated: 
"It will only match japanese text after a non-japanese character, and then wrongly highlight everything till a non-japanese character. Searching in between won't even return any results! For example searching あ in "あえいk" will wrongly highlight あえい, while searching for えい won't return any result at all."

**Steps to reproduce**
1. Search “んにち”
2. Search “こ”

**What happened instead**
1. will return nothing.
2. will highlight こんにちは, and will wrongly highlight everything till a non-japanese character

**Simplenote version**
Android 1.6.5

**OS version**
Android 8.0.0

**Comment by geriux** [comment]
Another user is having issues with the highlight of words in Japanese in #2467725-zd

**Comment by dmsnell** [comment]
> It will only match japanese text after a non-japanese character, and then wrongly highlight everything till a non-japanese character. 

That sounds a lot like we're using `\b` and `\B` somewhere in a RegExp pattern but I didn't see any obvious spot in the code.

**Comment by belcherj** [comment]
Another report: #2541908-zd

**Comment by theck13** [comment]
This is expected behavior.  Simplenote Android matches the full word from the beginning character of the word.

I have created a new issue, https://github.com/Automattic/Simplenote-United/issues/69, to use the same search method across platforms.
