### ISSUE TITLE
Menu misaligned with status bar

### ISSUE THREAD

**Issue by jakebornheimer** [Automattic/simplenote-android#598]
#### Steps to reproduce
1. Use Essential Phone (or maybe phone with notch)
2. Install new version of Simplenote
3. Open the hamburger button menu

#### What I expected

The menu should open _below_ the space that the status bar occupies.

#### What happened instead

As in the screenshot below, the menu opens _behind_ the status bar. The menu options are still accessible, but the "All Notes" menu item is partially obscured by the status bar, making it difficult to tap.

#### Simplenote version

1.1.6

#### Hardware

Phone: Essential Phone PH-1 (ver. 1.8)
(This phone has a central front-camera notch - may be related to this behaviour.)

#### Android version

9

#### Screenshot

![simplenotebug](https://user-images.githubusercontent.com/45367248/49031465-00683900-f178-11e8-9a36-b17c8b6edcf3.png)

**Comment by roundhill** [comment]
Thanks for the report, I can confirm this on an emulator with a notch:

<img width="264" alt="screen shot 2018-11-26 at 10 36 11 am" src="https://user-images.githubusercontent.com/789137/49034542-20dbc780-f167-11e8-8465-88e2d51fe41c.png">
