### ISSUE TITLE
searching in Android version implement differently from desktop, which makes it useless for Asian language.

### ISSUE THREAD

**Issue by rsyqvthv** [Automattic/simplenote-android#600]
I've reported this for Android version many times in Google Play review, seems they've been ignored.
Hope here works.

#### Steps to reproduce
1.  make note A  as "爱你"
2.  make note B  as "我爱你"
3.  searching with "爱"
4.  only returns note A.

#### What I expected

note A and B should both show up.

#### What happened instead

only shows note A

simplenote Android version only shows the search term in boundary, 
but lots of Asian characters need search in word. 
I believe this is same as #594 

#### Simplenote version

V1.6.6

#### OS version

Android 7.1

#### Screenshot / Video

in Android, left is the 2 notes, right side is after searching "爱", only one note returns.

![1086903136](https://user-images.githubusercontent.com/2230369/49167815-1c154000-f32e-11e8-9816-f8a9813027d5.png)

but in desktop, same implement shows 2 notes which is correct.

![1062001194](https://user-images.githubusercontent.com/2230369/49167849-2b948900-f32e-11e8-9acf-db124badda62.jpg)

**Comment by roundhill** [comment]
Unfortunately this isn't an easy fix due to the way the app uses FullTextSearch. See #227

**Comment by liviopv** [comment]
@roundhill Dan, a user reported a similar issue in #1848600-zen when searching for non-textual characters, like `@` or `#`. Searching for `@` works on the web app, but it fails on Android. Is that related to the way we implement `FullTextSearch` too?

If not, I can open a separate issue for it.

**Comment by liviopv** [comment]
@roundhill the same user from ^ also reported some inconsistency on the search when using Cyrillic characters. Can you confirm it's also due to the same implementation of `FullTextSearch`?

**Comment by roundhill** [comment]
@liviopv Can you have the user try uninstalling/resinstalling the app? The search index may need to be reset in order to get Cyrillic working. Full Text Search can't support the individual `#` `@` characters though...

**Comment by theck13** [comment]
This is expected behavior.  Simplenote Android matches the full word from the beginning character of the word.

I have created a new issue, https://github.com/Automattic/Simplenote-United/issues/69, to use the same search method across platforms.
