### ISSUE TITLE
Privacy: Recent app screen showing note contents, even when passcode is enabled

### ISSUE THREAD

**Issue by kriskorn** [Automattic/simplenote-android#602]
#### Steps to reproduce
1. Open Simplenote app
2. Write a note and minimize the app
3. Open the recent apps on your mobile device

#### What I expected

To see a Simplenote app splash screen or a logo.

#### What happened instead

Saw all of the contents of my note.

#### Simplenote version

1.6.3

#### OS version

8.1.0

#### Screenshot / Video

![android-recent-app-screen](https://user-images.githubusercontent.com/12064241/49517201-4160fb80-f8a4-11e8-8fcf-15408933cf2e.jpg)

#1620989-zen

**Comment by iskandergaba** [comment]
Good suggestion indeed. I will look into it soon.
