### ISSUE TITLE
Android Version 1.6.6. crashes permanently

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#603]
#### Steps to reproduce
Update to Android Version 1.6.6. 

#### What I expected
To read and edit my notes

#### What happened instead
It crashes / haltes after start.
Android askes me if I want to give Feedback.

#### Simplenote version
Android Version 1.6.6. 

#### OS version
Android 8.1.0 Oreo

**Comment by theck13** [comment]
Since it appears the crash was resolved after uninstall/install, I'll close this issue.  Feel free to reopen this issue if you're still seeing crashes.

Also, be sure to update to Simplenote 1.7.0 in case some the bugs removed since Simplenote 1.6.6 fix the issue.
