### ISSUE TITLE
(Request) Simple checklist feature

### ISSUE THREAD

**Issue by GTD4life** [Automattic/simplenote-android#605]
I love the idea #528 from CryptoStar2000. Unfortunately no one replied yet. 

Would it be possible to implement such a checklist feature? 

_This is definitely in the spirit of simplenote! :-)_

 Could be implemented as markdowns?

> Feature Request:
A simple mode for Android touch devices that changes a "o" bullet point at the beginning of a line to a simple "x" by touching on the "o". At best change "o"s to standard bigger checkboxes by activating a "touch checkbox mode".

> This would enhance SimpleNote A LOT on touch devices. And as it's simple "o" and "x" there is no difference on desktop devices.

Another solution to implement might be _Swipe on text to markdown formating_ #449 by CorentinLemaitre

**Comment by roundhill** [comment]
We're working on a pretty sweet checklist feature across all of the apps. Stay tuned :)

**Comment by GTD4life** [comment]
That sounds promising :-). Any small hint on the schedule?

**Comment by CryptoStar2000** [comment]
Nice. Maybe its going to be a christmas present? In the electron markup a similar idea is already implement (but complicated to realize on touch screens...).

**Comment by roundhill** [comment]
Should be early January! I can also get y'all a beta .apk if you want to help test it.

**Comment by CryptoStar2000** [comment]
That would be very nice of you :-). Just send it to CryptoStar2000@quantentunnel.de.  thx!!

**Comment by roundhill** [comment]
Here y'all go! Thanks for trying it out: https://github.com/Automattic/simplenote-android/releases/tag/v.1.6.8-beta
