### ISSUE TITLE
Feature Request: sync data without entering PIN

### ISSUE THREAD

**Issue by jessestu** [Automattic/simplenote-android#607]
A user in 1651423-zen requests this feature:

> Is it possible to add to the simplenote a function that synchronizes notes with the network without entering a PIN in the android application?

They add:

> Currently, to synchronize the data you need to enter a pin.

> I would like to automatically synchronize notes without touching the phone at the same time every day when I do not work on the phone for example. in the night when I'm sleeping. I would like to use the task schedule in my phone to run the simplenote application, then it will synchronize itself.

Please let me know how I can help with any next steps on this suggestion.

**Comment by onvpn** [comment]
This is a valuable remark, it is worth implementing

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
