### ISSUE TITLE
Notes List: Alphabetical sorting is case sensitive

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-android#609]
#### Steps to reproduce
1. Set up some notes using both capital and lowercase letters to start titles
2. Sort notes alphabetically, either A-Z or Z-A

#### What I expected
For the notes to be in alphabetical order, like on the MacOS app or the web app.

#### What happened instead
The titles starting with a capital letter are alphabetized, followed by the titles with lowercase letters in alphabetical order.
Like this:
Apple
Banana
Cat
Zebra
android
tabletop

#### Simplenote version
1.6.8 and the past few versions did this

#### OS version
Android 8.0.0
Samsung Galaxy S8

#### Screenshot / Video
![simplenote-notelist](https://user-images.githubusercontent.com/31680407/50388030-9ee4ad00-06d8-11e9-96cf-992161ee943a.jpg)

**Comment by ashercantrell** [comment]
Also reported in 1673736-zen

**Comment by Dmitry-Borodin** [comment]
Looks like ordering happens in https://github.com/Simperium/simperium-android library, that is responsible for querying the data. Looks like their bug.
But I didn't reproduce it.
Currently used version is 'com.simperium.android:simperium:0.7.1'

**Comment by rachelmcr** [comment]
I ran into this today while testing beta version 2.3-rc-2.

I almost always title notes with a capital letter, but I have some notes that start with "iOS" and it stood out that they weren't in alphabetical order with the other notes.
