### ISSUE TITLE
"Null" string appearing in Markdown preview when Dark at Night Only is enabled

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-android#615]
#### Steps to reproduce
1. Create a new note in Markdown
2. Click the Preview button

#### What I expected
Preview will only show text from the note with Markdown formatting applied

#### What happened instead
Markdown formatting was applied, but there is a "null" string at the top of the note -- turning off Dark at Night Only resolves the issue, though

#### Simplenote version
1.6.7

#### OS
Android 9.0 (Android One) running on a Xiaomi Mi A2

#### Screenshot / Video
![Note Text](http://cld.wthms.co/GlVNPJ+)
![Note Preview](http://cld.wthms.co/NVQhGG+)

**Comment by iskandergaba** [comment]
Hello, I noticed this as well. I believe this and #616 are both side effects of #580. Before this fix was introduced, things rendered just fine. @roundhill @robertoissc

**Comment by iskandergaba** [comment]
Thank you for reporting the issues in #615 and #616. I have located the problem and it appears to be a simple fix. I will push a fix for this in few minutes.
