### ISSUE TITLE
Manual switch from Dark at Night Only to Day only updates text area in Markdown preview

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-android#616]
#### Steps to reproduce
1. Activate Dark at Night Only
2. Switch to Day mode
3. Preview a note written with Markdown

#### What I expected
Entire view should be in the lighter Day mode

#### What happened instead
Text view displayed in Day mode, the rest of the interface remained in Dark mode

#### Simplenote version
1.6.7

#### OS version
Android 9.0 (Android One) running on a Xiaomi Mi A2

#### Screenshot / Video
![Preview of Markdown](http://cld.wthms.co/tueIyi+)

**Comment by iskandergaba** [comment]
Hello, I noticed this as well. I believe this and #615 are both side effects of #580. Before this fix was introduced, things rendered just fine. @roundhill @robertoissc

**Comment by iskandergaba** [comment]
Thank you for reporting the issues in #615 and #616. I have located the problem and it appears to be a simple fix. I will push a fix for this in few minutes.

**Comment by iskandergaba** [comment]
@roundhill, Check #617
