### ISSUE TITLE
[Feature Request] Hide notes tagged with e.g. "!archive" when "All notes" are shown

### ISSUE THREAD

**Issue by CryptoStar2000** [Automattic/simplenote-android#636]
It would be very great to have one tag, that is not displayed in "All notes" but is not trash. Maybe "!archive" or similar? That would increase overview.

I could tag some notes as e.g. "Relevant" and work with these only, but then I miss new shared notes since these haven't had this "Relevant" tag, yet. Hiding irrelevant/less important notes would solve this issue.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
