### ISSUE TITLE
Dark mode changes to light in landscape mode with keyboard open

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-android#641]
#### Steps to reproduce
1. Turn on Dark mode
2. Flip to landscape mode
3. Enter a note (it should stay in dark mode)
4. Tap into a note to type

#### What I expected
For it to stay in dark mode.

#### What happened instead
Switched to light, just in this view when the keyboard is open.

#### Simplenote version
1.6.9

#### OS version
Android 8.0

#### Screenshot / Video
![screenshot_20190208-133944_simplenote8099562935365401120](https://user-images.githubusercontent.com/31680407/52498563-29a93a80-2ba7-11e9-948c-953ef017f7a1.jpg)

**Comment by roundhill** [comment]
The OS takes control of the text editing when you switch a small-screen device to landscape. It does not appear to be possible to theme it. It makes it a better editing experience so we should leave it as-is for now.
