### ISSUE TITLE
Sharing: icons are all different sizes when sharing from note

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-android#642]
#### Steps to reproduce
1. Open a note
2. Tab the share icon

#### What I expected
For the app icons to all be the same size.

#### What happened instead
They are varying sizes, and I do not see this when sharing from another app.

#### Simplenote version
1.6.9

#### OS version
Android 8.0.0

#### Screenshot / Video
![screenshot_20190206-120808](https://user-images.githubusercontent.com/31680407/52499335-329b0b80-2ba9-11e9-92e2-e295d5b06510.png)
![screenshot_20190208-134756_simplenote5370503698852220765](https://user-images.githubusercontent.com/31680407/52499339-3464cf00-2ba9-11e9-85d6-b2c744bc5bf1.jpg)

**Comment by abdullahicyc** [comment]
I think i have this, WIP

**Comment by abdullahicyc** [comment]
WIP :)

**Comment by abdullahicyc** [comment]
I would like to work on this.
