### ISSUE TITLE
Some text becomes same color as background in dark mode

### ISSUE THREAD

**Issue by jwold** [Automattic/simplenote-android#651]
#### Steps to reproduce
1. Create a few notes in Simplenote, being sure to add titles and descriptions
2. Go to All Notes, so that you can see multiple notes at once
2. Switch back and forth between dark and light mode

#### What I expected

The title and description to be clearly visible in dark mode.

#### What happened instead

The title is no longer visible, as its text is the same gray as the background. 

When you tap a note to select it (but before releasing it), the description becomes hard to see. 

#### Simplenote version

1.7.0

#### OS version

Android-Version 8.1.0

#### Additional notes

This was reported by a user in 1835667-zen. I was unable to reproduce it as I didn't have the device mentioned. I will note that on my iOS device (iPhone X / iOS 12.1.4) I did not encounter the same issue.

**Comment by lizswafford** [comment]
The customer sent additional screenshots and device information. Noting it here just in case you didn't see them yet.

**Comment by theck13** [comment]
I cannot reproduce the behavior described in this issue or the ticket with Simplenote 2.2.0.  Feel free to reopen this issue if we receive more reports and include the following details.

Make|Model|Android Version|App Version
-|-|-|-
|||

Videos would be helpful as well.
