### ISSUE TITLE
Long notes crash the Simplenote app

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-android#657]
#### Steps to reproduce
1. Take the content from the Total.txt file and paste it in a note.
2. Try to open the note in the Simplenote app on your Android device.

#### What I expected
To see the note.

#### What happened instead
It crashed the note without any feedback

#### Simplenote version
1.7.0

#### OS version
Android 9

I tried with half of the note(first.txt) and it worked.

[Total.txt](https://github.com/Automattic/simplenote-android/files/3046420/Total.txt)
[FirstPart.txt](https://github.com/Automattic/simplenote-android/files/3046421/FirstPart.txt)

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.  Please, provide details about the device to help reproduce the issue if it is still crashing.
