### ISSUE TITLE
TAB key, Indentation and lists

### ISSUE THREAD

**Issue by tacocowboy** [Automattic/simplenote-android#658]
Hi there,

When I indent a list on the Windows App with the TAB key, there's no way to keep the same TAB on the android APP, I tried two spaces, 4 spaces...

Plus it doesn't keep the indentation either.

Example: I make a list on the Windows App, indent it. Go to the Android App, press enter to create a new line on the list and it doesn't keep the indentation. 

#### Steps to reproduce
1. Create a list on the Windows App with indentation
2. Open the Android App
3. Create a new line on the list

#### What I expected

Keep the same indentation

#### What happened instead

Doesn't keep the same indentation

#### Simplenote version

1.7.0

#### OS version

Android

#### Screenshot / Video

As it can be seen in the screenshot, the last empty line in the list it doesn't keep the same indentation that the previous lines nor the first parent one. It sits in the middle of both.

![Screenshot_20190405-094638_Simplenote](https://user-images.githubusercontent.com/37452516/55612470-9d6f5a00-5788-11e9-9f6f-c3bcfaa110b8.png)

**Comment by theck13** [comment]
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/58538087-9aee1700-81b1-11e9-9ba6-2ef01cf4e0cc.gif" width ="360">
