### ISSUE TITLE
When PIN lock enabled, content still visible when viewing phone's most recently used apps 

### ISSUE THREAD

**Issue by aswinanil** [Automattic/simplenote-android#660]
#### Steps to reproduce
1. Have PIN lock enabled
2. Navigate to any view where your content is visible
3. Exit the app
4. Open your phones recently used apps view

#### What I expected
The Simplenote preview in Android's recently used apps view should not display anything when passcode/fingerprint lock is enabled

#### What happened instead
The Simplenote preview in Android's recently used apps view shows my content undermining the purpose of the PIN lock feature

#### Simplenote version
1.7.0 (Android)

#### OS version
Android 9 PKQ1, MIUI Global 10.2 Stable

**Comment by robertoissc** [comment]
Seems like this is a duplicated issue. #602

**Comment by theck13** [comment]
Yep, this is a duplicate.
