### ISSUE TITLE
Two copies of the same note open on multiple tap.

### ISSUE THREAD

**Issue by jlarne** [Automattic/simplenote-android#661]
#### Steps to reproduce
1. Tap on a note multiple times quickly
2. (Multiples of the same note should open one on top of the other)
3. Edit text
4. Go 'back'
5. The same note should be displayed without the last edit
5a. (Further edits can be made to the note on the re-displayed window)
6. Return to main screen - the last edit is persisted.

#### What I expected
A single note to open.

#### What happened instead
The same note opens one after the other.  I am able to edit the text as usual.  After going 'back', I see the other (lower) notes which were opened first, and are without edits made (to the upper note windows).

On returning to the main screen (all notes closed), the last edit made is persisted, regardless of which note 'windows' were typed into.

#### Simplenote version
1.7.0

#### OS version
Android Go 8.1

**Comment by theck13** [comment]
I cannot reproduce the behavior described in this issue or the ticket with Simplenote 2.2.0.  Feel free to reopen this issue if we receive more reports and include the following details.

Make|Model|Android Version|App Version
-|-|-|-
|||

**Comment by jlarne** [comment]
Tyler,

   This issue is absolutely still happening for me.  It has not changed regardless of version number.  I might even go further to say that now, when a second 'version' of a note  opens, and it is edited, when going backwards (next being the 'first opened note', then list of notes), the edit is discarded.  Perhaps this was always happening, though I hadn't seen that problem before.

   It appears that all of this has to do with speed.  I have several documents with 20,000+ characters.  They are quite slow to open.  I am seriously concerned about data loss in such case (which is frequent for me).  I have to be diligent to make sure that the notes are opening only 'once'.

**Comment by jlarne** [comment]
Nokia 1 (TA-1056)
Android 9
Simplenote 2.2
