### ISSUE TITLE
Markdown preview doesn't support HTML tags

### ISSUE THREAD

**Issue by maxme** [Automattic/simplenote-android#662]
This has been reported by one of our user:

#### Steps to reproduce
1. Add the `<br>` tag in a note.
2. Preview
3. 💥 you see `<br>` in the preview (should create a newline)

**Comment by theck13** [comment]
Parsing HTML tags for the ***Preview*** tab was removed in https://github.com/Automattic/simplenote-android/pull/481.  Please, notify the user mentioned that it is expected behavior.
