### ISSUE TITLE
Swipe on note list to trash to match iOS

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-android#663]
It has been requested by a user to be able to swipe on a note in the list of notes to be able to trash it or perhaps even access other note options.

This is currently how it works on iOS, if you swipe to the left on a note in the list of notes screen you get a button to trash the post.

With Android you can long touch on a note to be able to bulk select and delete notes.

It would seem to make sense to have actions be the same on the different platforms.

Ticket reference: #30749117-zd

**Comment by theck13** [comment]
I added this to our feature requests.
