### ISSUE TITLE
Google Login: Please add "Sign up & Sign in with Google Account" option

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-android#664]
WordPress Android already has this very useful and must have feature. As a hardcore Simplenote user I think its missing in Simplenote Android app. Please add this feature as soon as possible. 
@theck13

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.

**Comment by Donboscow** [comment]
Any Estimated time of arrival? @theck13
