### ISSUE TITLE
Replace ListView with RecyclerView

### ISSUE THREAD

**Issue by semal259** [Automattic/simplenote-android#665]
I think it would be wise if the existing ListView is replaced with RecyclerView?

**Comment by theck13** [comment]
Yes, in general, `RecyclerView` is better than `ListView`.  Is there a specific `ListView` usage that is causing a problem?

**Comment by semal259** [comment]
I was trying to implement #663 to add swipe gesture, turns out `ListView` has no support for swipe gestures. I was wondering to replace with `RecyclerView`

**Comment by theck13** [comment]
`RecyclerView` doesn't have swipe-to-whatever out of the box either.  We can update `ListView` to `RecyclerView` in the same changes when adding swipe-to-delete if we think it's necessary, but I don't think a separate issue is required.
