### ISSUE TITLE
Drawer partially obscured by system bar

### ISSUE THREAD

**Issue by nbradbury** [Automattic/simplenote-android#668]
While testing #666 on an API 28 emulator, I noticed the drawer is overlapped by the system bar.

![Screenshot_1556625595](https://user-images.githubusercontent.com/3903757/56960547-35a9f600-6b1f-11e9-8bdc-6595fd22eebb.png)

**Comment by robertoissc** [comment]
I believe this is a duplicate of #598 and fixed on #644 :)

**Comment by nbradbury** [comment]
> I believe this is a duplicate of #598 and fixed on #644 :)

Apologies, @robertoissc - you're right, it is a dup. I'll close this issue. Thanks!
