### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by jodastephen** [Automattic/simplenote-android#674]
No sync is occurring from/to the Android app.

* I installed the app and used the web application to create some notes.
* The notes appeared in the Android app correctly.
* The next day I added a new note in the Android app.
* The new note is not syncing to the server.
* When I try to log out it warns me that I have unsynced notes.
* A new note created in the web application is not syncing to the Android app

I've also tried publishing the new note from the Android app, but that fails as well.

Is this supposed to "just work" automatically? Why is there no "sync status" information box, or "sync now" button?  From my perspective it looks like the main feature of a cloud-based note taking app (syncing notes) simply doesn't work.

**Environment**
Please include:
- Device: OnePlus6T
- Android: v9
- Oxygen OS 9.0.13 security patch 2019.3
- Simplenote version: 1.7.0

**Comment by jodastephen** [comment]
The sync is now working. Did you have an outage?

There is definitely a need for more information in the Android app and the web application as to the status of the sync.

**Comment by Robertght** [comment]
Hey @jodastephen !

I can't see any outages at that date.

Aside from the Android device, have you used a different device to write the notes on the web app? 
If yes, what browser and OS were you running?

**Comment by jodastephen** [comment]
I have only used the Android device above, and Chrome on Windows. Generally, the system has been fairly stable, although I did have to use the history to retrieve data on another occasion where it had been deleted.

**Comment by theck13** [comment]
Since it appears the syncing has been resolved, I'll close this issue.  Feel free to reopen it if you're still having syncing problems.

**Comment by amineHorseman** [comment]
Hi, I'm having the same issue, notes written from the android app are not synchronized with the server. And the new notes written in the web version do not appear in the android app, even after synchronizing.

I tried to log out and login again, it loads all the old notes but not the new ones (looks like it loads only the modifications made before July 29th). Same issue with deleted notes after July 29th are not trashed in the android app.

**Environment:**
- Simplenote v 1.8.2
- Android 7.0
