### ISSUE TITLE
Add ability to edit a note in "full screen mode"

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-android#683]
Currently editing a note on a tablet, the note list is always visible:

![5CIFbRQ66_ZRf_WdiBT0oD4_lnkcqNrpUhdIpsNahz-w5J-QWfSfD6KBtDh7tG9AWVMx28AxKlklTaviFdDF04PJqffTEneoHoDx4SIm370WARjlmx7EGN66qSNMU4ZnLyXnDPeK27bnkelB8yv_gOT7PF04BB7gtj0XrcQ2KgOTEecS8sLDUijeZ3cAn0BGh1qKmHKg34GfJUgNPQwMyvMhKNty9](https://user-images.githubusercontent.com/154014/58288217-8e645b80-7d78-11e9-8387-0c49884c3d0e.jpg)

On the other clients (macOS, iOS, Electron) we have the ability to edit a note in full screen. For example, here is note editing on an iPad:

![iPad](https://user-images.githubusercontent.com/154014/58288302-cb305280-7d78-11e9-8a14-b091633cb6a4.gif)

It we be great to add this full screen editing experience to the Android client.

**Comment by iskandergaba** [comment]
I got this. PR soon.

**Comment by iskandergaba** [comment]
This has been implemented and merged on #707 and will appear in 2.0 version of the app. If no further comments, please consider closing this issue.
