### ISSUE TITLE
Android enhancement: external keyboard key functionality

### ISSUE THREAD

**Issue by jroedel** [Automattic/simplenote-android#684]
I am using the latest version of Simplenote to date on Android 9, Xiaomi Mi A1. I use a Logitech K380 Bluetooth keyboard, and I use Simplenote usually upwards of 20 times a day with this configuration. I wish there was better support for external keyboards... details following.
### What

ESC key: should go back to the list of notes where one can navigate notes.

TAB key: should create a tab of 4 spaces like it does in the desktop version (at least in my Linux version). Also, when the user is currently in a list item, the spaces should be added before the dash.

Ctrl-TAB: should take on the present functionality of TAB which is to toggle between the various UI buttons and the tags text box.

UP and DOWN arrows: perhaps this is better handled in Issue #328 where I left a comment, but the scrolling is weird especially while using a keyboard on long notes.

Ctrl-B, Ctrl-I, Ctrl-U: add markdown formatting for Bold, Italics and Underlined respectively. 

Ctrl-1, Ctrl-2, Ctrl-3: adjust the number of '#' characters at the beginning of the current line to create markdown headers of 1st, 2nd or 3rd level respectively. 

### Why

This would be a HUGE plus for those of us taking markdown notes with bluetooth keyboards. ESPECIALLY, taking live notes such as in class or meetings.

**Comment by theck13** [comment]
Thanks for the suggestion!  I have added it to our feature requests.
