### ISSUE TITLE
Number of notes per tag (notes count) 

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#687]
### What
I want to see the number of notes per tag (notes count). 

### Why
I want to know how many notes I have. 
This helps also for consistency / synchron ization check between various devices. 

### How
Like in the Web Version, where this feature already exists.

**Comment by theck13** [comment]
The number of notes per tag is shown on the ***Edit Tags*** screen.  Open the navigation drawer and tap the ***Edit*** button next to the ***Tags*** header.  The number of notes for each tag is on the right side of the row in the list.

**Comment by gubrist** [comment]
![20190531_172219](https://user-images.githubusercontent.com/22197180/58716299-052cd480-83c9-11e9-9f89-e150a6ffe7f6.jpg)

Only one tag shows a number and this one is wrong.

**Comment by theck13** [comment]
Can you confirm there is more than one note with the "Geocaching" tag ***on that device***?  I'm guessing that number represents how many notes on that specific device have that tag.

**Comment by gubrist** [comment]
![20190531_180452](https://user-images.githubusercontent.com/22197180/58718934-d44f9e00-83ce-11e9-8f80-1f56f7dcad6a.jpg)

**Comment by theck13** [comment]
Yep, it appears there are more than one note with the "Geocaching" tag.  That is a bug rather than a feature request.

I suggest going through the process I mentioned in https://github.com/Automattic/simplenote-android/issues/669#issuecomment-497050488 on the fault device.

**Comment by gubrist** [comment]
> Yep, it appears there are more than one note with the "Geocaching" tag. That is a bug rather than a feature request.

Where shall I report this bug?

It apears on my both Android devices.

**Comment by theck13** [comment]
We already have an open issue for that, https://github.com/Automattic/simplenote-android/issues/239.
