### ISSUE TITLE
Automatic reordering and deletion of checked items

### ISSUE THREAD

**Issue by melboiko** [Automattic/simplenote-android#706]
I'm migrating from Google Keep and I use Simplenote for shopping lists and TODO lists.  The checkbox feature is useful for that, but in my opinion it would work much better if it had the following 2 functions seen in other apps:

 - Checked items are moved to the bottom of the list.
 - A command to delete all checked items.

Thank you for your work!

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.
