### ISSUE TITLE
Clicking on the first tag in the list does not open the list of notes

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-android#708]
### Expected
Clicking on the first tag in the list opens a list of notes assigned to that tag.

### Observed
Clicking on the first tag in the list does not do anything.

### Reproduced
1. Open the navigation drawer
2. Click on the first tag in the list - nothing happens

### Devices
Make|Model|Android Version|App Version
-|-|-|-
Nexus|6P|27|1.7.0
Google|Pixel 3A|28|1.7.0

**Comment by theck13** [comment]
I'm unable to reproduce that behavior with the devices below.  I tested both alphabetical and non-alphabetical tag sorting.  The first tag in the navigation drawer list showed the correct notes with that tag in both cases.  See the animation [here](https://drive.google.com/open?id=1_diT74VBAyR2bw1wP3WuVdR6uPEp_18o) for illustration.

Make|Model|Android Version|App Version
-|-|-|-
Nexus|6P|27|1.7.0
Google|Pixel 2|25|1.7.0

This _may_ be related to some open tag issues (https://github.com/Automattic/simplenote-android/issues/239, https://github.com/Automattic/simplenote-android/issues/279).  Can you confirm your devices have the same tags and counts as the web (i.e. app.simplenote.com)?  If not, then it's probably related to one or more of the open tag issues.
