### ISSUE TITLE
Note counts in Edit Tag List not working for uppercased tags

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-android#709]
### Expected
A tag that begins with an uppercase letter correctly shows the number of notes assigned to that tag in the Edit Tags view.

### Observed
If a tag begins with an uppercase letter, the number of notes is not populated

### Reproduced
1. Create a tag that begins with an uppercase letter
2. Assign this tag to multiple documents
3. Open the navigation drawer
4. Click `EDIT` button next to `Tags`
5. Verify the number of documents for the uppercase tag is blank

<img src="https://user-images.githubusercontent.com/5810477/59650948-3df8d780-9145-11e9-9401-fd22b728e211.gif" width="300"/>

### Devices
Make|Model|Android Version|App Version
-|-|-|-
Nexus|6P|27|1.7.0
Google|Pixel 3A|28|1.7.0

**Comment by iskandergaba** [comment]
Easy. PR soon.
