### ISSUE TITLE
Editing a list in a note crashes Simplenote

### ISSUE THREAD

**Issue by veesahni** [Automattic/simplenote-android#732]
### Expected
Adding a new item to a list in a note just works.  In fact, I believe when I tap the on-screen enter key, it creates a new line and automatically prepends the starting "-"

To be clear, an example of a list:
\- line 1
\- line 2
\- line 3

### Observed
Adding a new line to a list is causes simplenote to crash

The following do not fix the problem:
- clearing cache
- restarting the device
- clearing all storage
- uninstalling and reinstalling the app

I can see this behavior happening on two identical devices, configuration listed below.

### Reproduced

Open a note with a list, like:

\- line 1
\- line 2
\- line 3

Tap into the end of line 2

Tap the on-screen enter key

Simplenote crashes, every time.

### Devices 

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 2|Android 9 July Security Patch|1.8.0

**Comment by pards** [comment]
Also happens on Galaxy S8 running Android 8.0.0 and kernel 3.18.91-16008568-QB236988411
