### ISSUE TITLE
Chrome OS: Enter/Return Key Does Not Insert New Line

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-android#741]
### Expected
Pressing the **_Enter_**/**_Return_** key on an external keyboard does insert a new line into a note on Chrome OS.

### Observed
Pressing the **_Enter_**/**_Return_** key on an external keyboard does not insert a new line into a note on Chrome OS.  Pressing the **_Shift_** and **_Enter_**/**_Return_** keys does insert a new line.

### Reproduced
1. Open any note.
2. Press **_Enter_**/**_Return_** key.
3. Notice new line is not inserted.
4. Press **_Shift_** and **_Enter_**/**_Return_** keys.
5. Notice new line is inserted.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel Slate|75.0.3770.129|1.8.1

**Comment by mgalbritton** [comment]
On the Pixelbook, Shift+enter/return does not start a new line. It advances the cursor to the tags field. 
#2171760-zen

**Comment by cecoates** [comment]
I can repro on my Pixelbook. Except shift+enter works for me.

Chrome OS Version 75.0.3770.102 (Official Build) (64-bit)

Simplenote 1.8.1 for Android

A regular "enter" sends you to the tag field. You have to very carefully hold shift, then hit enter to get a new line.

It feels counterintuitive so I've switched to using the web app.

**Comment by erricgunawan** [comment]
Reported in 2520662-zen 

Chromebook. Simplenote 2.2

**Comment by sarahfg** [comment]
Reported in #2586687-zen

**Comment by theck13** [comment]
This is a [bug in Chrome OS](https://bugs.chromium.org/p/chromium/issues/detail?id=1021729) affecting all Android apps with multiline input fields (i.e. `EditText`).  It was fixed in Chrome OS 80, which is scheduled to be released today.  Pressing the **_Enter_** key will work as expected in Simplenote Android once the device is updated to Chrome OS 80.
