### ISSUE TITLE
strikethrough <s> markdown not working on android app

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/simplenote-android#754]
When on the android app, trying to use `<s> strike </s>`, the markdown does not format correctly. The `~~strike~~` works fine though.

When I wrote this text on the simplenote android app-

```
~~strikethrough using android app~~

~~strikethrough using android app 2~~

<s>strike this</s>
```

![image](https://user-images.githubusercontent.com/40609190/61478394-0df45c80-a9af-11e9-8a9c-e8686960ec54.png)

### Expected

![image](https://user-images.githubusercontent.com/40609190/61478235-beae2c00-a9ae-11e9-8258-9e5110c4668c.png)

### Observed

![image](https://user-images.githubusercontent.com/40609190/61478363-fe751380-a9ae-11e9-9d59-27bdc71b2155.png)

### Reproduced

To reproduce the issue, open the simplenote android app-
 1. Create a new note or open an old one.
 2. Tap on 'info' button and enable Markdown.
 3. Write something like `<s> strike 1 </s>`.
 4. Go to Preview to see the formatted text.

I was able to reproduce the issue consistently. On more than one android devices.

Make|Model|Android Version|App Version
-|-|-|-
Xiaomi|Reedmi 6 Pro|9| 1.8.2

Make|Model|Android Version|App Version
-|-|-|-
Samsung|S9|9| 1.8.2

**Comment by ahmadbaig1** [comment]
Reported here zd-2189172

**Comment by theck13** [comment]
Parsing HTML tags for the ***Preview*** tab was removed in https://github.com/Automattic/simplenote-android/pull/481.   Please, notify the user that it is expected behavior.

**Comment by ahmadbaig1** [comment]
Thanks! Informed the user, will keep in mind!
