### ISSUE TITLE
Deleted tags reappear after logging out and logging in again

### ISSUE THREAD

**Issue by robertoissc** [Automattic/simplenote-android#755]
### Expected
Deleted tags don't reappear after logging out/in.

### Observed
Deleted tags reappear after logging out and logging in again.

### Reproduced
1. Open tags list
2. Delete a few tags
3. Notice tags are removed from the list
4. Log out
5. Log in
6. Notice tags reappear as if they had not been removed

Make|Model|Android Version|App Version
-|-|-|-
Huawei|P20|8.1.0|1.8.2

**Comment by robertoissc** [comment]
Related to #279

**Comment by theck13** [comment]
Looking at this snippet from [my comment](https://github.com/Automattic/simplenote-android/issues/279#issuecomment-494211170) in #279, we can close this ticket as a duplicate.
> Logging out/in causes the tag to reappear in tag list on Android.
