### ISSUE TITLE
Bangla unicode search problem

### ISSUE THREAD

**Issue by v3coder** [Automattic/simplenote-android#760]
In english search working with word. But in bangla its traeger bangla alphabet (smashing) so its become critical to search.

I am searching for রোহান & simplenote give me 25 results. Though i have the word রোহান in only one note.

See the screenshot. Plz fix it.

![IMG_20181208_130434_760](https://user-images.githubusercontent.com/39517042/62186104-cdb9b480-b386-11e9-9656-7bccc6e22e43.jpg)
![Screenshot_20181208-125110](https://user-images.githubusercontent.com/39517042/62186106-ce524b00-b386-11e9-8e15-a6e7ac72c198.png)

I have test it on multiple different brand device. Its not working.
Samsung A1
Walton Primo NF2+

I am using Latest version of simplenote from playstore

**Comment by reginabally** [comment]
Another report in 3544589-zen with Marathi/Indian text.

Device: Samsung-M21 (SM-M215F/DS)
OS: Android 10
App version: 2.12(123) (I've asked them to update to 2.13 and test again)

Edit by @rezzap: User advised that after update to 2.13, the issue remains.
