### ISSUE TITLE
Duplicate Note/Tag Removal Tool

### ISSUE THREAD

**Issue by admagnificat** [Automattic/simplenote-android#770]
### What

I am requesting a duplicate removal tool for both notes and tags.
 
### Why

Related to my previous bug report regarding sync issues and duplicate tags and notes, a duplicate removal tool might be very helpful to remove large numbers of duplicate notes and tags in bulk.

[The real problem is sync, I think, but a duplicate removal tool might (or might not) help.]

Many thanks again for all of your hard work on this wonderful utility!

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.
