### ISSUE TITLE
Cannot find notes while using Chinese characters

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-android#793]
When searching for a note which has Chinese character that's not the first inside the title or the content, you won't see any results. 

### Expected
To be able to find the notes by other characters as well

### Observed
I wasn't able to find any note while searching for a different character than the first one.

### Reproduced
> 1. Add the following content in a note: 
``` 
这是一个中文标题 This is a Chinese title 
接下来是一段中文正文笔记。Next is a Chinese body 
``` 
> 2. Try to search for a Chinese character, but the first one inside the title or content of the note.
> 3. While the first character can be found, the others inside the title or content won't display the note.

Tested on web+macOS as well, but I could only replicate it on my Android phone.

Make|Model|Android Version|App Version
-|-|-|-
Samsung|8+|9.0.1|1.82
Sony | Xperia 1 | n/a |1.82

**Comment by theck13** [comment]
This may be related to https://github.com/Automattic/simplenote-android/issues/594 and/or https://github.com/Automattic/simplenote-android/issues/760.

**Comment by Robertght** [comment]
@theck13 Thanks! It looks similar to #594 indeed. If it looks like a duplicate, we can close it.

**Comment by theck13** [comment]
This is expected behavior.  Simplenote Android matches the full word from the beginning character of the word.

I have created a new issue, https://github.com/Automattic/Simplenote-United/issues/69, to use the same search method across platforms.
