### ISSUE TITLE
New note app shortcut creates continuous loop of new notes

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-android#797]
Creating a note using the app shortcut causes a continuous loop of new notes when trying to hit "up" after finishing the note. 

### Expected
Hitting "up" will show the note list

### Observed
Hitting "up" creates a new note

### Reproduced
1. Make sure the app is closed and not in the background
2. Long-press on the app icon and click **New Note**
3. Type some text
4. Hit the "up" button in the toolbar
5. Notice a new note is created and displayed. This behavior will loop continuously.

<img src="https://user-images.githubusercontent.com/5810477/64037664-088c4500-cb0b-11e9-957a-a05405120e0e.gif" width="300"/>

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 3a (emulator)|28|2.0-rc-1

**Comment by theck13** [comment]
I wasn't able to reproduce that behavior.  I ran the steps provided on the devices below.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 3|28|2.0-rc-1
Google|Pixel 3a (emulator)|28|2.0-rc-1
Google|Pixel 2 (emulator)|25|2.0-rc-1

See the animation below for illustration using a Google Pixel 3a (emulator).

<a href="https://user-images.githubusercontent.com/3827611/64041885-d20bf580-cb1d-11e9-83d0-d872c8fc1ec5.gif"><img src="https://user-images.githubusercontent.com/3827611/64041885-d20bf580-cb1d-11e9-83d0-d872c8fc1ec5.gif" width="320"></a>

**Comment by AmandaRiu** [comment]
Hrm, I rebuilt my emulator and the issue went away so I'm guessing this was local to my emulator. Closing ticket.
