### ISSUE TITLE
Please add "Sign in with Google" option

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-android#858]
### What
***Please kindly add "Sign up & Sign in with Google Account" option***

### Why
***Then we can easily sign in Simplenote from desktop, mobile & web without any hassle***

**Comment by theck13** [comment]
Closing since this is a duplicate of https://github.com/Automattic/simplenote-android/issues/664.

**Comment by Donboscow** [comment]
Any ETA? @theck13

**Comment by belcherj** [comment]
No eta.
