### ISSUE TITLE
Line breaks (br) aren't shown properly in Markdown previews

### ISSUE THREAD

**Issue by idkwhatusernameuse** [Automattic/simplenote-android#860]
Line breaks aren't shown properly in notes.

### Expected
Put a line break where there's a `<br>` tag

### Observed
`<br>` tags are shown, instead of putting a line break. Happens on the Android app but on the Linux app (Electron), it doesn't happen.

### Reproduced
> 1. Create a note.
> 2. Activate Markdown in the note.
> 3. Write a note where `<br>` tags are used.
> 4. Preview note.

I've attached a screen recording, showing the bug (zipped because GitHub won't allow me to upload an MP4 file)

[screenrecording.zip](https://github.com/Automattic/simplenote-android/files/3781366/screenrecording.zip)

Make|Model|Android Version|App Version
-|-|-|-
Xiaomi|Poco F1|9.0 (Pixel Experience ROM)|2.1

**Comment by theck13** [comment]
HTML is escaped on the _*Preview*_ tab intentionally as described in https://github.com/Automattic/simplenote-android/pull/481.

> a markdown note with an html form in it could be used to gather sensitive data from a user.
