### ISSUE TITLE
Update Async Task Classes to Avoid Leaks

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-android#864]
Update all inner classes that extend `AsyncTask` and are not `static` to avoid context leaks (e.g. [`emptyTrashTask`](https://github.com/Automattic/simplenote-android/blob/bdb1196c8942bf542e8c99b035c23a828c190ce9/Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java#L1291), [`loadNoteTask`](https://github.com/Automattic/simplenote-android/blob/42b753ad78c8693f6e38ec95b19b61fcb88a30d6/Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java#L137), [`pinNotesTask`](https://github.com/Automattic/simplenote-android/blob/bdb1196c8942bf542e8c99b035c23a828c190ce9/Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java#L867), [`refreshListTask`](https://github.com/Automattic/simplenote-android/blob/bdb1196c8942bf542e8c99b035c23a828c190ce9/Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java#L822), [`refreshListForSearchTask`](https://github.com/Automattic/simplenote-android/pull/857/files/5a395971482df22d07e74de8e9b2453335f45983#diff-291124c3836fdaed5786d9e1f5aab559R1027), [`removeTagFromNotesTask`](https://github.com/Automattic/simplenote-android/blob/a34e7ac8ef6f2cedc8d19a1e105ea56873e8377e/Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java#L194), [`trashNotesTask`](https://github.com/Automattic/simplenote-android/blob/bdb1196c8942bf542e8c99b035c23a828c190ce9/Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java#L908)).

**Comment by iskandergaba** [comment]
Hello!

It looks like this issue hasn't been dealt with yet. The problem with making an `AsyncTask` class `static` is that all global variables and methods inside the parent `Activity` class have to be turned static, and the global variables and methods used inside of those methods as well, and so on recursively.

Luckily, it appears that there is a simple solution to this. We can use a `WeakReference` to the parent activity inside the nested `AsyncTask` class. An example of that can be found [here](https://stackoverflow.com/a/49571060).

I already tried to apply that on `emptyTrashTask` and it worked fine. It is a clean solution that would spare us from turning everything into `static` unnecessarily inside the `Activity` class.

It should be noted however that if tasks are memory intensive and last a long time, the weak reference may be collected by garbage collector while in `doInBackground` and then the app runs into a `NullPointerException`. To fight that, we can use a variant  of the same called `SoftReference` which will ensure the garbage collector would not collect it before the required job is done (or the app runs out of memory).

**I believe that `SoftReference` is the way to go.**

Below is an example implementation:
```java
import java.lang.ref.SoftReference;
...
new emptyTrashTask(NotesActivity.this).executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
...
private static class emptyTrashTask extends AsyncTask<Void, Void, Void> {

        private SoftReference<NotesActivity> activityRef;

        emptyTrashTask(NotesActivity context) {
            activityRef = new SoftReference<>(context);
        }

        @Override
        protected Void doInBackground(Void... voids) {
            NotesActivity activity = activityRef.get();
            if (activity.mNotesBucket == null) return null;

            Query<Note> query = Note.allDeleted(activity.mNotesBucket);
            Bucket.ObjectCursor c = query.execute();
            while (c.moveToNext()) {
                c.getObject().delete();
            }

            return null;
        }

        @Override
        protected void onPostExecute(Void nada) {
            NotesActivity activity = activityRef.get();
            activity.showDetailPlaceholder();
        }
}
```

I am including a couple of articles regarding `WeakReference` and `SoftReference` below. I want to get your opinion before proceeding with this solution. Let me know.

**References:**
- [Link 0](https://javarevisited.blogspot.com/2014/03/difference-between-weakreference-vs-softreference-phantom-strong-reference-java.html)
- [Link 1](https://www.logicbig.com/tutorials/core-java-tutorial/gc/soft-vs-weak-ref.html)

**Comment by theck13** [comment]
> It looks like this issue hasn't been dealt with yet. The problem with making an `AsyncTask` class `static` is that all global variables and methods inside the parent `Activity` class have to be turned static, and the global variables and methods used inside of those methods as well, and so on recursively.

Yes, exactly.

> Luckily, it appears that there is a simple solution to this. We can use a `WeakReference` to the parent activity inside the nested `AsyncTask` class. An example of that can be found [here](https://stackoverflow.com/a/49571060).

Yep!  We're actually doing this same thing for `AsyncTask`s elsewhere in the code (i.e. [CreateNoteActivity.SendNoteTask](https://github.com/Automattic/simplenote-android/blob/3f26d23084eb14719fa913a7898bf25ac96ba1f5/Wear/src/main/java/com/automattic/simplenote/CreateNoteActivity.java#L50-L55), [NoteEditorFragment.LoadNoteTask](https://github.com/Automattic/simplenote-android/blob/3f26d23084eb14719fa913a7898bf25ac96ba1f5/Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java#L1262-L1267), [PreferencesFragment.SignOutAsyncTask](https://github.com/Automattic/simplenote-android/blob/3f26d23084eb14719fa913a7898bf25ac96ba1f5/Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java#L315-L320)).

> I believe that `SoftReference` is the way to go.

It's true that a `SoftReference` is likely to stick around longer than a `WeakReference`.  Like you mentioned, an `AsyncTask` could produce a `NullPointerException` if the garbage collector decides to clear `Reference` objects.  Due to those two reasons, I think using a `WeakReference` would actually help us detect whether our code needs to be rearchitected.  If we start receiving `NullPointerException` crashes due to an `AsyncTask` with a `WeakReference`, then we need to rethink what that `AsyncTask` is doing.  Since this issue is meant to avoid leaks and remove the lint warnings for inner classes that extend `AsyncTask` and are not `static`, using a `SoftReference` or `WeakReference` would work.

Thanks for the thorough analysis, @iskandergaba!  Feel free to open up a pull request with your proposed changes and I'll review it as soon as possible.
