### ISSUE TITLE
Simplenote Completely down 

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-android#878]
**From last two days can't log in simplenote with simplenote-electron, app.simplenote.com web version and simplenote android app. Simplenote backend is completely down. When contacting through simplenote.com/contact-us/ they are not responding.**

**Comment by theck13** [comment]
Simplenote is not down.  I've had no problems logging in on multiple devices and platforms the last two days.  Reach out to us at support@simplenoteapp.com for help.

In the future, use the template for creating issues.
