### ISSUE TITLE
Bold headings in markdown editor mode

### ISSUE THREAD

**Issue by jivox92362** [Automattic/simplenote-android#885]
### What
The macOS version of Simplenote bolds headings in the editor while writing markdown notes, making it easier to visualize sections of content.

### Why
Bold headings provide better visibility of text.

#### Simplenote macOS screenshot
Notice the bold text of the ## h2.
![Simplenote macOS screenshot](https://camo.githubusercontent.com/e76dd08cc4c41300479865fb4c24c8dbd525d028/68747470733a2f2f73696d706c656e6f7465626c6f672e66696c65732e776f726470726573732e636f6d2f323031382f30322f73637265656e2d73686f742d323031382d30322d32302d61742d322d30382d31352d706d2e706e673f773d31333330)

#### Atom markdown screenshot
![screenshot-20191117-031010](https://user-images.githubusercontent.com/57426891/69006705-cf809700-08e7-11ea-8fbb-d0c3acd631eb.png)

### Related issues
* https://github.com/Automattic/simplenote-electron/issues/1578
* https://github.com/Automattic/simplenote-electron/pull/1727

**Comment by jivox92362** [comment]
A workaround for this is to convert your heading text to **Math sans bold** glyphs and copying it back to the Simplenote document.

https://qaz.wtf/u/convert.cgi?text=Copy+the+Math+sans+bold+text

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.

**Comment by jivox92362** [comment]
Bold headings were added to the macOS version with markdown support in Automattic/simplenote-macos#169.

There's a discussion for inclusion in the electron version at Automattic/simplenote-electron#1727.
