### ISSUE TITLE
Missing undo/redo functionality

### ISSUE THREAD

**Issue by andrey-starodubtsev** [Automattic/simplenote-android#888]
It's very frustrating when you type a text and then suddenly lose it (or part of it) due to awkward move or accidental touch of a screen. 

Sadly, Android has no intrinsic functionality of Undo/Redo. But some applications implement it as a separate feature. For example, Google Keep has one (https://support.google.com/keep/answer/2888246?co=GENIE.Platform%3DAndroid&hl=en&oco=1).

It would be nice to have similar feature in Simplenote for Android.

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.

You can undo and redo note content by tapping the "History" action and restoring a previous version. You can restore deleted notes by viewing the note in the "Trash" and tapping the "Restore note" action.

**Comment by daoxi** [comment]
> Thanks for the suggestion! I have added it to our feature requests.
> 
> You can undo and redo note content by tapping the "History" action and restoring a previous version. You can restore deleted notes by viewing the note in the "Trash" and tapping the "Restore note" action.

That's unfortunately more of a workaround, not a real solution, the "History" feature seems to require internet access (I'm getting the message "couldn't retrieve history"), it'd be inconvenient if a note app requires internet access just to undo/redo changes.

**Comment by bobmatyas** [comment]
Another request for this on 11631656-zen
