### ISSUE TITLE
kitkat?

### ISSUE THREAD

**Issue by caspertone2003** [Automattic/simplenote-android#899]
Any (old) release is working on kitkat?
Thanks

**Comment by theck13** [comment]
Devices below Android 6.0 can use Simplenote 1.8.2 and below.  Previous versions of Simplenote can be downloaded and installed from https://github.com/Automattic/simplenote-android/releases.

**Comment by caspertone2003** [comment]
Thanks for the answer!
the bug label was not my intention, I am not aware of how to label ... please apologize me!
