### ISSUE TITLE
App returns to summary screen after usinng hyphes

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-android#902]
Kindle Fire HD 8 throws the user to the summary screen after using hyphens in markdown mode. #2532773-zd

### Expected
Should not throw the user to the summary screen when using hyphens in markdown. 

### Observed
Throws the user to the summary screen.

### Reproduced
From HE:
I was able to replicate this same issue on a Kindle Fire 7, but only in a note that was a list. I had the same issue again when creating a list in a new note. When you type in a new item in the list and then click enter to add the next item the screen goes blank and brings you back to the original screen. It doesn't seem to be any open issues for Kindle devices that I can see. This didn't happen in the regular Android app.

**Comment by theck13** [comment]
Amazon Kindles are not officially supported.
