### ISSUE TITLE
Search: Sort order changes affect note list sorting when app is closed during search

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#907]
### Expected

I expect that the note list sort order will not be affected by the search sort order.

### Observed

If I go back to the note list, the note sort order is not affected by the search sort order.

However, if the app is closed while doing a search, any changes to the search sort order affect the note list sort order when the app is reopened.

### Reproduced

1. Open the app and confirm the note sort order (under Settings > Sort order).
2. Start a new search.
3. Enter any text to search your notes.
4. Notice that the search results use the same sort order as your notes list.
5. Change the sort order and/or direction for the search.
6. Tap the back arrow to go back to the notes list and notice that it has the original note sort order.
7. Start another new search.
8. Enter any text to search your notes.
9. Change the sort order and/or direction for the search.
10. Force close the app.
11. Reopen the app and notice that the notes list is using the selected sort order and direction from your last search (also saved under Settings > Sort order).

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.3-rc-2

**Comment by jorgecasariego** [comment]
In addition to this behaviour I am noticing the same thing in two similar situations:

**Pressing Home Button** 

**Reproduced**
1. Open the app and confirm the note sort order (under Settings > Sort order).
2. Start a new search.
3. Enter any text to search your notes.
4. Notice that the search results use the same sort order as your notes list.
5. Change the sort order and/or direction for the search.
6. Tap the back arrow to go back to the notes list and notice that it has the original note sort order.
7. Start another new search.
8. Enter any text to search your notes.
9. Change the sort order and/or direction for the search.
10. Press Home Button
11. Reopen the app and notice that the notes list is using the selected sort order and direction from your last search (also saved under Settings > Sort order).


**Pressing Overview Button**
**Reproduced**
1. Open the app and confirm the note sort order (under Settings > Sort order).
2. Start a new search.
3. Enter any text to search your notes.
4. Notice that the search results use the same sort order as your notes list.
5. Change the sort order and/or direction for the search.
6. Tap the back arrow to go back to the notes list and notice that it has the original note sort order.
7. Start another new search.
8. Enter any text to search your notes.
9. Change the sort order and/or direction for the search.
10. Press the Overview Button
11. Press the Simple Note window to show the search results  
12. Press Back button and notice that the notes list is using the selected sort order and direction from your last search (also saved under Settings > Sort order).

**Comment by pachlava** [comment]
[testing] fix/feature verified on Samsung A31 | Android 10 | Simplenote 2.17-rc-1

The sorting UX was reworked and the issue described here is no longer an issue, because of SortBar addition
