### ISSUE TITLE
Sharing Broken to Simplenote from Google now + Firefox

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-android#917]
### Expected
When I share content with the app I expect a note to be created with that content. Just one note should be made, with the title of the site as the title of the note and the URL as the first piece of content.

### Observed
When an article from Google Now is shared to Simplenote multiple copies of a note with that URL are created. When a link is shared from Firefox no note is created. The app simply opens.

The sharing seems to work as expected from other apps tested like Chrome, Airbnb, Google Maps, Pinterest, or the WordPress app reader.

### Reproduced
1. Open up Google now's recommended articles. I do this on my Pixel by swiping from left to right on the homescreen
2. Select an article
3. Select the share icon
4. Select Simplenote
5. Exit the note just created in Simplenote. You'll see multiple copies of that same note

1. Open a URL in Firefox
2. Select the share icon
3. Select the Simplenote icon
4. Simplenote will open but no note will be made

Android 10|Simplenote 2.2
Android 10|Simplenote 2.3

Ticket: #2585883-zen

**Comment by theck13** [comment]
I was able to create a single note while sharing from both Firefox and Google Now with Simplenote 1.8.2 through 2.3.0-rc3.  In other words, I wasn't able to recreate the issue.  Simplenote uses the standard sharing mechanism and accepts any text type (i.e. `text/*`).  How that text is sent to Simplenote is up to the sending app.  The only time Simplenote does not do anything is if the text received from the sending app is empty.

> The sharing seems to work as expected from other apps tested like Chrome, Airbnb, Google Maps, Pinterest, or the WordPress app reader.

Due to that, I would expect the issue to be with the sending app or the operating system sending the text rather than Simplenote.

Are there issues sharing from Firefox or Google Now with any other app listed when you tap the ***Share*** action?

**Comment by sarahfg** [comment]
I'm unable to reproduce this with other by sharing to other services. I've tried the usual note-taking alternatives like Keep and Evernote in Android to see if it's something about the note format. I've also tried sharing to email and messaging services without getting the duplication issue the user and I experience in Simplenote. 

The user has also reported the issue in Youtube, but I wasn't able to reproduce that in Simplenote

**Comment by msilbers** [comment]
reported in #3287249-zen

> Often, when I share a link to SimpleNote, that link fits well into a new note, but after that when I go back to the main list, a new note is created and the link fits into it.

video attached in email

**Comment by rossanafmenezes** [comment]
> reported in #3287249-zen
> 
> > Often, when I share a link to SimpleNote, that link fits well into a new note, but after that when I go back to the main list, a new note is created and the link fits into it.
> 
> video attached in email

Regarding the reported above by @msilbers 👍 

Device: Samsung A7 2018
*Android* : 10
*SimpleNote* : 2.9

User also added the following information:

When the described behavior occurs, there are two cases that arise:

*1/* If I completely close the Simplenote application, then the behavior
is repeated

*2/* If I don't close the Simplenote application, the behavior does not
recur but a second instance of Simpleneote is created, and it's the same
every time this behavior recurs

**Comment by ParaskP7** [comment]
I was able to reproduce the issue and can verify that something weird is happening. Although, I am not yet sure whether this an OS problem or Simplenote itself. I'll keep investigating to get to the bottom of it.

So far I have the below table:

| Browser | Action | Simplenote in Background | Result | Comments |
| --- | --- | --- | --- | --- |
| Google Now | Share | No | ✅ | Works as expected. |
| Google Now | Share | Yes | ⚠️ | Works, but two instances of Simplenote start existing, side-by-side. Somehow Google Now, which wasn't in the device recents before, starts existing in it as Simplenote. |
| Chrome | Share | No | ⚠️ | Works, but Chrome gets transformed to Simplenote, in device recents. However, this is not the case when Simplenote gets backgrounded right away. |
| Chrome | Share | YES | ⚠️ | Works, but two instances of Simplenote start existing, side-by-side. Chrome gets transformed to Simplenote, in device recents. |
| Chrome | Quick Share | No | ✅ | Works as expected. |
| Chrome | Quick Share | Yes | ❌ | Doesn't work. |
| Firefox | Share | No | ✅ | Works as expected. |
| Firefox | Share | Yes | ✅ | Works as expected. |

For all those cases above, after having Simplenote launched in multiple instances, trying to keep sharing from different browsers, and any combination of those, results in more unpredictable behaviours. More Simplenote instances can be created, working side by side, while sharing sharing was working before for a specific case, now it can stop, etc.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 4|11|2.14-rc-1
