### ISSUE TITLE
Enable Markdown Live Preview

### ISSUE THREAD

**Issue by wchest** [Automattic/simplenote-android#918]
This is essentially the same feature request already submitted for [simplenote-ios#24](https://github.com/Automattic/simplenote-ios/issues/305) and [simplenote-macos#326](https://github.com/Automattic/simplenote-macos/issues/326), but it would be great if there was an option for live preview mode for markdown text. The main use case is that formatted markdown is easier to read and prevents users from having to switch between edit and preview mode.

Ideally, the implementation would simply update the formatting as you type. So when you type `# Heading` it would automatically be formatted as an H1, typing `**some bold text**` would make the text bold, etc.

Here's an example from Dropbox Paper's markdown live preview:

![markdown-preview-3](https://user-images.githubusercontent.com/470326/71760355-3a266b80-2e71-11ea-9153-b09e5263161b.gif)

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.

In the future, use the template for creating issues.

**Comment by wchest** [comment]
@theck13 - Thanks for the feedback. I'll be sure to use the template in the future.
