### ISSUE TITLE
Landscape View in Preview with a Table Zoomed in

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-android#919]
### Expected
The size of text in all notes should be consistent for all notes in both portrait and landscape orientation. All text should be viewable 

### Observed
When a note includes a table in markdown the preview text gets weirdly zoomed in on landscape orientation. It isn't possible to read all text in the note for this reason

### Reproduced
1. Open up Simplenote on an Android phone
2. Enable Markdown on a note 
3. Add a table to the note
4. Look at the note Preview in landscape orientation on the phone.

#### Text with no table
![](https://d.pr/i/0cqSPv+)
(Image link: https://d.pr/i/0cqSPv )

#### Text with table
![](https://d.pr/i/UPMXpW+)
(Image link: https://d.pr/i/UPMXpW )

Make|Model|Android Version|App Version
-|-|-|-
Pixel|3|Android 10| 2.3
Galaxy Note|10|Android 9|

User reported #2590146-zen

**Comment by hichamboushaba** [comment]
Closed by #1247
