### ISSUE TITLE
Add auto-sync and notifications

### ISSUE THREAD

**Issue by gamato** [Automattic/simplenote-android#920]
Please allow the app to auto-sync -- either to be able to sync without being launched, or at least when being in background -- and whenever it auto-syncs please show a notification if and when any changes have been detected.

Right now if someone modifies a shared note there is no notification and thus no way to notice what (and when) has changed, which makes shared notes a very limited feature.

**Comment by theck13** [comment]
I have added it to our feature requests.  In the future, use the template for creating issues.
