### ISSUE TITLE
Not able to login in development build of the app 

### ISSUE THREAD

**Issue by manu-chroma** [Automattic/simplenote-android#948]
Setup an Android Emulator and not able to login into the app in it.

**Comment by theck13** [comment]
Are you using an existing Simplenote account?

**Comment by manu-chroma** [comment]
I am trying to use an account I created almost a week back on Simplnote debug (this one I installed on my actual android device)

**Comment by theck13** [comment]
Be sure to read the [***How to Configure***](https://github.com/Automattic/simplenote-android#how-to-configure) section of the [`README.md`](https://github.com/Automattic/simplenote-android/blob/f87fd8282e11f7c192e16cd644974389f08e5f0a/README.md).  In there you will see that using an existing account will not work and data will be cleared periodically.

> Create a new account in order to use a development build. Logging in with an existing Simplenote account won't work.  Use the account for **testing purposes only** as all note data will be periodically cleared out on the server.

Using an actual device or emulator will have the same results.

**Comment by manu-chroma** [comment]
Hi, thanks for your reply. 

This was an issue of javax.net.ssl.SSLHandshakeException: Unacceptable certificate due a separate certificate installed on my device which was causing the auth to fail when I tried using the android emulator. Should've looked at the logs before opening an issue! :)

**Comment by theck13** [comment]
Thanks for the update.  I'm glad you got it working!
