### ISSUE TITLE
Crash: Changing device language with a note open crashes the app

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#959]
The app crashes when I switch between languages with a note open. I observed this while switching between UK English and either Spanish or German.

With a markdown note open, I got this NullPointerException: `Attempt to invoke virtual method 'void com.automattic.simplenote.NoteMarkdownFragment.updateMarkdown(java.lang.String)' on a null object reference`. In Sentry: [SIMPLENOTE-ANDROID-11B](https://sentry.io/share/issue/09db54c3cf3a49528b72eef209d823b8/)

With a non-markdown note open, I got this NullPointerException: `Attempt to invoke virtual method 'boolean androidx.fragment.app.Fragment.isAdded()' on a null object reference`. In Sentry: [SIMPLENOTE-ANDROID-11C](https://sentry.io/share/issue/57caf1efe44245ccb63ed8bf2aa0b97e/)

### Reproduced

1. Open the app and select a markdown note in the notes list to open the editor.
2. Change your device language (e.g. from UK English to Spanish).
3. Return to the app. Result: Crash.
4. Open the app again and select a non-markdown note.
5. Change your device language (e.g. from Spanish back to UK English).
6. Return to the app. Result: Crash.

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.4-rc-3

There are no other reports of either of these exact crashes, and I wouldn't expect users to commonly switch languages at this point, but I wanted to report it in case resolving this case could help with resolving other, more common crashes.

**Comment by theck13** [comment]
Thanks for the report, @rachelmcr!  I was able to reproduce the crashes both cases.

There seem to be multiple crashes with the same stack trace and probably the same cause, but Sentry does not consolidate them from what I see.  It looks like the crash has been occurring since the Simplenote Android 2.2.0 release, but the volume has been low.

**Comment by theck13** [comment]
Due to the low volume and specific circumstances causing the crash, I'm going to move this to the Simplenote Groundskeeping project and work on it during the next Hack Week on March 9th.
