### ISSUE TITLE
Widget: Notes List widget has unexpected behavior after logout

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-android#984]
### Expected

If I log out of the app after adding a Notes List Widget to my device home screen, I expect to see the prompt "Log in to use widget" and see the welcome screen when I tap the widget.

### Observed

Right after I log out of the widget, I see the prompt "Log in to use widget" but when I tap it a new note is opened. After that, the widget is blank (no login prompt).

Also, if I resize the widget while logged out of the app, when the widget is large enough the new note button will appear.

### Reproduced

1. Log in to the app.
2. Add the notes list widget to the device home screen.
3. Confirm the notes list widget works as expected (opening a note in the list or creating a new note).
4. Log out of the app.
5. Confirm the notes list widget shows the "Log in to use widget" message as expected.
6. Tap on the notes list widget and notice that it opens a new note in the note editor, instead of taking you to the login screen.

<img src="https://user-images.githubusercontent.com/8658164/76332829-bfeaeb00-62e8-11ea-83f6-015dbb69c689.png" width="50%">

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.5-rc-1

**Comment by theck13** [comment]
> 6. Tap on the notes list widget and notice that it opens a new note in the note editor, instead of taking you to the login screen.

I'm unable to reproduce this exactly.  If I tap the _*New Note*_ button, then a new note is created, but I'm taken to the login/signup screen if I tap anywhere else in the widget.  Can you confirm you're seeing the same behavior?

**Comment by rachelmcr** [comment]
No, when I tap anywhere on the widget immediately after logging out, it creates a new note. Here's a quick screencast showing that behavior: https://cloudup.com/cQoOz4VT8MW

**Comment by theck13** [comment]
Hmm, I think I performed the same steps from your screencast, but I'm seeing something different.  See the video <a href="https://heckofanapp.files.wordpress.com/2020/03/984_list_widget_button.mp4">here</a> for illustration.  There is definitely something wrong going on that your screencast shows.  Aside from the ***New Note*** button being shown after resizing, the ***Log in to use widget*** text disappears when you exit the app after tapping the widget following the logout.  Are you using the default Nexus/Pixel launcher or another one?

**Comment by rachelmcr** [comment]
I'm using the Moto App Launcher (the default launcher on my moto e5 play).

**Comment by theck13** [comment]
I'm unable to install the Moto App Launcher APK on my devices.  I'm not sure if it is created for Motorola devices specifically.  Are you able to install the [Nexus/Pixel launcher](https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher) on your device?  If so, we can confirm whether it's the launcher, device, or widget.

**Comment by theck13** [comment]
I was able to reproduce the new note bug with the Pixel launcher, but not with the Nova launcher, which was used in the [video I shared](https://heckofanapp.files.wordpress.com/2020/03/984_list_widget_button.mp4).  I confirmed a fix for the Pixel launcher, but I would like for you to test it with the Moto launcher.  I'll request your review in the pull request shortly.
