### ISSUE TITLE
Duplicate hit on search results during sync problems.

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-android#995]
A User is reporting the following which I think may be worth looking into further:

> The android app occasionally produces a large number of duplicate hits on a single note even when the note contains only one occurrence of the search field. The extraneous hits also highlight found strings which do not match the search field. Rather, they are displaced a few characters from the correct match. This bug does not occur in the web interface, nor does it occurs in the windows version, just in the Android app.
> 
> I suspect it might be accessing items in the note history instead of the most recent note, but if so it's not consistent in that it only occurs in a small fraction of the notes in the database.
> 
> It turns out this problem occurs if and only if Simplenote is failing to synchronize. This happens sometimes when I access a note from multiple devices and notes are not synchronizing: I'll have three versions of the same note on three different devices. My internet connection is working properly, but perhaps not to your server.
> 
> This happens for a period of several minutes from time to time. Eventually the sync stabilizes to one version, but then if I do a search I get the odd duplications you saw in the screenshots I sent you in my original email. This is "solved" by deleting the corruped note (and thence its history) and recreating it (select all, copy, delete note, create note, paste).

They added the following: 

> One note somehow gets corrupted after I have made multiple edits to it from different machines. I can tell it is corrupted because when I am searching through all my notes for a particular string I get multiple hits (sometimes 20 or 30) on this single corrupted record.

>  This problem happens only when I'm having synchronization problems. The changes I have made to a particular note on device 1 are not making it to device 2, and vice versa, at least not immediately. Sometimes it takes half an hour for changes made to the note on device 1 to propagate through to device 2. Things get scrambled.

They sent the following screenshot which is quite blurry but hope to get a better one next time this replicates.
![IMG_20200214_165121](https://user-images.githubusercontent.com/10325627/77149919-94a39100-6a8a-11ea-8b9b-9fa496ac91a0.jpg)

**(EMUI) version of android 7 on a Huawei Mediapad tablet running Simplenote 2.4.**

2800420-zen

**Comment by belcherj** [comment]
Please use the issue template as it helps triage and diagnose issues.

**Comment by melindahelt** [comment]
The user replied and added:

> Your interpretation is correct except that the search results problem continues even after everything has completed synching. Indeed, sometimes I don't notice it until days have passed. Thanks.

**Comment by ParaskP7** [comment]
👋 @rezzap !

After you sent an email to the user, they user came back to us with the `I am no longer experiencing this problem using the latest beta version on Android 9, and have not for some time now. Thanks for fixing the problem.`!

It seems that this was a one of event and was fixed by updating the app and or Android version.

I am guessing that this issue can now be closed. Would you mind closing it for us?
