### ISSUE TITLE
Automated backup for simplenote notes on cloud service providers

### ISSUE THREAD

**Issue by manu-chroma** [Automattic/simplenote-android#999]
Before discussing feature request, I want to say, I've deep appreciation for the people working on simplenote and their choice to keep the platform code open source.
 
### What
Regular automatic backup feature for simplenote, which can connect to any of the popular cloud storage provider, eg: google drive to backup all your notes periodically in some simple access format for example: plain text files. 

### Why
I've started using simplenote as serious user (using for pretty much noting down anything), given the simplicity of the product and availability on all major platforms. 

I want to ensure, in case of any sort of incident, that my notes are safe. For this, I want to have ability to setup backups outside simplenote storage boundaries. 

I know there is a feature to export notes on the web app but it is hard to perform manual trigger for that. 

### How
Either this can be periodic trigger to backup all the notes or it can also be to manually trigger export notes to the to the connected cloud provider. 

Thanks again!

**Comment by theck13** [comment]
Thanks for the suggestion! I have added it to our feature requests.
